### ISSUE TITLE
[Refactor] html package has setup error on python 3

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#10]
Forced to edit setup.py to get html package installed.
Known problem, noted in google search

**Comment by tomasg2012** [comment]
It occurred to me that the html package isn't even imported in the program, I'll have to remove that from the requirements.

**Comment by jbobzin-insyde** [comment]
Is imported.  No sure if used.

Sent from my Windows Phone
________________________________

**Comment by jbobzin-insyde** [comment]
Maybe Soup does the import?
Program did not start without it.

**Comment by tomasg2012** [comment]
Ah, that is correct.  I think it's because BeautifulSoup uses the parser from package html.  That can be replaced with another parser, but not sure how that harms the logic of the program.  I've read that there are better parsers available.

**Comment by jbobzin-insyde** [comment]
It seems html package is not getting active support. Which argues for possible replacement.
But the patch to get it to install is trivial and does not change operation. 
So maybe you just need to note details of how to install in instructions.

**Comment by tomasg2012** [comment]
Are you sure the program doesn't start without it?  I don't seem to have html installed.  I just want to make sure if it's not my python environment being busted.

**Comment by tomasg2012** [comment]
I'm closing this issue unless the html problem is still a thing: afaik it is not a problem to not have html imported or installed.
