### ISSUE TITLE
syntax error causing exception on an error

### ISSUE THREAD

**Issue by pwvancil** [DMTF/Redfish-Service-Validator#102]
in file: RedfishServiceValidator.py around line 130,
     if not paramPass:
 rsvLogger.error("{}: Expected Entity type {}, but not found in type inheritance {}".format((name, (propType, propCollectionType), allTypes)))
.
the statement has bug.
too many parentheses reduces format tuple to 2 entries.    causes tuple exception.
.
patch fix that worked:
rsvLogger.error("{}: Expected Entity type {}, but not found in type inheritance {}".format(name, (propType, propCollectionType), allTypes))

**Comment by tomasg2012** [comment]
Thank you, this is actually already a commit in 09-27-enhancements, but it has not been pulled yet.

**Comment by tomasg2012** [comment]
Closed as of PR 104.
