### ISSUE TITLE
Absent '@odata.id' in arrays causes exception

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#105]
If an array element does not contain an odata.id, the tool throws an exception:
~~~
ERROR - Something went wrong
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 614, in validateSingleURI
    propMessages, propCounts = checkPropertyConformance(node.soup, prop.name, prop.propDict, propResourceObj.jsondata, node.refs)
  File "RedfishServiceValidator.py", line 469, in checkPropertyConformance
    paramPass = validateEntity(PropertyName, val, propType, propCollectionType, soup, refs, autoExpand)
  File "RedfishServiceValidator.py", line 83, in validateEntity
    uri = val['@odata.id']
KeyError: '@odata.id'
ERROR - Power.v1_0_0.Power:Redundancy:  Could not finish check on this property
ERROR - PowerControl: Appears to be an extra property (check inheritance or casing?)
~~~

While this may also be a spec/schema issue (don't believe odata.id is required for *all* array types), that's a separate issue...

**Comment by mraineri** [comment]
It's required for anything that's defined as an EntityType in CSDL (such as the Redundancy entity).

**Comment by billdodd** [comment]
Thanks Jeff for opening this issue and Mike for your comments.

The function that is encountering the exception, validateEntity(), is only called for items that are an EntityType. So @odata.id should be present. But the function should check for that first before trying to reference it and generate an appropriate error message.
