### ISSUE TITLE
[refactor] Testing from Windows, error line 26 due to bad log file name string

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#11]
Running on windows, line 26 fails with FileNotFoundError. The log file name path has lots of \\ in the string which may be cause.

**Comment by tomasg2012** [comment]
Is there a directory created for logs?  If there is, then it seems to be an os dependent oversight, needs something like os.dir to stitch it together.

**Comment by jbobzin-insyde** [comment]
If the directory 'logs' is created manually outside the program, then this error is not seen.
