### ISSUE TITLE
UnicodeEncodeError occurred when generating html log

### ISSUE THREAD

**Issue by PuwenHsiao** [DMTF/Redfish-Service-Validator#116]
Hello,

I saw the error message when generating html log

Traceback (most recent call last):
  File "C:/Users/puwen/PycharmProjects/Redfish-Service-Validator/RedfishServiceValidator.py", line 1103, in <module>
    sys.exit(main(sys.argv))
  File "C:/Users/puwen/PycharmProjects/Redfish-Service-Validator/RedfishServiceValidator.py", line 1083, in main
    f.write(htmlPage)
UnicodeEncodeError: 'cp950' codec can't encode character '\xa9' in position 895214: illegal multibyte sequence

My environment is
  Windows 10 x64
  Default system UI language: zh-TW

I had tried to fix by adding encoding and it seems to have worked.

with open(datetime.strftime(startTick, os.path.join(logpath, "ConformanceHtmlLog_%m_%d_%Y_%H%M%S.html")), 'w', **encoding='UTF-8'**) as f:

**Comment by billdodd** [comment]
Thanks for reporting the error. It does look like adding the encoding param to the open() is the correct fix. I'll fix in my next Pull request.

**Comment by tomasg2012** [comment]
This can maybe be fast tracked in a bug fix merge,  if you feel it appropriate, or it can wait, nbd.
