### ISSUE TITLE
Validation error on String properties that are nullable

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#117]
Running into validation errors on properties that are defined in CSDL as Collection(Edm.String), but are nullable (there is no "Nullable = false" in CSDL). 

For instance:

SoftwareInventory UefiDevicePath is defined in CSDL as:
        <Property Name="UefiDevicePaths" Type="Collection(Edm.String)">

And the JsonSchema is:
               "UefiDevicePaths": {
                    "type": "array",
                    "items": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },

This particular implementation shows it as null:

    "UefiDevicePaths": [
        null
    ],

But the service validator errors out:

INFO - SoftwareInventory.v1_1_0.SoftwareInventory:UefiDevicePaths
INFO - 	value: [None] <class 'list'>
INFO - 	has Type: Collection(Edm.String) Edm.String
INFO - 	is Optional
INFO - 	is Collection
ERROR - SoftwareInventory.v1_1_0.SoftwareInventory:UefiDevicePaths: Expected string value, got type <class 'NoneType'>
INFO - 	FAIL

**Comment by tomasg2012** [comment]
Correct, the program assumes wrongly about the Nullable for collections.  It tests if the list itself is null, not individual items in the list.

Will be fixed.
