### ISSUE TITLE
Error on missing mandatory properties that are implemented

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#121]
Service validator is failing with the following errors:

/redfish/v1/Chassis/1/Power/Redundancy/PSU

ERROR - Redundancy.v1_0_0.Redundancy:Name: Mandatory prop does not exist
ERROR - Redundancy.v1_0_0.Redundancy:Mode: Mandatory prop does not exist
ERROR - Redundancy.v1_0_0.Redundancy:MaxNumSupported: Mandatory prop does not exist
ERROR - Redundancy.v1_0_0.Redundancy:MinNumNeeded: Mandatory prop does not exist
ERROR - Redundancy.v1_0_0.Redundancy:Status: Mandatory prop does not exist
ERROR - Redundancy.v1_0_0.Redundancy:RedundancySet: Mandatory prop does not exist

But these properties are implemented:

GET @ /redfish/v1/Chassis/1/Power/Redundancy/PSU

{
    "RedundancySet@odata.navigationLink": "/redfish/v1/Chassis/1/Power/Redundancy/PSU/RedundancySet",
    "@odata.id": "/redfish/v1/Chassis/1/Power/Redundancy/PSU",
    "Status": {
        "State": "Enabled",
        "Health": "OK"
    },
    "RedundancySet@odata.count": 0,
    "Name": "PSU Redundancy",
    "@odata.context": "/redfish/v1/$metadata#Redundancy.Redundancy",
    "RedundancySet": [],
    },
    "@odata.type": "#Redundancy.v1_2_0.Redundancy",
    "MemberId": "PSU",
    "MinNumNeeded": 2,
    "MaxNumSupported": 2,
    "Mode": "N+m",
    "RedundancyEnabled": true
}

**Comment by tomasg2012** [comment]
Interesting, can you post the debug log to this particular run in a zip file?  this seems unusual

**Comment by billdodd** [comment]
I took a peek at this and couldn't see anything obvious. There are very similar Redundancy resources in the public-composability mockup that get validated correctly. As Tomas said, the logs from the run will be helpful to figure what is going wrong.

**Comment by samerhaj** [comment]
Here is a snippet from the logs. Hope this is helpful:



INFO - Redundancy.Redundancy#0, ('/redfish/v1/Chassis/1/Power/Redundancy/PSU', True, 'Redundancy.Redundancy', '/redfish/v1/metadata/Redundancy_v1.xml', OrderedDict([('@odata.id', '/redfish/v1/Chassis/1/Power/Redundancy/PSU')]))
INFO - 
*** ServiceRoot -> Redundancy.Redundancy#0, /redfish/v1/Chassis/1/Power/Redundancy/PSU
DEBUG - 
*** Redundancy.Redundancy, True, True
DEBUG - payload: {
    "@odata.id": "/redfish/v1/Chassis/1/Power/Redundancy/PSU"
}
DEBUG - getting Schema of Redundancy.Redundancy /redfish/v1/metadata/Redundancy_v1.xml
DEBUG - callingResourceURI with authtype Basic and ssl True: /redfish/v1/metadata/Redundancy_v1.xml
DEBUG - 200, [200].....
TIME ELAPSED: 0.100781
DEBUG - Redundancy.v1_2_0   Redundancy
WARNING - No @odata.type present, assuming highest type Redundancy.v1_2_0.Redundancy
DEBUG - References generated from /redfish/v1/$metadata: 174 out of 174
INFO - Annotations generated: 0 out of 0
DEBUG - References generated from /redfish/v1/metadata/Redundancy_v1.xml: 4 out of 174
DEBUG - Generating type: Redundancy.v1_2_0.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_2_0
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_1_2.Redundancy'}
DEBUG - Redundancy.v1_1_2.Redundancy
DEBUG - Actions
DEBUG - Redundancy.v1_2_0.Actions
DEBUG - {'Name': 'Actions', 'Nullable': 'false', 'Type': 'Redundancy.v1_2_0.Actions'}
DEBUG - ADDING :::: Redundancy.v1_2_0.Redundancy:Actions
DEBUG - ___
DEBUG - Redundancy.v1_2_0, Redundancy.v1_2_0.Redundancy:Actions, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'The available actions for this resource.', 'Term': 'OData.Description'}, 'isNav': False, 'OData.LongDescription': {'String': 'The Actions property shall contain the available actions for this resource.', 'Term': 'OData.LongDescription'}, 'attrs': {'Name': 'Actions', 'Nullable': 'false', 'Type': 'Redundancy.v1_2_0.Actions'}}
DEBUG - HASTYPE
DEBUG - Redundancy.v1_2_0, Redundancy.v1_2_0.Actions
DEBUG - References generated from of parent: 4 out of 174
DEBUG - go deeper in type
DEBUG - Generating type: Redundancy.v1_2_0.Actions of tagType ComplexType
DEBUG - Schema is Actions, Redundancy.v1_2_0
DEBUG - ___
DEBUG - Actions
DEBUG - {'Name': 'Actions'}
DEBUG - None
DEBUG - Oem
DEBUG - Redundancy.v1_2_0.OemActions
DEBUG - {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Redundancy.v1_2_0.OemActions'}
DEBUG - ADDING :::: Redundancy.v1_2_0.Actions:Oem
DEBUG - ___
DEBUG - Redundancy.v1_2_0, Redundancy.v1_2_0.Actions:Oem, ComplexType
DEBUG - {'isTerm': False, 'isNav': False, 'attrs': {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Redundancy.v1_2_0.OemActions'}}
DEBUG - HASTYPE
DEBUG - Redundancy.v1_2_0, Redundancy.v1_2_0.OemActions
DEBUG - References generated from of parent: 4 out of 174
DEBUG - go deeper in type
DEBUG - Generating type: Redundancy.v1_2_0.OemActions of tagType ComplexType
DEBUG - Schema is OemActions, Redundancy.v1_2_0
DEBUG - ___
DEBUG - OemActions
DEBUG - {'Name': 'OemActions'}
DEBUG - None
DEBUG - Generating type: Redundancy.v1_1_2.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_1_2
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_1_1.Redundancy'}
DEBUG - Redundancy.v1_1_1.Redundancy
DEBUG - Generating type: Redundancy.v1_1_1.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_1_1
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_1_0.Redundancy'}
DEBUG - Redundancy.v1_1_0.Redundancy
DEBUG - Generating type: Redundancy.v1_1_0.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_1_0
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_0_2.Redundancy'}
DEBUG - Redundancy.v1_0_2.Redundancy
DEBUG - RedundancyEnabled
DEBUG - Edm.Boolean
DEBUG - {'Name': 'RedundancyEnabled', 'Type': 'Edm.Boolean'}
DEBUG - ADDING :::: Redundancy.v1_1_0.Redundancy:RedundancyEnabled
DEBUG - ___
DEBUG - Redundancy.v1_1_0, Redundancy.v1_1_0.Redundancy:RedundancyEnabled, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This indicates whether redundancy is enabled.', 'Term': 'OData.Description'}, 'attrs': {'Name': 'RedundancyEnabled', 'Type': 'Edm.Boolean'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/ReadWrite', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this property shall be a boolean indicating whether the redundancy is enabled.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Edm, Edm.Boolean
DEBUG - Generating type: Redundancy.v1_0_2.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_0_2
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_0_1.Redundancy'}
DEBUG - Redundancy.v1_0_1.Redundancy
DEBUG - Generating type: Redundancy.v1_0_1.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_0_1
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.v1_0_0.Redundancy'}
DEBUG - Redundancy.v1_0_0.Redundancy
DEBUG - Generating type: Redundancy.v1_0_0.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy.v1_0_0
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Redundancy.Redundancy'}
DEBUG - Redundancy.Redundancy
DEBUG - Name
DEBUG - Edm.String
DEBUG - {'Name': 'Name', 'Nullable': 'false', 'Type': 'Edm.String'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:Name
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:Name, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'The name of the resource or array element.', 'Term': 'OData.Description'}, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'attrs': {'Name': 'Name', 'Nullable': 'false', 'Type': 'Edm.String'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'This object represents the Name property.  All values for resources described by this schema shall comply to the requirements as described in the Redfish specification. The value of this string shall be of the format for the reserved word *Name*.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Edm, Edm.String
DEBUG - Mode
DEBUG - Redundancy.v1_0_0.RedundancyMode
DEBUG - {'Name': 'Mode', 'Type': 'Redundancy.v1_0_0.RedundancyMode'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:Mode
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:Mode, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This is the redundancy mode of the group.', 'Term': 'OData.Description'}, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'attrs': {'Name': 'Mode', 'Type': 'Redundancy.v1_0_0.RedundancyMode'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this property shall contain the information about the redundancy mode of this manager.  Failover shall indicate a master/slave type arrangement where status indicates the role of this manager.  N+1 indicates an arrangement where the redundancy set needs MaxNumSupported-1 number of resources in order to be redundant.  Load Balanced indicates all members are active. However, there functionality is not independent of each other. Their functioning is determined by some sort of load balancing algorithm. Sparing is implied (i.e. each member can be a spare for the other(s). Sparing indicates that all members are active and are aware of each others. However, their functionality is independent until failover. Each member can be a spare for the other(s). Limited Sparing indicates that all members are active, and they may or may not be aware of each and they are not spares for each other.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.RedundancyMode
DEBUG - References generated from of parent: 4 out of 174
DEBUG - ['Failover', 'N+m', 'Sharing', 'Sparing']
DEBUG - MaxNumSupported
DEBUG - Edm.Int64
DEBUG - {'Name': 'MaxNumSupported', 'Type': 'Edm.Int64'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:MaxNumSupported
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:MaxNumSupported, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This is the maximum number of members allowable for this particular redundancy group.', 'Term': 'OData.Description'}, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'attrs': {'Name': 'MaxNumSupported', 'Type': 'Edm.Int64'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this property shall contain the maximum number of members allowed in the redundancy group.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Edm, Edm.Int64
DEBUG - MinNumNeeded
DEBUG - Edm.Int64
DEBUG - {'Name': 'MinNumNeeded', 'Type': 'Edm.Int64'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:MinNumNeeded
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:MinNumNeeded, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This is the minumum number of members needed for this group to be redundant.', 'Term': 'OData.Description'}, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'attrs': {'Name': 'MinNumNeeded', 'Type': 'Edm.Int64'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this property shall contain the minimum number of members allowed in the redundancy group for the current redundancy mode to still be fault tolerant.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Edm, Edm.Int64
DEBUG - Status
DEBUG - Resource.Status
DEBUG - {'Name': 'Status', 'Nullable': 'false', 'Type': 'Resource.Status'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:Status
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:Status, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'isNav': False, 'attrs': {'Name': 'Status', 'Nullable': 'false', 'Type': 'Resource.Status'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.Status
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - go deeper in type
DEBUG - Generating type: Resource.Status of tagType ComplexType
DEBUG - Schema is Status, Resource
DEBUG - ___
DEBUG - Status
DEBUG - {'Name': 'Status'}
DEBUG - None
DEBUG - State
DEBUG - Resource.State
DEBUG - {'Name': 'State', 'Type': 'Resource.State'}
DEBUG - ADDING :::: Resource.Status:State
DEBUG - ___
DEBUG - Resource, Resource.Status:State, ComplexType
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This indicates the known state of the resource, such as if it is enabled.', 'Term': 'OData.Description'}, 'attrs': {'Name': 'State', 'Type': 'Resource.State'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'This property shall represent if this component is available or not and why.  Enabled indicates the resource is available.  Disabled indicates the resource has been intentionally made unavailable but it can be enabled.  Offline indicates the resource is unavailable intentionally and requires action to be made available.  InTest indicates that the component is undergoing testing.  Starting indicates that the resource is on its way to becoming available.  Absent indicates the resources is physically unavailable.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.State
DEBUG - References generated from of parent: 2 out of 174
DEBUG - HealthRollup
DEBUG - Resource.Health
DEBUG - {'Name': 'HealthRollup', 'Type': 'Resource.Health'}
DEBUG - ADDING :::: Resource.Status:HealthRollup
DEBUG - ___
DEBUG - Resource, Resource.Status:HealthRollup, ComplexType
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This represents the overall health state from the view of this resource.', 'Term': 'OData.Description'}, 'attrs': {'Name': 'HealthRollup', 'Type': 'Resource.Health'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'This property shall represent the HealthState of the resource and its dependent resources.  The values shall conform to those defined in the Redfish specification.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.Health
DEBUG - References generated from of parent: 2 out of 174
DEBUG - Health
DEBUG - Resource.Health
DEBUG - {'Name': 'Health', 'Type': 'Resource.Health'}
DEBUG - ADDING :::: Resource.Status:Health
DEBUG - ___
DEBUG - Resource, Resource.Status:Health, ComplexType
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This represents the health state of this resource in the absence of its dependent resources.', 'Term': 'OData.Description'}, 'attrs': {'Name': 'Health', 'Type': 'Resource.Health'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'This property shall represent the HealthState of the resource without considering its dependent resources. The values shall conform to those defined in the Redfish specification.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.Health
DEBUG - References generated from of parent: 2 out of 174
DEBUG - Oem
DEBUG - Resource.Oem
DEBUG - {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Resource.Oem'}
DEBUG - ADDING :::: Resource.Status:Oem
DEBUG - ___
DEBUG - Resource, Resource.Status:Oem, ComplexType
DEBUG - {'isTerm': False, 'isNav': False, 'attrs': {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Resource.Oem'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.Oem
DEBUG - References generated from of parent: 2 out of 174
DEBUG - go deeper in type
DEBUG - Generating type: Resource.Oem of tagType ComplexType
DEBUG - Schema is Oem, Resource
DEBUG - ___
DEBUG - Oem
DEBUG - {'Name': 'Oem'}
DEBUG - None
DEBUG - RedundancySet
DEBUG - Collection(Resource.Item)
DEBUG - {'Name': 'RedundancySet', 'Type': 'Collection(Resource.Item)'}
DEBUG - ADDING :::: Redundancy.v1_0_0.Redundancy:RedundancySet
DEBUG - ___
DEBUG - Redundancy.v1_0_0, Redundancy.v1_0_0.Redundancy:RedundancySet, EntityType
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'Contains any ids that represent components of this redundancy set.', 'Term': 'OData.Description'}, 'Redfish.Required': {'Term': 'Redfish.Required'}, 'attrs': {'Name': 'RedundancySet', 'Type': 'Collection(Resource.Item)'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': True, 'OData.LongDescription': {'String': 'The value of this property shall contain the ids of components that are part of this redundancy set. The id values may or may not be dereferenceable.', 'Term': 'OData.LongDescription'}, 'OData.AutoExpandReferences': {'Term': 'OData.AutoExpandReferences'}}
DEBUG - HASTYPE
DEBUG - Collection(Resource, Collection(Resource.Item)
DEBUG - HASTYPE
DEBUG - Resource, Resource.Item
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - typeEntityTag found RedundancySet
DEBUG - Generating type: Redundancy.Redundancy of tagType EntityType
DEBUG - Schema is Redundancy, Redundancy
DEBUG - ___
DEBUG - Redundancy
DEBUG - {'Name': 'Redundancy', 'BaseType': 'Resource.v1_0_0.ReferenceableMember'}
DEBUG - Resource.v1_0_0.ReferenceableMember
DEBUG - References generated from /redfish/v1/metadata/Resource_v1.xml: 2 out of 174
DEBUG - Generating type: Resource.v1_0_0.ReferenceableMember of tagType EntityType
DEBUG - Schema is ReferenceableMember, Resource.v1_0_0
DEBUG - ___
DEBUG - ReferenceableMember
DEBUG - {'Name': 'ReferenceableMember', 'BaseType': 'Resource.ReferenceableMember', 'Abstract': 'true'}
DEBUG - Resource.ReferenceableMember
DEBUG - MemberId
DEBUG - Edm.String
DEBUG - {'Name': 'MemberId', 'Nullable': 'false', 'Type': 'Edm.String'}
DEBUG - ADDING :::: Resource.v1_0_0.ReferenceableMember:MemberId
DEBUG - ___
DEBUG - Resource.v1_0_0, Resource.v1_0_0.ReferenceableMember:MemberId, EntityType
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This is the identifier for the member within the collection.', 'Term': 'OData.Description'}, 'attrs': {'Name': 'MemberId', 'Nullable': 'false', 'Type': 'Edm.String'}, 'OData.Permissions': {'EnumMember': 'OData.Permission/Read', 'Term': 'OData.Permissions'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this string shall uniquely identify the member within the collection.', 'Term': 'OData.LongDescription'}}
DEBUG - HASTYPE
DEBUG - Edm, Edm.String
DEBUG - Generating type: Resource.ReferenceableMember of tagType EntityType
DEBUG - Schema is ReferenceableMember, Resource
DEBUG - ___
DEBUG - ReferenceableMember
DEBUG - {'Name': 'ReferenceableMember', 'BaseType': 'Resource.Item', 'Abstract': 'true'}
DEBUG - Resource.Item
DEBUG - Generating type: Resource.Item of tagType EntityType
DEBUG - Schema is Item, Resource
DEBUG - ___
DEBUG - Item
DEBUG - {'Name': 'Item', 'Abstract': 'true'}
DEBUG - None
DEBUG - Oem
DEBUG - Resource.Oem
DEBUG - {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Resource.Oem'}
DEBUG - ADDING :::: Resource.Item:Oem
DEBUG - ___
DEBUG - Resource, Resource.Item:Oem, EntityType
DEBUG - {'isTerm': False, 'OData.Description': {'String': 'This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.', 'Term': 'OData.Description'}, 'isNav': False, 'OData.LongDescription': {'String': 'The value of this string shall be of the format for the reserved word *Oem*.', 'Term': 'OData.LongDescription'}, 'attrs': {'Name': 'Oem', 'Nullable': 'false', 'Type': 'Resource.Oem'}}
DEBUG - HASTYPE
DEBUG - Resource, Resource.Oem
DEBUG - References generated from of parent: 2 out of 174
DEBUG - go deeper in type
DEBUG - Generating type: Resource.Oem of tagType ComplexType
DEBUG - Schema is Oem, Resource
DEBUG - ___
DEBUG - Oem
DEBUG - {'Name': 'Oem'}
DEBUG - None
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
DEBUG - OrderedDict()
INFO - Redundancy.v1_2_0.Redundancy:Actions
INFO - 	value: n/a <class 'str'>
INFO - 	has Type: Redundancy.v1_2_0.Actions complex
INFO - 	is Optional
INFO - 	prop Does not exist, skip...
INFO - Redundancy.v1_1_0.Redundancy:RedundancyEnabled
INFO - 	value: n/a <class 'str'>
INFO - 	has Type: Edm.Boolean Edm.Boolean
INFO - 	is Optional
INFO - 	prop Does not exist, skip...
INFO - Redundancy.v1_0_0.Redundancy:Name
INFO - 	value: n/a <class 'str'>
INFO - 	has Type: Edm.String Edm.String
INFO - 	Mandatory Test: FAIL
**ERROR - Redundancy.v1_0_0.Redundancy:Name: Mandatory prop does not exist**

**Comment by tomasg2012** [comment]
Unusual...
```
DEBUG - payload: {
"@odata.id": "/redfish/v1/Chassis/1/Power/Redundancy/PSU"
}
```
This part of the log suggests that the payload is missing.  This particular reason why is because of how it is listed in the Power_v1.xml schema:

```
<NavigationProperty Name="Redundancy" Type="Collection(Redundancy.Redundancy)">
<Annotation Term="OData.Description" String="Redundancy information for the power subsystem of this system or device."/>
<Annotation Term="OData.AutoExpand"/>
</NavigationProperty>
```

The issue here is the Redundancy payload is supposed to be embedded into the Power payload.

Note the OData.AutoExpand, which implies that the payload itself must (or may, I'm not sure) be contained in the payload that links to it (Power).  The program is correctly handling the data its given but the data is incomplete.  If I'm recalling correctly, a `BaseType="Resource.v1_0_0.ReferenceableMember"` that Redundancy is defined by does not allow the @odata.id to resolve to a resource, or at least technically is incorrect implementation.

**Comment by samerhaj** [comment]
Closing as this appears to be an implementation issue
