### ISSUE TITLE
Updating bautifulsoup to 4.6.0 causes report fails.

### ISSUE THREAD

**Issue by boras1988** [DMTF/Redfish-Service-Validator#124]
As long as I was using beautifulsoup ver. 4.4.1 everything worked fine. Switching to ver. 4.6.0 caused reports to fail when running on the same redfish app which ver. 4.4.1 reported as 100% correct.

**Comment by tomasg2012** [comment]
Are you using the tool as it is currently available on the repo?  Could you provide log reports?

**Comment by boras1988** [comment]
Sorry, accidently was using an older RedfishServiceValidator version, got confused because it also had 0.91 in the config.ini. On the latest version everything works fine with beautiful soup 4.6.0.

**Comment by billdodd** [comment]
Closing since this is not a problem in the latest version of the tool.
