### ISSUE TITLE
BIOS validation failing on @Redfish.Settings annotation

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#128]
I have a failure on Bios resource containing @Redfish.Settings annotation:

The Error is:

ERROR - Something went wrong
Traceback (most recent call last):
  File "C:\DevTools\redfish\Redfish-Service-Validator\traverseService.py", line 595, in __init__
    soup, refs, propOwner, propChild, tagType, topVersion)
  File "C:\DevTools\redfish\Redfish-Service-Validator\traverseService.py", line 752, in getPropertyDetails
    propTag = propEntity.find(['NavigationProperty', 'Property'], attrs={'Name': propChild}, recursive=False)  # BS4 line
AttributeError: 'NoneType' object has no attribute 'find'
ERROR - Settings.v1_0_4.Settings:@Redfish.Settings :  Could not get details on this property
ERROR - 	Item is present, no schema found

The resource is:

{
    "Id": "Bios",
    "@Redfish.Settings": {
        "@odata.type": "#Settings.v1_0_4.Settings",
        "Time": "2017-12-06T17:10:50+00:00",
        "SettingsObject": {
            "@odata.id": "/redfish/v1/Systems/1/Bios/Pending"
        },
        "Messages": []
    },
    "Name": "Bios",
    "AttributeRegistry": "BiosAttributeRegistryV1",
    "@odata.type": "#Bios.v1_0_2.Bios",
    "@odata.context": "/redfish/v1/$metadata#Bios.Bios",
    "@odata.id": "/redfish/v1/Systems/1/Bios/",
    "Attributes": { },
    "Actions": {
        "#Bios.ResetBios": {
            "target": "/redfish/v1/Systems/1/Bios/Actions/Bios.ResetBios",
            "title": "ResetBios"
        },
        "#Bios.ChangePassword": {
            "title": "ChangePassword",
            "target": "/redfish/v1/Systems/1/Bios/Actions/Bios.ChangePassword"
        }
    },
    "Description": "System Bios"
}

**Comment by samerhaj** [comment]
Is the validator  having a hard time traversing from Settings.v1_0_0 to  Settings.v1_0_4? When we change "@odata.type" of "@Redfish.Settings" from "#Settings.v1_0_4.Settings" to "#Settings.v1_0_0.Settings", this error disappears and the test passes.

**Comment by tomasg2012** [comment]
Is Settings.v1_0_4 namespace present in the schema associated with the service?  It's an unusual error, would like to see a full debug log associated with this.  From a first glance it seems it is unable to find that tag in the file, but if it's able to work with Settings.v1_0_0, then it should be fine.

**Comment by mraineri** [comment]
Samer, Settings is a ComplexType (no entities defined in that file), so we don't extend it into the trivial namespaces; the `@odata.type` property should be #Settings.v1_0_0.Settings.

**Comment by mraineri** [comment]
Need to bring an issue back to the main forum where we do not extend complex type definitions into trivial namespaces for further discussion. This is done in schemas containing only complex types (like Settings).

**Comment by samerhaj** [comment]
Thanks Mike. I am opening this in the SPMF forum. We can close this tool issue for now until that is resolved

**Comment by billdodd** [comment]
Per the discussion above - this is a schema issue rather than a tool issue, so closing for now.
