### ISSUE TITLE
DynamicPropertyPatterns that are Primitive should allow null values

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#130]
The tool is not allowing DynamicPropertyPatterns of Primitive types to be null-able. This should be allowed

**Comment by billdodd** [comment]
I think I see the problem. But want to be sure I'm looking at the same scenario. Is the error reported like this (obviously with a different key name and possibly a different type):

```
ERROR - #Bios.v1_0_0.Bios:Attributes key "SataPortDModel" with value "None" is not of type "Edm.Primitive"
```
