### ISSUE TITLE
Improvements to conformance report

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Service-Validator#137]
At the 1/18/2018 Tools TF call, @jautor shared a conformance report that showed many errors due to some fundamental problem(s) that prevented most of the resources from even being loaded.

This issue is to track the suggested improvements.

See my next comment below for the enhancements suggested by Jeff A. and Mike R.

**Comment by billdodd** [comment]
Here are the specific enhancements suggested by Jeff A. and Mike R.:

General:

1. Remove OData and CSDL terminology except when used for annotations or schema errors
    a. Use Redfish or JSON terminology whenever possible (most users won’t be aware of OData)
2. If property / enum / etc. not found in schema, do a case-insensitive check to report case errors

Header improvements:

1. Large title / simplified
2. Add Github Release version for tool issue reporting
3. Add link to Github repo
4. Clarify test config parameters, collapse into section, only show those items that affect the output
5. Collapse other boxed text into fewer sections for clarity
6. Final counts should become a “Test Summary” section
    a. All of this header info and summary should hopefully fit on one page, can be used to publish results
7. Resource report should have URI as a clear header line,
    a. Large font, can we put expand/collapse here?
    b. Include schema type and response time all in one line/section for clarity
    c. Resource type just schema/version, show path for “Schema file”

Resource report improvements:

1. Value: Report embedded object as value “JSON Object”, don’t include object’s properties (unknown object error will be shown in the error payload)
2. Value: Links (objects with @odata.id single property) – report as “Link: <value of odata.id>”
3. Type: report all as JSON types, not CSDL, including @odata annotations (report as string)
4. Type: add (enum) to string values with enumeration definitions
5. Type: Objects/links show the resource type (of link target) “link to: <resource type>”
6. Type: $ref simple types should report their JSON type (e.g. “Resource.Id” reports “string”.  $ref objects report the object type (e.g. “Resource.Status”)
7. Exists: Change to Yes/No.  Properties not in schema (additional) report “—"
8. Success: Simplify text for clarity

Error case enhancements:

1. If schema file not located via $metadata, construct standard Redfish schema filename from @odata.type and attempt to load.  Report error but attempt to continue:
    a. Current:  ERROR - Got XML, but expected schema doesn't exist...? ServiceRoot.v1_1_0, ServiceRoot ... we will be unable to generate properties
    b. Suggest: ERROR – Expected schema from $metadata “ServiceRoot.xml” not found in repository.  Attempting default “ServiceRoot_v1.xml”
2. Same error – Need to differentiate between missing $metadata entry, “file not found” (report HTTP status codes), and missing namespaces
    a. Is this a test config error, $metadata error, @odata.type error, or other?
3. “failAdditional” – decode these entries into their common faults
    a. Invalid Property – property not defined in schema
    b. Invalid Type – property ok, wrong type
    c. Misc Failure (see below)
4. General – always report “expected value” and “received value” when these are known.
5. General – any HTTP error, report “HTTP Status Code: <nnn>” and include any payload as an expandable “show details”
6. General – Any resource which fails due to payload error, include payload as expandable “show payload”

**Comment by billdodd** [comment]
I reviewed and updated the checklist above. It looks like there may need to be some header section improvements and an enhancement to include failing JSON payload in an expandable section. Let's discuss these at the next task force call.

### Header improvements:

- [ ] Clarify test config parameters, collapse into section, only show those items that affect the output
- [ ] Final counts should become a “Test Summary” section
    - [ ] All of this header info and summary should hopefully fit on one page, can be used to publish 

### Error case enhancements:

- [ ] General – any HTTP error, report “HTTP Status Code: <nnn>” and include any payload as an expandable “show details”
- [ ] General – Any resource which fails due to payload error, include payload as expandable “show payload”

**Comment by mraineri** [comment]
Since these are finished (mostly), I think we can take any additional improvements as new issues in the future.
