### ISSUE TITLE
Referenceable array member checks should continue without odata.id

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#143]
Embedded objects / arrays which are marked as referenceable members must contain an @odata.id to conform to the spec. This is properly flagged as an error in the tool.

However, the schema type of these arrays/objects can be assumed (and perhaps always correct?) from the parent, and so checking the properties within the array member should continue, not abort (as the tool does now).

**Comment by billdodd** [comment]
@jautor - the issue text doesn't seem to match the title. Is this mixing 2 issues?

**Comment by jautor** [comment]
Yep, I've entered two in the wrong place...  Fixing both...

**Comment by tomasg2012** [comment]
Closed with PR #170, just still around.
