### ISSUE TITLE
False error on property values with multiple valid types (string, boolean)

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#147]
Finding this specifically in the AttributeRegistry where the "MapToValue" and "MapFromValue" properties in "Dependencies" are set to boolean true/false.  Other values as strings are passing correctly.  This is valid in schema - type can be string, number, boolean.

I assume this is probably a generic issue that will apply to any property with multiple types allowed (those are rare in Redfish).  

Example:
~~~
            {
                "DependencyFor": "Lunch",
                "Type": "Map",
                "Dependency": {
                    "MapFrom": [
                        {
                            "MapFromAttribute": "FavoriteLunchSpot",
                            "MapFromProperty": "CurrentValue",
                            "MapFromCondition": "EQU",
                            "MapFromValue": "TacoBell"
                        }
                    ],
                    "MapToAttribute": "BurritosOnMenu",
                    "MapToProperty": "ReadOnly",
                    "MapToValue": true
                }
            },
~~~

In this example the dependency shown is on the schema "read-only" attribute (boolean).  But "MapToValue" could also be a number...

**Comment by billdodd** [comment]
The checkPropertyConformance() function was missing a validation for primitive types. This is fixed in PR #144.
