### ISSUE TITLE
Exception on Link generation if exception occurs in Property generation

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#148]
I've stripped down an EthernetInterface resource, and the crash still occurs.  Schema version doesn't appear to matter, either.  Note that VLAN doesn't even appear in this payload, this is something specific with the name/schema...

Error:
~~~
ERROR - Something went wrong
Traceback (most recent call last):
  File "C:\Users\JAUTOR\Documents\GitHub\Redfish-Service-Validator\traverseService.py", line 639, in __init__
    soup, refs, propOwner, propChild, tagType, topVersion)
  File "C:\Users\JAUTOR\Documents\GitHub\Redfish-Service-Validator\traverseService.py", line 852, in getPropertyDetails
    typeTag = typeSchema.find(  # BS4 line
AttributeError: 'NoneType' object has no attribute 'find'
ERROR - EthernetInterface.v1_0_0.EthernetInterface:VLAN :  Could not get details on this property
ERROR - Something went wrong
Traceback (most recent call last):
  File "C:\Users\JAUTOR\Documents\GitHub\Redfish-Service-Validator\traverseService.py", line 999, in getAllLinks
    if propDict['isNav']:
TypeError: 'NoneType' object is not subscriptable
~~~

Payload:
~~~
{
    "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
    "@odata.id": "/redfish/v1/Systems/1/EthernetInterfaces/1/",
    "@odata.type": "#EthernetInterface.v1_4_0.EthernetInterface",
    "Id": "1",
    "FullDuplex": true,
    "LinkStatus": "LinkUp",
    "MACAddress": "94:18:82:18:09:a8",
    "Name": "Eth0",
    "SpeedMbps": null,
    "Status": {
        "Health": null,
        "State": null
    }
}
~~~

**Comment by billdodd** [comment]
Jeff, the $metadata file and the text log file (ConformanceLog_*.txt) would be very helpful in understanding what went wrong.

**Comment by tomasg2012** [comment]
It might be enlightening if the XML for that particular item was found, VLANNetworkingInterface_v1.xml.  The program does generate information for items that don't exist, usually to check if it's valid to omit them in the first place.  However, it shouldn't ever except, and the second exception is a result of the first.

The item in particular, of type VLANNetworkingInterface.VLAN, is an abstract complex item, that only exists if VLANs doesn't... but that doesn't seem relevant to the issue.

**Comment by jautor** [comment]
All of the schema XML files are straight from the 2017.3 release.  I'll forward the $metadata and logfile...

**Comment by billdodd** [comment]
It looks like this entry in the $metadata file is tripping things up:

```
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SoftwareInventoryCollection_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
    </edmx:Reference>
```

Here's a snippet of the debug log leading up to the error:


> DEBUG - VLAN
> DEBUG - VLanNetworkInterface.VLAN
> DEBUG - {'Name': 'VLAN', 'Type': 'VLanNetworkInterface.VLAN'}
> DEBUG - ADDING :::: EthernetInterface.v1_0_0.EthernetInterface:VLAN
> DEBUG - ___
> DEBUG - EthernetInterface.v1_0_0, EthernetInterface.v1_0_0.EthernetInterface:VLAN, EntityType
> DEBUG - References generated from http://redfish.dmtf.org/schemas/v1/Resource_v1.xml: 3 out of 111
> DEBUG - {'isTerm': False, ...}
> DEBUG - HASTYPE
> DEBUG - VLanNetworkInterface, VLanNetworkInterface.VLAN
> DEBUG - **getting Schema of VLanNetworkInterface http://redfish.dmtf.org/schemas/v1/SoftwareInventoryCollection_v1.xml**
> DEBUG - Should be XML
> DEBUG - callingResourceURI out of service with authtype Session and ssl True: http://redfish.dmtf.org/schemas/v1/SoftwareInventoryCollection_v1.xml {'OData-Version': '4.0'}
> DEBUG - 200, [200], {'Date': 'Wed, 31 Jan 2018 23:35:39 GMT', ...},
> TIME ELAPSED: 0.062006
> DEBUG - References generated from http://redfish.dmtf.org/schemas/v1/SoftwareInventoryCollection_v1.xml: 3 out of 111
> ERROR - Something went wrong
> Traceback (most recent call last):
>   ...
> ERROR - EthernetInterface.v1_0_0.EthernetInterface:VLAN :  Could not get details on this property


Note that while processing VLanNetworkInterface it fetches and uses the SoftwareInventoryCollection_v1.xml schema.

**Comment by jautor** [comment]
Yeah, this is a cut and paste error as I was updating the $metadata.  There were actually two $metadata errors - the one you found, and also "VlanNetworkInterfaceCollection" specified the namespace "VlanNetworkInterface" (not Collection), which may be a better clue as to why the tool was even looking there.  

At least this found an unhandled exception!  But that is the only problem - correcting the $metadata removed the exception condition.
