### ISSUE TITLE
Why does tool fetch URI with embedded #

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#15]
I see the tool fetch URI with embedded #
DEBUG - callingResourceURI: /redfish/v1/Chassis/H88493-003-1638MSL/Thermal%23/Temperatures/0

Seems not required because this fetch will return /redfish/v1/Chassis/H88493-003-1638MSL/Thermal page which is already in memory?

**Comment by tomasg2012** [comment]
The tool by default escapes # as %23, and I've had mixed messages about this.

It is true, _normally_ a pound sign signifies a fragment, it is not sent over http.  However, for Odata and Redfish, `/redfish/v1/$metadata#ServiceRoot.ServiceRoot` is technically a unique URI, that returns that specific Schema document, via @odata.context.

Now in the case of Thermal, some Collections have @odata.id entries and ContainsTarget=True, which has the whole Entity in the payload itself.  I've gathering info from others to determine whether or not the pound sign in these collections is also expected to give a response like above; however, it seems that we've come to the conclusion that whether or not this info is available, it might as well be handled in memory.

**Comment by jbobzin-insyde** [comment]
Spec seems pretty clear - last paragraph of 6.1.1 (just before 6.1.2)
The # and following text are a frag and ignored by the server.

So in a https get of  /redfish/v1/$metadata#ServiceRoot.ServiceRoot  service would return entire $metadata contents. Following the ServiceRoot.ServiceRoot would be responsibility of the client, searching inside of the returned (entire) metatdata

**Comment by tomasg2012** [comment]
There is a fix for elements in AutoExpand annotated NavigationProperties, which includes Temperatures.  And currently, the $metadata grabbing is designed around that principle as well.

**Comment by jbobzin-insyde** [comment]
Thanks for the fix.  Will try.  Should help performance.  I think this is analogous - If I use IE or Chrome to fetch an Internet page with #frag clause in URI, I get the whole page back from the server. Then the browser searches the buffer for the tag extracted from frag and positions the window according to its own rules. So the frag is something that is ignored by the server and only makes sense to the client.

**Comment by tomasg2012** [comment]
Sorry, that was my understanding initially, but based on several sources I got a conflicted understanding, based on the original tool and service implementations.

**Comment by jbobzin-insyde** [comment]
Is there enough confusion we need to add a issue for the Interop task force meeting?

**Comment by tomasg2012** [comment]
You might want to mention it to Mike Rainier, I talked to him about it.

**Comment by pwvancil** [comment]
issue entered re redfish frags
for now, tool should not read URIs that are the same when ignoring the frag

**Comment by jbobzin-insyde** [comment]
fixed
