### ISSUE TITLE
Improve property naming in error messages, especially for array elements

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#150]
Property-level errors should start with the property name, remove any remaining "Property named" (or similar) lead ins (will add comment later showing specific known cases).

Some error messages do not include the array index with the property name.  Known examples include:
- "String 'XXXX' does not match pattern"
- "This type is an invalid Edm.PrimativeType"

Those that do can use a more readable form for array elements:
BEFORE: IPv4Addresses.Address#0
AFTER: IPv4Addresses[0].Address

**Comment by billdodd** [comment]
@jautor - In PR #167 I have fixes to display array member property names using standard array indexing notation - both in the "Property Name" column of the report tables and in the error messages. See the screenshots I added to that PR for examples.

If you have any additional specific error message examples that show other formatting errors, please add them here.

**Comment by billdodd** [comment]
I believe PR #167 fixes the property naming issues described. If not, please reopen this issue.
