### ISSUE TITLE
OrderedDict output format on Registry / Messages or embedded objects

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#153]
The "OrderedDict" language describing properties still exists in some cases.  This appears in Registries (especially Message), but may also be on embedded objects in general.  Will attach examples if needed.

Replacing that text with the JSON types will improve readability for those resources.

**Comment by billdodd** [comment]
@jautor - I had a fix for this in the Pull Request that got merged today. Can you check again with the current code to see if you still see this? I don't see it anymore in my tests.

**Comment by jautor** [comment]
Great - I'll check this tomorrow and will close appropriately...

**Comment by jautor** [comment]
Close fixed.
