### ISSUE TITLE
Unhandled exceptions do not show up on resources without other errors

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#154]
If the Validator throws an unhandled exception, the red box text shows up accordingly in the expanded resource report, but until the report is expanded, there is no visual indication of a fault (HTML).

Not sure if there's a way to catch all unhandled exceptions to recognize this condition, but perhaps a non-zero-length error report with no error counts reported would be a good indication?

**Comment by billdodd** [comment]
I made a tactical fix for this that does what you mention above (detect a non-zero-length error log with no error counts) in PR #164.

Longer term it would be better to reorganize the code so that errors found in traverseService.py can update the error counters directly.
