### ISSUE TITLE
failSchema Errors?

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#168]
We are getting a LOT of failSchema errors. I've never seen this before
the latest release of Service Validator. Can some explain what this is?
Thanks.

1 failSchema errors in /redfish/v1/Registries
1 failSchema errors in /redfish/v1/Registries/Base.1.2.0
1 problemResource errors in None
1 failSchema errors in /redfish/v1/Systems
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/Memory
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/Memory/3
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/Processors
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/Processors/CPU.Socket.2
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/EthernetInterfaces
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/EthernetInterfaces/NIC.Embedded.1-1-2
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/SimpleStorage
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/SimpleStorage/Perc
1 failSchema errors in /redfish/v1/Chassis
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1-Sled2/Thermal
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1-Sled2/Thermal#/Temperatures/0
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1-Sled2/Power
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1-Sled2/Power#/PowerControl/0
1 failProp errors in /redfish/v1/Chassis/Rack1-PowerBay1
1 failSchema errors in /redfish/v1/Chassis/Rack1-PowerBay1/Power#/Voltages/0
1 failSchema errors in /redfish/v1/Chassis/Rack1-PowerBay1/Power#/PowerSupplies/0
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/4
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/3
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/7
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/2
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/10
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/5
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/8
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/9
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/6
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/11
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/1
1 failSchema errors in /redfish/v1/Chassis/Rack1-Block1/Thermal#/Fans/0
1 failSchema errors in /redfish/v1/Managers
1 failSchema errors in /redfish/v1/Managers/RackManager
1 failSchema errors in /redfish/v1/Managers/RackManager/NetworkProtocol
1 failSchema errors in /redfish/v1/SessionService
1 failSchema errors in /redfish/v1/SessionService/Sessions
1 failSchema errors in /redfish/v1/AccountService/Accounts
1 failSchema errors in /redfish/v1/AccountService/Accounts/redfish_adm
1 failSchema errors in /redfish/v1/AccountService/Roles
1 failAdditional errors in /redfish/v1/AccountService/Roles/ReadOnlyUser
1 failAdditional errors in /redfish/v1/AccountService/Roles/Operator
1 failAdditional errors in /redfish/v1/AccountService/Roles/Administrator
1 failSchema errors in /redfish/v1/JsonSchemas
1 failSchema errors in /redfish/v1/JsonSchemas/AccountService.v1_0_0

**Comment by billdodd** [comment]
Yes, this change was made to address the case where errors occur that are not associated with a particular property. These errors are generally $metadata errors. But since they are not bound to a particular property, there were no red FAIL cells in the resource table and no red fail count in the resource header of the report. So you could end up with errors in a resource but would not see any indication in the report unless you expanded that resource and scrolled to the error log.

So, for the resources where you see this, there should be an error (or errors) logged at the bottom of that resource section in the report.

**Comment by PhillipWatts1012** [comment]
Could you give an example of where in the report we would see the error logged?  We do not understand what is causing these errors.

**Comment by billdodd** [comment]
Sure. Here is a screenshot showing an example. See the "failSchema" tag in red at the upper right and then the "ERROR" message in red logged at the bottom.

![screen shot 2018-02-21 at 12 27 12 pm](https://user-images.githubusercontent.com/3341721/36498040-c45c8204-1702-11e8-8ac5-dda6a5ff5704.png)

**Comment by PhillipWatts1012** [comment]
around line 355  in traverse.py
        filehandle = open(SchemaLocation + '/' + xml, "r")
where it tries to open **/home/dmtftest/schemas/$metadata**
there is no such file in dmtftest/schemas
this causes the failSchemas error. (I think)
Then the routine recurses with the correct schema.xml and succeeds.

Paul and I do not understand what the test is attempting.
Are there instances where it expects $metadata in schemas?
Some manufactures like their $metadata on harddrive?
Is there an option to prevent those errors?
Regression testing doesn't like seeing messages that look like failures.
Thanks.

**Comment by PhillipWatts1012** [comment]
log attached

________________________________

**Comment by tomasg2012** [comment]
Please use Github's issue comment system to attach the log file as an upload instead of as text, it's pretty large.

**Comment by tomasg2012** [comment]
Additionally, please post the $metadata that exists on the service.  The program is capable of looking for a $metadata stored on the harddrive but that's a rare fallback in case the service has none.

**Comment by PhillipWatts1012** [comment]
it doesnt support upload of xml.  Here it is:

<?xml version="1.0" encoding="UTF-8"?> 
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">

    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ServiceRoot_v1.xml">
      <edmx:Include Namespace="ServiceRoot" />
      <edmx:Include Namespace="ServiceRoot.v1_0_2"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/AccountService_v1.xml">
      <edmx:Include Namespace="AccountService" />
      <edmx:Include Namespace="AccountService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Chassis_v1.xml">
      <edmx:Include Namespace="Chassis" />
      <edmx:Include Namespace="Chassis.v1_4_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/ChassisCollection_v1.xml">
        <edmx:include Namespace="ChassisCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ComputerSystem_v1.xml">
        <edmx:Include Namespace="ComputerSystem" />
        <edmx:Include Namespace="ComputerSystem.v1_3_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/ComputerSystemCollection_v1.xml">
        <edmx:include Namespace="ComputerSystemCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterface_v1.xml">
        <edmx:include Namespace="EthernetInterface" />
        <edmx:Include Namespace="EthernetInterface.v1_3_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/EthernetInterfaceCollection_v1.xml">
        <edmx:include Namespace="EthernetInterfaceCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface_v1.xml">
        <edmx:include Namespace="VLanNetworkInterface" />
        <edmx:Include Namespace="VLanNetworkInterface.v1_0_0"/>
    </edmx:Reference>  
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Event_v1.xml">
        <edmx:include Namespace="Event" />
        <edmx:Include Namespace="Event.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventService_v1.xml">
        <edmx:include Namespace="EventService" />
        <edmx:Include Namespace="EventService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/IPAddresses_v1.xml">
        <edmx:include Namespace="IPAddresses" />
        <edmx:Include Namespace="IPAddresses.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/JsonSchemaFile_v1.xml">
        <edmx:include Namespace="JsonSchemaFile" />
        <edmx:Include Namespace="JsonSchemaFile.v1_0_2"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/JsonSchemaFileCollection_v1.xml">
        <edmx:include Namespace="JsonSchemaFileCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventDestination_v1.xml">
        <edmx:include Namespace="EventDestination" />
        <edmx:Include Namespace="EventDestination.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/EventDestinationCollection_v1.xml">
        <edmx:include Namespace="EventDestinationCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogEntry_v1.xml">
        <edmx:include Namespace="LogEntry" />
        <edmx:Include Namespace="LogEntry.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/LogEntryCollection_v1.xml">
        <edmx:include Namespace="LogEntryCollection" />
    </edmx:reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/Role_v1.xml">
        <edmx:include Namespace="Role" />
        <edmx:include Namespace="Role.v1_0_0" />
    </edmx:reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/RoleCollection_v1.xml">
        <edmx:include Namespace="RoleCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogService_v1.xml">
        <edmx:include Namespace="LogService" />
        <edmx:Include Namespace="LogService.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/LogServiceCollection_v1.xml">
        <edmx:include Namespace="LogServiceCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Manager_v1.xml">
        <edmx:include Namespace="Manager"/>
        <edmx:Include Namespace="Manager.v1_1_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/ManagerCollection_v1.xml">
        <edmx:include Namespace="ManagerCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerAccount_v1.xml">
        <edmx:include Namespace="ManagerAccount" />
        <edmx:Include Namespace="ManagerAccount.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/ManagerAccountCollection_v1.xml">
        <edmx:include Namespace="ManagerAccountCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerNetworkProtocol_v1.xml">
        <edmx:include Namespace="ManagerNetworkProtocol" />
        <edmx:Include Namespace="ManagerNetworkProtocol.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Message_v1.xml">
        <edmx:include Namespace="Message" />
        <edmx:Include Namespace="Message.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Power_v1.xml">
        <edmx:include Namespace="Power" />
        <edmx:Include Namespace="Power.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Redundancy_v1.xml">
        <edmx:include Namespace="Redundancy" />
        <edmx:Include Namespace="Redundancy.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Processor_v1.xml">
        <edmx:include Namespace="Processor" />
        <edmx:Include Namespace="Processor.v1_1_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/ProcessorCollection_v1.xml">
        <edmx:include Namespace="ProcessorCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Memory_v1.xml">
        <edmx:include Namespace="Memory" />
        <edmx:Include Namespace="Memory.v1_3_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/MemoryCollection_v1.xml">
        <edmx:include Namespace="MemoryCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SerialInterface_v1.xml">
        <edmx:include Namespace="SerialInterface" />
        <edmx:Include Namespace="SerialInterface.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/SerialInterfaceCollection_v1.xml">
        <edmx:include Namespace="SerialInterfaceCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Session_v1.xml">
        <edmx:include Namespace="Session" />
        <edmx:Include Namespace="Session.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/SessionCollection_v1.xml">
        <edmx:include Namespace="SessionCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionService_v1.xml">
        <edmx:include Namespace="SessionService" />
        <edmx:Include Namespace="SessionService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SimpleStorage_v1.xml">
        <edmx:include Namespace="SimpleStorage" />
        <edmx:Include Namespace="SimpleStorage.v1_2_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/SimpleStorageCollection_v1.xml">
        <edmx:include Namespace="SimpleStorageCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Task_v1.xml">
        <edmx:include Namespace="Task" />
        <edmx:Include Namespace="Task.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/TaskCollection_v1.xml">
        <edmx:include Namespace="TaskCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/TaskService_v1.xml">
        <edmx:include Namespace="TaskService" />
        <edmx:Include Namespace="TaskService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Thermal_v1.xml">
        <edmx:include Namespace="Thermal" />
        <edmx:Include Namespace="Thermalv1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VirtualMedia_v1.xml">
        <edmx:include Namespace="VirtualMedia" />
        <edmx:Include Namespace="VirtualMedia.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/VirtualMediaCollection_v1.xml">
        <edmx:include Namespace="VirtualMediaCollection" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface_v1.xml">
        <edmx:include Namespace="VLanNetworkInterface" />
        <edmx:Include Namespace="VLanNetworkInterface.v1_0_0"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterfaceCollection_v1.xml">
        <edmx:include Namespace="VLanNetworkInterface" />
    </edmx:reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
        <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
    </edmx:Reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFileCollection_v1.xml">
        <edmx:include Namespace="MessageRegistryFileCollection" />
    </edmx:reference>
    <edmx:reference uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml">
        <edmx:include Namespace="MessageRegistryFile" />
        <edmx:include Namespace="MessageRegistryFile.v1_0_0" />
    </edmx:reference>

    <edmx:DataServices>
 
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Service">
          <EntityContainer Name="Service" Extends="ServiceRoot.v1_0_2.ServiceContainer"/>
      </Schema>

  </edmx:DataServices>
</edmx:Edmx>

**Comment by tomasg2012** [comment]
Oh, the problem in your $metadata is that your tags are not correct.  The capitalization of reference should be Reference.  And uri must be Uri.  Perhaps, in these cases, it might be wise of us to recommend the Redfish-Reference-Checker tool that should point this out.

**Comment by PhillipWatts1012** [comment]
'That's strange.  I always run Reference Checker 1st and get no errors. I'll run it again in the morning.

**Comment by PhillipWatts1012** [comment]
So far it seems you are correct. **include** needed capitalization also.
But Reference Checker did not have errors before I made the change or after.

**Comment by tomasg2012** [comment]
I could've sworn there were new checks for miscapitalized tags, maybe I
misremembered.  I'll take a look at it.

**Comment by billdodd** [comment]
With the new and improved $metadata error reporting, I think this one can be closed. @mraineri - do you agree?

**Comment by mraineri** [comment]
It might be; @PhillipWatts1012 could you please run the latest version of the tool against your service to see if it helps with the error reporting? It should make it much clearer now and show what's wrong with $metadata rather than throwing nonsensical errors like before.

**Comment by mraineri** [comment]
@PhillipWatts1012 have you had a chance to check out the changes to see if that addresses the confusion about the error messages?

**Comment by PhillipWatts1012** [comment]
I will try to today.

________________________________

**Comment by mraineri** [comment]
@PhillipWatts1012 have you had a chance to try the newer version of the tool?

**Comment by tomasg2012** [comment]
Will close this one, if the issue arises again we'll just have to submit a new one or reopen this.
