### ISSUE TITLE
Note WARNING in HTML Report

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#173]
There are useful warnings in the txt log.  But users might not search and miss these.  Have we discussed noting these in the HTML report?
Maybe just a yellow-colored note in the pass: box

failAdditional: 1
warning: 1
pass: 41
passGet: 1
skipOem: 6
skipOptional: 19

If were possible to include in the Result column that would be great.

Insyde had a warning that I missed that ended up crashing the Conformance tool.

**Comment by tomasg2012** [comment]
Internally we've been considering a way to revamp how the HTML log is processed, and it would help to differentiate Warns and Error messages.  I will consider this in tandem.

**Comment by jbobzin-insyde** [comment]
OK, if you are working on this I will close.
You can open an enhancement if you wish.
