### ISSUE TITLE
Mangled URI ?

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#174]
Test is reporting error:
1 problemResource errors in /redfish/v1/Registries/Base.1.2.0...
in traverseService.py, around line 530, I added
                print ('ERRURI',self.uri)
and saw:
#MessageRegistryFile.v1_0_4.MessageRegistryFile, Counter({'pass': 7, 'skipOptional': 3, 'skipOem': 1, 'passGet': 1})

*** ServiceRoot -> Registries.Registries -> Members.MessageRegistryFile#0 -> Location.Uri.Uri, None
ERRURI **/redfish/v1/Registries/Base.1.2.0...**
/redfish/v1/Registries/Base.1.2.0...:  URI could not be acquired: 404

It certainly appears that the uri has been mangled by adding ....
But so far I cant find where.
Our service has:
"@odata.id": "/redfish/v1/Registries/Base.1.2.0",

Help?

**Comment by billdodd** [comment]
Can you share the payload of /redfish/v1/Registries/Base.1.2.0? I'm suspecting there may be an issue with the "Uri" property in the "Location" complex type.

**Comment by PhillipWatts1012** [comment]
In the below:
"PublicationUri": "http://redfish.dmtf.org/schemas/registries/v1/Base.1.2.0.json"
does not exist


{
    "Languages@odata.count": 1,
    "@odata.type": "#MessageRegistryFile.v1_0_4.MessageRegistryFile",
    "Location": [
        {
            "Language": "en",
            "PublicationUri": "http://redfish.dmtf.org/schemas/registries/v1/Base.1.2.0.json"
        }
    ],
    "@odata.id": "/redfish/v1/Registries/Base.1.2.0",
    "Description": "Base Message Registry File locations",
    "Languages": [
        "en"
    ],
    "Id": "Base.1.2.0",
    "@odata.context": "/redfish/v1/$metadata#MessageRegistryFile.MessageRegistryFile",
    "Registry": "1.2",
    "Location@odata.count": 1,
    "Name": "Base Message Registry File"
}

**Comment by billdodd** [comment]
Thanks. I think I know what the problem is. I can make a fix based on that.

Additionally, if you'd like to help confirm my suspicion, you could do the following:

Rerun the test with the `--debug_logging` option. Then grep for "Registry Location Uri" in the text log (ConformanceLog_*.txt). And post the grep output here.

**Comment by PhillipWatts1012** [comment]
I'll give it a try 1st thing in the morning.

**Comment by billdodd** [comment]
Thanks, Phillip. Actually, you don't need to confirm. I was able to repro that exact problem locally. I will make the fix.
