### ISSUE TITLE
More on failSchema errors

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#176]
in Summary:
1 failSchema errors in /redfish/v1/Systems/Rack1-Block1-Sled1-Node1/EthernetInterfaces/NIC.Embedded.1-1-2
NOTE NIC.Embedded.1-1-1  DID NOT fail  (they look almost identical)  here is 1-1-2:

redfishtool -r localhost -u root -p calvin raw GET /redfish/v1/Systems/Rack1-Block1-Sled2-Node1/EthernetInterfaces/NIC.Embedded.1-1-2
{
    "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
    "Id": "NIC.Embedded.1-1-2",
    "MACAddress": "10:98:36:A9:07:86",
    "Name": "System Ethernet Interface",
    "PermanentMACAddress": "10:98:36:A9:07:86",
    "@odata.id": "/redfish/v1/Systems/Rack1-Block1-Sled2-Node1/EthernetInterfaces/NIC.Embedded.1-1-2",
    "Status": {
        "State": "Enabled",
        "Health": "OK"
    },
    "Description": "The properties for a Computer System Ethernet Interface",
    "@odata.type": "#EthernetInterface.v1_3_0.EthernetInterface"
}

Error in HTML log:
ERROR - Schema element with Namespace attribute of VLanNetworkInterface not found in schema file http://redfish.dmtf.org/schemas/v1/VLanNetworkInterfaceCollection_v1.xml
VLanNetworkInterface ?????

metadata:
   <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterface_v1.xml">
        <edmx:Include Namespace="EthernetInterface" />
        <edmx:Include Namespace="EthernetInterface.v1_3_0"/>

Just in case, here is all of metadata:
<?xml version="1.0" encoding="UTF-8"?> 
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">

    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ServiceRoot_v1.xml">
      <edmx:Include Namespace="ServiceRoot" />
      <edmx:Include Namespace="ServiceRoot.v1_0_2"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/AccountService_v1.xml">
      <edmx:Include Namespace="AccountService" />
      <edmx:Include Namespace="AccountService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Chassis_v1.xml">
      <edmx:Include Namespace="Chassis" />
      <edmx:Include Namespace="Chassis.v1_4_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ChassisCollection_v1.xml">
        <edmx:Include Namespace="ChassisCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ComputerSystem_v1.xml">
        <edmx:Include Namespace="ComputerSystem" />
        <edmx:Include Namespace="ComputerSystem.v1_3_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ComputerSystemCollection_v1.xml">
        <edmx:Include Namespace="ComputerSystemCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterface_v1.xml">
        <edmx:Include Namespace="EthernetInterface" />
        <edmx:Include Namespace="EthernetInterface.v1_3_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterfaceCollection_v1.xml">
        <edmx:Include Namespace="EthernetInterfaceCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
        <edmx:Include Namespace="VLanNetworkInterface.v1_0_0"/>
    </edmx:Reference>  
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Event_v1.xml">
        <edmx:Include Namespace="Event" />
        <edmx:Include Namespace="Event.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventService_v1.xml">
        <edmx:Include Namespace="EventService" />
        <edmx:Include Namespace="EventService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/IPAddresses_v1.xml">
        <edmx:Include Namespace="IPAddresses" />
        <edmx:Include Namespace="IPAddresses.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/JsonSchemaFile_v1.xml">
        <edmx:Include Namespace="JsonSchemaFile" />
        <edmx:Include Namespace="JsonSchemaFile.v1_0_2"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/JsonSchemaFileCollection_v1.xml">
        <edmx:Include Namespace="JsonSchemaFileCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventDestination_v1.xml">
        <edmx:Include Namespace="EventDestination" />
        <edmx:Include Namespace="EventDestination.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EventDestinationCollection_v1.xml">
        <edmx:Include Namespace="EventDestinationCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogEntry_v1.xml">
        <edmx:Include Namespace="LogEntry" />
        <edmx:Include Namespace="LogEntry.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogEntryCollection_v1.xml">
        <edmx:Include Namespace="LogEntryCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Role_v1.xml">
        <edmx:Include Namespace="Role" />
        <edmx:Include Namespace="Role.v1_0_0" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RoleCollection_v1.xml">
        <edmx:Include Namespace="RoleCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogService_v1.xml">
        <edmx:Include Namespace="LogService" />
        <edmx:Include Namespace="LogService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/LogServiceCollection_v1.xml">
        <edmx:Include Namespace="LogServiceCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Manager_v1.xml">
        <edmx:Include Namespace="Manager"/>
        <edmx:Include Namespace="Manager.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerCollection_v1.xml">
        <edmx:Include Namespace="ManagerCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerAccount_v1.xml">
        <edmx:Include Namespace="ManagerAccount" />
        <edmx:Include Namespace="ManagerAccount.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerAccountCollection_v1.xml">
        <edmx:Include Namespace="ManagerAccountCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ManagerNetworkProtocol_v1.xml">
        <edmx:Include Namespace="ManagerNetworkProtocol" />
        <edmx:Include Namespace="ManagerNetworkProtocol.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Message_v1.xml">
        <edmx:Include Namespace="Message" />
        <edmx:Include Namespace="Message.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Power_v1.xml">
        <edmx:Include Namespace="Power" />
        <edmx:Include Namespace="Power.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Redundancy_v1.xml">
        <edmx:Include Namespace="Redundancy" />
        <edmx:Include Namespace="Redundancy.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Processor_v1.xml">
        <edmx:Include Namespace="Processor" />
        <edmx:Include Namespace="Processor.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ProcessorCollection_v1.xml">
        <edmx:Include Namespace="ProcessorCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Memory_v1.xml">
        <edmx:Include Namespace="Memory" />
        <edmx:Include Namespace="Memory.v1_3_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MemoryCollection_v1.xml">
        <edmx:Include Namespace="MemoryCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SerialInterface_v1.xml">
        <edmx:Include Namespace="SerialInterface" />
        <edmx:Include Namespace="SerialInterface.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SerialInterfaceCollection_v1.xml">
        <edmx:Include Namespace="SerialInterfaceCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Session_v1.xml">
        <edmx:Include Namespace="Session" />
        <edmx:Include Namespace="Session.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionCollection_v1.xml">
        <edmx:Include Namespace="SessionCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionService_v1.xml">
        <edmx:Include Namespace="SessionService" />
        <edmx:Include Namespace="SessionService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SimpleStorage_v1.xml">
        <edmx:Include Namespace="SimpleStorage" />
        <edmx:Include Namespace="SimpleStorage.v1_2_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SimpleStorageCollection_v1.xml">
        <edmx:Include Namespace="SimpleStorageCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Task_v1.xml">
        <edmx:Include Namespace="Task" />
        <edmx:Include Namespace="Task.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/TaskCollection_v1.xml">
        <edmx:Include Namespace="TaskCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/TaskService_v1.xml">
        <edmx:Include Namespace="TaskService" />
        <edmx:Include Namespace="TaskService.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Thermal_v1.xml">
        <edmx:Include Namespace="Thermal" />
        <edmx:Include Namespace="Thermal.v1_1_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VirtualMedia_v1.xml">
        <edmx:Include Namespace="VirtualMedia" />
        <edmx:Include Namespace="VirtualMedia.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VirtualMediaCollection_v1.xml">
        <edmx:Include Namespace="VirtualMediaCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
        <edmx:Include Namespace="VLanNetworkInterface.v1_0_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterfaceCollection_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
        <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFileCollection_v1.xml">
        <edmx:Include Namespace="MessageRegistryFileCollection" />
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/MessageRegistryFile_v1.xml">
        <edmx:Include Namespace="MessageRegistryFile" />
        <edmx:Include Namespace="MessageRegistryFile.v1_0_0" />
    </edmx:Reference>

    <edmx:DataServices>
 
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Service">
          <EntityContainer Name="Service" Extends="ServiceRoot.v1_0_2.ServiceContainer"/>
      </Schema>

  </edmx:DataServices>
</edmx:Edmx>

**Comment by mraineri** [comment]
So, your metadata file is including the file VLanNetworkInterfaceCollection_v1.xml. From that file, it's pulling in the namespace VLanNetworkInterface, which is not correct; the only namespace in that file is VLanNetworkInterfaceCollection.

There is an error in your metadata file, but it is odd that it's called out as part of the payload validation for that EthernetInterface resource.

**Comment by PhillipWatts1012** [comment]
Thanks Michael, we will repair.

**Comment by pwvancil** [comment]
question answered.

**Comment by pwvancil** [comment]
suggestion to create a metadata checker to check this
