### ISSUE TITLE
Question about deprecation

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#177]
ERROR - FanName: The given property is deprecated: This property has been Deprecated in favor of Thermal.v1_1_0.Thermal.Fan.Name

It appears, searching the schemas, the Thermal.1_1_0 maybe  the
   ONLY version in which FanName is NOT marked as deperecated.

So....  The question is:  **how does Service Validator know that its deprecated**?
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Thermal_v1.xml">
        <edmx:Include Namespace="Thermal" />
        <edmx:Include Namespace="Thermal.v1_1_0"/>
    </edmx:Reference>

**Comment by PhillipWatts1012** [comment]
Ah, its in the xml.  sorry, never mind.

**Comment by pwvancil** [comment]
separe issue handling changing message to warning
