### ISSUE TITLE
A reporting request.

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#178]
Paul and I have a problem and a request.
QA is gradually being separated.
The QA team has policies and procedures.
Anything which is reported as an error is an issue and a ticket.
Therefore this request:
1) Do not report deprecation errors.  OR
2) Report them as warnings, removing the word error. OR
3) give us a command line option to suppress
       failSchema errors.
Please consider.
Thanks

**Comment by billdodd** [comment]
I think the intent for deprecation was to report them as warnings. So I think option 2 is correct.
