### ISSUE TITLE
Check the validation of Actions Blocks (My AI from Tools Mttn)

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#182]
In recent test it appeared that unexpected property ("Target" instead of  "target") in action block was not detected.  The spec in 6.5.4.7.1 has this text-

> The  value of the property shall be a JSON object containing a property named "target"

Based on shall in that sentence I think the Validator should post an error if "target" item is not found or if the target URL value is obviously mal-formed. Currently this is set to a Warning in Validator. If there is spec inconstancy on requirement for "target" let the spec WG deal with that. The shall seems clear to me.

Because of "may", in next paragraph"AllowableValues" is optional.  But if found it has a defined structure. 

Can there be anything else in the block?   In 6.4.4.7, the spec says 

> The resource may provide a separate ActionInfo

So here is how I would explain this for the Validator team -
1. For base Action, "target" is expected and "AllowableValues" may appear. There is no metadata for this, field structure are defined per spec
2. Action may optionally supply "@Redfish.ActionInfo" and a URI. Nothing else may appear in the block.
3. This URI would point to a new page with "@odata.type": "ActionInfo"
4. This would trigger a $metadata search for the metadata file and a validation of the contents of the type

Can you check if this matches the current Validator coding? 
Can we figure out how to test this with a mockup?

**Comment by tomasg2012** [comment]
I was not aware of any ActionInfo specifics, so I don't believe the validator has any logic to accomodate as of now, will have to be implemented.

**Comment by jbobzin-insyde** [comment]
Lets wait some time for additional comments and corrections, but I would suggest - fix the standard parameters and mark ActionInfo as a Enhancement.

**Comment by mraineri** [comment]
For now, let's assume "target" is not required to be in the payload until we get a final answer from the SPMF.
