### ISSUE TITLE
Should Service Validator Check this - latest type not included in $metadata include list?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#185]
In my test of Service-Validator, this issue is not found in report- 

$metadata missing up-to-date <edmx:Include Namespace= "Type.new-version" when a page references a property defined the latest "Type.new-version" but not defined in the base version.
The page did contain update of the local #odata.type.
Recent service change to add the latest newly-added property and type to the page neglected to update $metadata to also reference the latest type.

The Service-Conformance-Check did flag the issue in 7.2.1

Should this be a reported error?  How important is this omission? Error or Warning?

**Comment by tomasg2012** [comment]
This kind of misuse of typing isn't a huge error for the tool itself, but it seems on a greater scale it should be important.  Seems necessary to make it an error.  The spec itself 7.2.1 seems to label this important for security reasons...

**Comment by mraineri** [comment]
I would think this should be an error; not having a properly constructed $metadata resource will break generic OData clients. $metadata is the decoder ring for these clients when trying to determine where the namespaces referenced by `@odata.type` and `@odata.context` come from.

**Comment by mraineri** [comment]
Let's use this to track reporting of $metadata errors. The tool should be doing something like this:
- Perform initial read of $metadata
- Go through all of the resources and tally the namespaces referenced (from the `@odata.context` and `@odata.type` properties)
- At the end, create a $metadata report so all $metadata errors are highlighted in a consistent manner

**Comment by billdodd** [comment]
@mraineri and @jautor - For the $metadata section of the report, do you have any input on a suggested format? The current resource sections have the tables with columns for Property Name, Value, Type, Exists, and Result. But these are mostly not applicable to $metadata.

For example: Should there be a table showing all the namespaces referenced by the service with a FAIL indicator for each one that is missing from $metadata? Or just a list of the errors found (no table)?

**Comment by mraineri** [comment]
I think a table for the error would be for the best; something like...

Error: The following namespaces are referenced by the service, but are not included in $metadata:

- NamespaceX
- NamespaceY
- NamespaceZ

**Comment by jautor** [comment]
I like Mike's answer.  The converse should not be flagged - a namespace/schema can appear in $metadata without being used - as that usage will depend heavily on the configuration (and installed options) of the product under test...

**Comment by jbobzin-insyde** [comment]
Are we in agreement that listing every referenced errata release in $metadata is required or not?

My point is that there is no metadata (xml) difference between "Message.v1_0_2", "Message.v1_0_3", "Message.v1_0_4", and "Message.v1_0_5".  The XML notation for errata update is just documentation.

It seems to me to be excessively pedantic to throw an error if the $metadata does not list every referenced errata version.

In contrast, my original issues involved not errata version but missing minor version reference which we all agree is significant.

My thinking is that errata version in $metadata should be don't care for this tool.

**Comment by mraineri** [comment]
It's only required if your service actually uses all of those versions for different payloads. However, I can't imagine why for some instances you'd report the `@odata.type` property as `#Message.v1_0_2.Message` and a different payload uses `#Message.v1_0_3.Message`.

The key thing is $metadata contains the namespaces referenced by your service in the `@odata.type` and `@odata.context` properties. If you only use `#Message.v1_0_5.Message`, then there's no need to include Message.v1_0_0 to Message.v1_0_4.

**Comment by jbobzin-insyde** [comment]
Or perhaps there are some cases where the xml block defining the namespace for an errata version includes something useful for validation?
And not just the typical "This version was created to show annotations in previous namespaces were updated."

**Comment by mraineri** [comment]
Unfortunately with how OData works, the namespace references need to be explicit; there's no need for you to keep bumping up the errata version you use if you don't see value in it.
