### ISSUE TITLE
Any alternative to BS4's XML support?

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#190]
Installing the BS4 library for XML parsing (lxml) on Windows machines creates a large burden on the platform, as that module has C++ components which require a compiler to be installed (Visual Studio).  

Are there any alternatives to BS4 for this support that could be used instead?  

At the least we should add instructions in the README on this requirement for Windows installs

**Comment by tomasg2012** [comment]
I was aware that lxml was installed through the pip3 python pipeline and did not require to be compiled... it should be installed through the command `pip3 install -r requirements.txt`, does it require external installations?  I don't recall.

**Comment by jautor** [comment]
Yeah, during the install of BS4 (through the pip process above), the BS4 install fails with pages of errors (on Windows) and quick googling of the head issue provided the details.  The XML component of BS4 is C++ based and therefore needs a compiler...  Not a problem on Linux, of course.  But as this is an end user / QA tool, asking folks to install the 300GB of VS is awful...

**Comment by jautor** [comment]
Actually, a better solution would be for us to build stable release Windows EXEs and post here for the end-user-facing utilities.  Bypass all the build and just let them use the tool...  And a heck of a lot easier than attempting to unravel the BS4 stuff...

**Comment by mraineri** [comment]
If we do that, we should probably also make a build script so we can package things up consistently for each release we tag.

**Comment by billdodd** [comment]
Some notes on the options:

1. Instructions to install binary prereqs on Windows
    There is a website that hosts Windows binary images of many popular compiled Python libraries.
    https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
    These are unofficial and not supported so may not be acceptable to some organizations. This option probably requires the least work in the near term. But we may end up getting a lot of issues opened if users have trouble with the pre-built images.
2. Use an alternative XML parser
    There are other XML parsers that do not require additional binary libs, including `xml.etree.ElementTree` and `xml.dom.minidom`. The API for these parsers is similar to BS4, so it shouldn't be too difficult to switch.
3. Convert the Python code to Windows EXE
    There are several tools for this. Two of the more popular ones seem to be [cx_Freeze](http://cx-freeze.readthedocs.io/en/latest/index.html) and [PyInstaller](https://www.pyinstaller.org/). As Mike alluded to in his comment, this would require that we rebuild new Windows binaries for each release of each of our tools that uses lxml (4 tools as often as once a week each).

**Comment by jautor** [comment]
With the binary releases now available, this issue has been resolved.
