### ISSUE TITLE
Improve error message for incorrect user credentials

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#191]
Using the config file, attempting to run with incorrect username/password and Session auth, utility fails with "Session could not start".
With Basic Auth, the report runs with only the ServiceRoot shown (since it is un-authenticated), with all other resources showing failures.  

The tool should clearly report that the connection failed due to login issues and terminate - no reason to generate a report when the login credentials given are in error.  And the failure message must indicate this is due to credential problems (either username or password).

**Comment by billdodd** [comment]
I've been doing some testing/investigation. In the case of Session auth, it seems to be difficult to tell if the problem is bad authentication or something else.

The 2 systems I have access to both return `400 Bad Request` when supplied with invalid creds.

**Comment by jautor** [comment]
That will probably be the answer (we probably can't tell bad credentials from other errors), but we could have the tool exit on error at that point - suggest "check user credentials" (and report the HTTP code of course).  Probably a reasonable answer for the "first" expected result that requires authentication - assuming there's a good point in the code for that - Session creation would seem to be a good point, but for basic auth?

Or maybe we just keep a count of 400 errors and stop trying after a few consecutive errors with no success?

**Comment by billdodd** [comment]
Agree. We're thinking along the same lines. I have some ideas and will keep experimenting and come up with something that works well.
