### ISSUE TITLE
Determine resource's schema when not found in $metadata

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#195]
(this was mentioned before but may have been lost, and doesn't appear to be implemented)

When a resource's schema (name/version) doesn't appear in the $metadata file (an error that should be flagged as such), the tool will produce numerous failures for the resource because the schema isn't loaded.  

As $metadata issues are fairly common, having the tool fail at that point masks numerous validation tests that could be performed if the schema was known.  As the the correct schema can be determined (or at least, should be if the @odata.type is valid), the tool should attempt to construct the schema and continue running.  

This can allow most implementations to obtain a fairly complete and accurate test run, instead of failing very early in the run due to $metadata errors, and therefore can significantly reduce the number of test/build/release/test iterations required to bring an implementation into conformance with the spec and schemas.

**Comment by mraineri** [comment]
I think we have this tracked as part of issue #185 already; does the last comment in that issue cover everything you need?

**Comment by jautor** [comment]
The part perhaps not covered is "continue testing using an assumed (from odata.type) schema regardless of $metadata errors.  But certainly could be tracked as part of that issue...
