### ISSUE TITLE
Error on Copyright in Base Message Registry file Base.1.2.0.json (in DSP8011_2017.2) 

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#205]
There is a Copyright in the published Base.1.2.0.json file (in DSP8011_2017.2) 
When checking /redfish/v1/Registries/BaseMessages/Base.1.1.0.json , Validator generates 
ERROR - @Redfish.Copyright not defined in schema MessageRegistry.v1_0_0 (check version, spelling and casing)

How to fix?

**Comment by mraineri** [comment]
This seems like this issue is already covered by #197 and will be fixed with PR #202

**Comment by billdodd** [comment]
Actually, I don't think this is related to issue #197 / PR #202.

The most likely cause of this error is that the Redfish alias for RedfishExtensions.v1_0_0 is missing from the $metadata.

Jeff - can you run with the latest version of the tool and check the results for /redfish/v1/$metadata in the HTML report (it's the first resource section in the report)?

**Comment by jbobzin-insyde** [comment]
Bill, your diagnosis is correct. Was the Redfish Alias

**Comment by jbobzin-insyde** [comment]
This $metadata ref looks correct - 
   <edmx:Reference Uri="/redfish/v1/schema/RedfishExtensions_v1.xml">
        <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
        <edmx:Include Namespace="Validation.v1_0_0"/>
    </edmx:Reference>
The file is present, and Copyright is defined inside.

but I see the error 

ERROR - @Redfish.Copyright not defined in schema MessageRegistry.v1_0_0 (check version, spelling and casing)

**Comment by jbobzin-insyde** [comment]
This passes again on latest PR
