### ISSUE TITLE
Check that listed namespaces in $metadata are included in Referenced schema

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#206]
EthernetInterface v1.4.0 resource, with $metadata entries for EthernetInterface and VLanNetworkInterface (which appear to be correct).

JSON payload snippet:
~~~json
    "VLAN": {
        "VLANEnable": false,
        "VLANId": null
    }
~~~

Yields an error for that resource:
ERROR - VLAN: This type is invalid none

The definition here is a rare case of a referenced object to an external schema, which I assume is where the problem lies...

$metadata snippets for the related files:
~~~
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/EthernetInterface_v1.xml">
        <edmx:Include Namespace="EthernetInterface" />
        <edmx:Include Namespace="EthernetInterface.v1_0_3"/>
        <edmx:Include Namespace="EthernetInterface.v1_4_0"/>
    </edmx:Reference>
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
        <edmx:Include Namespace="VLanNetworkInterface.v1_0_0"/>
        <edmx:Include Namespace="VLanNetworkInterface.v1_1_1"/>
    </edmx:Reference>

~~~

**Comment by mraineri** [comment]
In this case, the $metadata document doesn't even need to reference VLanNetworkInterface; that comes for free as part of the EthernetInterface schema.

**Comment by billdodd** [comment]
The issue was with this $metadata element:

```
    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/VLanNetworkInterfaceCollection_v1.xml">
        <edmx:Include Namespace="VLanNetworkInterface" />
    </edmx:Reference>
```
The Namespace should be `VLanNetworkInterfaceCollection`.

The tool did report this as:

> ERROR - Schema element with Namespace attribute of VLanNetworkInterface not found in schema file http://redfish.dmtf.org/schemas/v1/VLanNetworkInterfaceCollection_v1.xml

I assume another $metadata validation check we could add would be to sure that all these `Foo` namspaces match in a given Reference element:

    <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/Foo_v1.xml">
        <edmx:Include Namespace="Foo" />
        <edmx:Include Namespace="Foo.v1_0_3"/>
        <edmx:Include Namespace="Foo.v1_4_0"/>
    </edmx:Reference>

**Comment by jautor** [comment]
Dang it!  Now I owe you another coke...  :+1: 

Yeah, that addition would be a good one - I stared at it looking for typos (the usual suspects) and completely missed that.  And it's so easy to do as that whole file is cut/paste search/replace to construct...

Moving to Enhancement...
