### ISSUE TITLE
Validator reports ERROR - Actions.xxx: Property "title" is not allowed in actions property

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#209]
Current Validator reports the ERROR - Actions.xxx: Property "title" is not allowed in actions property. 
Here is the JSON payload snippet:
```
    "Actions": {
        "#UpdateService.SimpleUpdate": {
            "target": "/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate",
            "title": "SimpleUpdate",
            "TransferProtocol@Redfish.AllowableValues": [
                "TFTP",
                "SFTP"
            ]
        }
    }
```
Validator reported:
```
ERROR - Actions.#UpdateService.SimpleUpdate: Property "title" is not allowed in actions property. Allowed properties are "target", "@Redfish.ActionInfo" and "*@Redfish.AllowableValues"
```
Though there is no property "title" in any metadata file, the all Action definition of schema 2018.1 still have the property "title". Is this a bug or the property "title" will be removed?

**Comment by mraineri** [comment]
Title is allowed in the Action object; it's not required though

**Comment by JojoWu19** [comment]
Get it, thanks.
