### ISSUE TITLE
Validate odata.id for referenceable members (and other URL-valued properties?)

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#213]
Tool should validate the odata.id for referenceable members (items within JSON arrays which may be accessible directly), as those id's have a specific format that must be followed.  The fragment must point to the array itself and the array index.  As these Id's are only used for that optional functionality (but their presence is required by schema), errors in their construction may otherwise go unnoticed. 

Example (first is wrong, second is right):
~~~json
{
    "Temperatures": [
        {
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/purple/",
            "Name": "A sensor with an invalid @odata.id",
            "PhysicalContext": "Intake",
            "ReadingCelsius": 30,
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            }
        },
        {
            "@odata.id": "/redfish/v1/Chassis/1/Thermal#/Temperatures/1",
            "Name": "But this one is ok...",
            "PhysicalContext": "CPU",
            "ReadingCelsius": 40,
            "Status": {
                "Health": "OK",
                "State": "Enabled"
            }
        }]
}
~~~

**Comment by mraineri** [comment]
For reference: RFC6901

**Comment by mraineri** [comment]
Closing; fixed in latest PR
