### ISSUE TITLE
Many "Not Found in Type Inheritance" Errors Reported

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#22]
After update to latest pull, there are errors flagged that I do not understand.
This test has $metadata that pulls all schema from DMTF. (LocalOnlyMode = False)
Earlier version reports different errors.
[metadata.zip](https://github.com/DMTF/Redfish-Service-Validator/files/979924/metadata.zip)
[logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/979847/logs.zip)
zip file created with 7zip

First Error (also note typo in message - inheritance)

ServiceRoot.v1_0_0.ServiceRoot:SessionService: Expected Entity type ('SessionService.SessionService', None), but not found in type inhertiance ['SessionService.v1_1_1.SessionService']
ServiceRoot.v1_0_0.ServiceRoot:AccountService: Expected Entity type ('AccountService.AccountService', None), but not found in type inhertiance ['AccountService.v1_1_0.AccountService']

**Comment by tomasg2012** [comment]
This type inheritance should be successful in this circumstance, yes, sorry about the typo.

However, I don't see that particular error in the logs you provided, am I mistaken?  Is this the latest pull on master?

**Comment by jbobzin-insyde** [comment]
git.exe pull --progress -v --no-rebase "origin"

From https://github.com/DMTF/Redfish-Service-Validator
= [up to date]      master     -> origin/master
Already up-to-date.

Success (485 ms @ 5/5/2017 3:42:49 PM)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Log starting line 1478

DEBUG - success: True #SessionService.v1_1_1.SessionService
DEBUG - success: False None
DEBUG - SessionService.SessionService, None, ['SessionService.v1_1_1.SessionService']
ERROR - ServiceRoot.v1_0_0.ServiceRoot:SessionService: Expected Entity type ('SessionService.SessionService', None), but not found in type inhertiance ['SessionService.v1_1_1.SessionService']
INFO -   FAIL

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Lines from the $metadata

<edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/SessionService_v1.xml">
<edmx:Include Namespace="SessionService"/>
<edmx:Include Namespace="SessionService.v1_0_3"/>
<edmx:Include Namespace="SessionService.v1_1_1"/>
</edmx:Reference>

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

The page

{"@Redfish.Copyright":"Copyright (c) 2015-2017, Insyde Software Corp. All Rights Reserved.","@odata.context":"/redfish/v1/$metadata#SessionService.SessionService","@odata.id":"/redfish/v1/SessionService",
"@odata.type":"#SessionService.v1_1_1.SessionService","Id":"SessionService","Name":"SessionService"
,"Description":"SessionService","Status":{"State":"Enabled","Health":"OK"},"ServiceEnabled":true,"SessionTimeout":1800,
"Sessions":{"@odata.id":"/redfish/v1/SessionService/Sessions"}}

**Comment by tomasg2012** [comment]
Like in the other comment, the program seems to have some issues with inheritance and references.  I will be producing a more fleshed out debug.

**Comment by jbobzin-insyde** [comment]
problem was in test system
