### ISSUE TITLE
Build local schema cache from DMTF site 

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#220]
Copying functionality from the Conformance Check tool...

Allow tool to download the schema bundle from the DMTF site - prefer to only download it if the tool doesn't find a file/reference in the existing local schema cache (don't need to do it every time, nor cause failures if there's no internet access).

**Comment by tomasg2012** [comment]
Added functionality in PR #232, but as an option --schema_pack that extracts zip at a given URI before anything is processed.  

However, this option does not prefer the local copy over a normal GET of the Schema, unless the option `--localonly` is used or a URI on $metadata does not succeed.

**Comment by mraineri** [comment]
General thoughts on the flow:
- By default, the tool should use the local cache copy
- If the local cache copy does not exist, and the reference for the schema on the service is to the service itself, get it from the service (and store it in the local cache it if successful)
- If the file on the service does not exist, go to the DMTF site to get the file (and store it in the local cache it if successful)
- If it can't be found at this point, then there's some problem

**Comment by tomasg2012** [comment]
Current implementation doesn't automatically cache XML files when acquired, would seem necessary to reopen such that the tool itself can automatically do it.  This can be reopened to do so;  unpacking the schema pack should most necessarily alleviate DMTF traffic, but does not enforce it and doesn't automatically spare DMTF the traffic.

**Comment by tomasg2012** [comment]
Closing; fixed in latest PR.
