### ISSUE TITLE
Error while running redfish validator

### ISSUE THREAD

**Issue by veedu** [DMTF/Redfish-Service-Validator#225]
Hi,

I raised issue 219 and it got fixed via issue 223. Now I took the latest code and ran the redfish validator and it throws the following error:

 python3 RedfishServiceValidator.py -c config/config.ini -v
Something went wrong
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1222, in main
    rst.setByArgparse(args)
  File "/home/vidhyag/newval/april_30_val/may_4/Redfish-Service-Validator/traverseService.py", line 113, in setByArgparse
    configpsr = configparser.ConfigParser()
NameError: name 'configparser' is not defined

**Comment by mraineri** [comment]
I see the problem; I'll fix it as part of the release I'll be doing today

**Comment by mraineri** [comment]
Fixed by #226
