### ISSUE TITLE
Allow validation of services using http plus authentication

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Service-Validator#235]
The Redfish spec requires that HTTPS be used when sending requests using Basic Auth. And HTTPS must also be used when sending a POST request to create a new session.

Since the validation tool is valuable for testing in-development systems that may not (yet) have HTTPS available or enabled, we should allow running the tool in this scenario. Currently, the tool will not send authentication creds if the scheme is HTTP. We should make a change to send the creds (if specified) even if the scheme is HTTP. In this case, the tool should show an error in the report indicating that sending creds over HTTP is disallowed by the spec. But it should proceed with the validation and populate the report with any other issues found.

**Comment by mraineri** [comment]
Fixed by #236
