### ISSUE TITLE
There are some resource errors reported by the validator

### ISSUE THREAD

**Issue by veedu** [DMTF/Redfish-Service-Validator#239]
Links.HostingSystem | Link: /redfish/v1/StorageSystems/FPGA_000 | link to: Resource | Yes | FAIL
-- | -- | -- | -- | --

ERROR - Links.HostingSystem: Linked resource reports schema version (or namespace): Resource.Resource not found in schema file Resource
There are more resource errors reported by the Validator tool.
ERROR - ConnectedEntities[0].EntityLink: Linked resource reports schema version (or namespace): Resource.Resource not found in schema file Resource
We are using EntityType Volume and the EntityLInk is pointing to a property of type Volume but its throwing above error.

Also, can you please provide a working example of implementing EntityLink. Attached metadata file.
[$metadata.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2115383/metadata.zip)

**Comment by tomasg2012** [comment]
This is a bug with the tool, it does not recognize the generic Resource.Resource link and thinks there's a problem.  The error is vague as well, since it references the generic Type vs the Type of the resource.  This should be unrelated to your implementation, and will be fixed ASAP.

**Comment by veedu** [comment]
Apart from the above, we have other resource errors like link to HostedServices, NetworkAdapters throwing error like below:

There is a link to NetworkAdapter in NetworkInterface property and tool is throwing the below error:
Links.NetworkAdapter | Link: /redfish/v1/Chassis/CARD_001/NetworkAdapters | link to: NetworkAdapter | Yes | FAIL
-- | -- | -- | -- | --
ERROR - Links.NetworkAdapter: Linked resource reports schema version (or namespace): NetworkAdapter.NetworkAdapter not found in schema file NetworkAdapter

Similarly, link to link to HostedServices.StorageServices in ComputerSystem property is throwing error:


HostedServices | [JSON Object] | ComputerSystem.v1_2_0.HostedServices | Yes | complex
-- | -- | -- | -- | --
HostedServices.StorageServices | Link: /redfish/v1/StorageServices | link to: HostedStorageServices | Yes | FAIL

ERROR - HostedServices.StorageServices: Linked resource reports schema version (or namespace): HostedStorageServices.HostedStorageServices not found in schema file HostedStorageServices

Are these tool errors? If not, can you please tell us structure how the properties should be oraganized. We are implementing them like this

HostedServices
{
  StorageServices
  {
        "odata.id" : "/redfish/v1/StorageServices"
 }
}

**Comment by veedu** [comment]
Hi,

Please find the debug logs attached. 
Can you let us know how to represent HostedServices.StorageServices?Also in LogEntry, we have implemented odata.type and odata.context but it throws error "WARNING - No @odata.type present, assuming highest type LogEntry.v1_3_0.LogEntry" .
[debug logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2127637/debug.logs.zip)
[debug logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2127639/debug.logs.zip)
[debug_logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2127646/debug_logs.zip)

/redfish/v1/Systems/HNA_001/LogServices/HOST_latest/Entries/HOST_1970_01_01_20_08_06_740073
{
  "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
  "@odata.id": "/redfish/v1/Systems/HNA_001/LogServices/HOST_latest/Entries/HOST_1970_01_01_20_08_06_740073",
  "@odata.type": "#LogEntry.v1_0_0.LogEntry",
  "Description": "Information of Log entry",
  "EntryType": "Event",
  "EventTimestamp": "1970-01-01 20:08:06.740073 T 00:00",
  "EventType": "TBD",
  "Id": "HOST_1970_01_01_20_08_06_740073",
  "Message": "Link Up - port:1",
  "Name": "Log Entry",
  "Severity": "info"
}

**Comment by veedu** [comment]
[debug_logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2127648/debug_logs.zip)

**Comment by veedu** [comment]
Hi,

Please find the debug logs attached.
Can you let us know how to represent HostedServices.StorageServices?Also in LogEntry, we have implemented odata.type and odata.context but it throws error "WARNING - No @odata.type present, assuming highest type LogEntry.v1_3_0.LogEntry"

/redfish/v1/Systems/HNA_001/LogServices/HOST_latest/Entries/HOST_1970_01_01_20_08_06_740073
{
"@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
"@odata.id": "/redfish/v1/Systems/HNA_001/LogServices/HOST_latest/Entries/HOST_1970_01_01_20_08_06_740073",
"@odata.type": "#LogEntry.v1_0_0.LogEntry",
"Description": "Information of Log entry",
"EntryType": "Event",
"EventTimestamp": "1970-01-01 20:08:06.740073 T 00:00",
"EventType": "TBD",
"Id": "HOST_1970_01_01_20_08_06_740073",
"Message": "Link Up - port:1",
"Name": "Log Entry",
"Severity": "info"
}

**Comment by tomasg2012** [comment]
This should be fixed with the latest PR.

**Comment by mraineri** [comment]
@tomasg2012 to review pull requests to see when it was fixed (and close)

**Comment by tomasg2012** [comment]
Fixed with PR #244
