### ISSUE TITLE
github summary incorrect

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#24]
The github summary line is incorrect. Tool has been updated to Python 3

Current = The Redfish Service Validator is a python2.7 tool for checking conformance of any "device" with a Redfish service interface against Redfish CSDL schema

**Comment by tomasg2012** [comment]
No kidding, I thought that would change with the README.md.  I don't seem to know how to change it and I don't think I have the permissions to.

**Comment by mraineri** [comment]
It actually is a summary field for the repo itself; it doesn't come from the Readme file.

I have admin permissions, so I corrected the summary.
