### ISSUE TITLE
Missing argv argument in ArgParse parse_args

### ISSUE THREAD

**Issue by omar-ocampo** [DMTF/Redfish-Service-Validator#241]
arrgget.parse_args is ignoring "argv" main function argument.

The issue does not appear if calling the application from command line, but it does appear if calling main() directly.

Replace line:

    args = argget.parse_args()

With:

    args = argget.parse_args(argv)
    
Cheers

**Comment by tomasg2012** [comment]
I recently learned that argparse by default uses sys.argv without having to import it or pass it through, but what it accepts via parameter is slightly different.  This should be changed, yes.

**Comment by tomasg2012** [comment]
Corrected in latest PR.
