### ISSUE TITLE
Also see "ERROR - Unable to retrieve $metadata resource at /redfish/v1/$metadata"

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#243]
I am seeing this error but postman says the header is fine.
  content-type →application/xml
Is it possible the error text means there is a bad URI in the $metadata? If so, how do I determine which URI is broken?

Obviously from the counters it did find something:
INFO - Counter({'pass': 148829, 'skipOptional': 107589, 'metadataNamespaces': 515, 'passGet': 155, 'serviceNamespaces': 77, 'repeat': 28, 'warningPresent': 21, 'failComplex': 12, 'failNoSchema': 7, 'err.IPAddresses.v1_0_0.PrefixLength': 3, 'failMandatoryExist': 3, 'failAdditional': 3, 'unvalidated': 1, 'err.Edm.Boolean': 1, 'failErrorPresent': 1, 'failProp': 1, 'reflink': 1, 'exceptionResource': 1})

**Comment by billdodd** [comment]
I don't think a bad URI in the $metadata would cause that error, but I could be wrong. If you could zip up the 2 log files and attach here, that would help diagnose what is happening.

**Comment by tomasg2012** [comment]
This is actually an oversight from last PR, and needs a line to fix.

**Comment by jbobzin-insyde** [comment]
I confirm the PR fixes the incorrect message
