### ISSUE TITLE
Set OemCheck to False but Validator reports error

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#245]
When set OemCheck to False, Validator still reports some Oem errors. Although the error amount is less than the number when OemCheck is True, I expect the report should be the same with before, is it correct?

In my environment, there are only standard CSDL (xml) files, and all JSON schema files (standard  and Oem). The attachment includes some part logs:
[log.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2136551/log.txt)

**Comment by tomasg2012** [comment]
This is a tool issue dealing with specifically vanilla Resource.Oem, since it uses Redfish.Additional as a tag.  It's a non-issue for implementation.  I'll add in a fix to the branch `fix-latest` tomorrow.

Does this occur with oemcheck set to True as well?  Can you provide a payload example of either of these error occurrences?

**Comment by JojoWu19** [comment]
Yes, it also can be found with oemcheck set to True. Attache payload and log with oemcheck set to True:
[payload.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2136880/payload.txt)
[log_oemcheck_true.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2136882/log_oemcheck_true.txt)

**Comment by tomasg2012** [comment]
When this issue is fixed, it should be noted that items inside "Oem", like the one "*******" (censored?), should be 'casted' with @odata.type inside the dict brackets `{ }`, since by default they are a neutral, untestable "Resource.OemObject".

The error that should've been reported as a result should be "Resource.OemObject should be typecasted with @odata.type"

**Comment by JojoWu19** [comment]
Do you mean the payload of /redfish/v1/UpdateService/FirmwareInventory/UEFI must like below?

`{`
>`"Id": "UEFI",`
>`"@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/UEFI",`
>`"@odata.type": "#SoftwareInventory.v1_2_0.SoftwareInventory",`
>`"Oem": {`
>>`"Abcd": {`
>>>`"@odata.type": "#AbcdSoftwareInventory.v1_0_0.SoftwareInventory",`
>>>`"Manufacturer": "Abcd",`
>>>`"FirmwareType": "UEFI",`
>>>`"FirmwareName": "UEFI" } } }`

If the implementation does not  add the @odata.type in the embedded object "Abcd", Validator will report error even oemcheck set to false, is it right?

**Comment by tomasg2012** [comment]
Yes, that looks accurate.  However, it would not report the error if set to off.

**Comment by JojoWu19** [comment]
How about set oemcheck to true and not add the @odata.type in the embedded object "Abcd" but modify the standard xml to refer AbcdSoftwareInventory (if this is allowed)?

**Comment by tomasg2012** [comment]
I don't believe modifying base Schema for implementation-based properties would be wise, however it would likely validate anyway.

**Comment by jbobzin-insyde** [comment]
Agree with Tomas.  Section 7.5.7.1 gives an example of a Oem-defined  Schema file that defines a new ComplexType. The schema file reference would need to added to $metadata. I assume a local schema store would be most convenient place to stash this xml file.

**Comment by JojoWu19** [comment]
You are right. There is a statement `The OEM-specified property shall also include a type
property that provides the location of the schema and the type definition for the property within that
schema.` in the `7.5.7.2. Oem property format and content` of specification. So @odata.type is required in the Oem-defined object.

And I do not see any Oem errors after verifying with the fix-latest branch.

**Comment by tomasg2012** [comment]
Fixed with latest PR
