### ISSUE TITLE
Failed on Bios Page - unclear what is wrong

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#246]
Current build has a very large page of type Bios (attached)
[Bios.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2142670/Bios.zip)
The idea is to test all of the possible Bios settings.

The validator throws several errors. It is not clear what is wrong. Is it possible this is because the page @odata.type follows the Settings Object in the file?
[logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2142685/logs.zip)

Chrome is slow with the big file. Firefox seems to work a little better.

**Comment by tomasg2012** [comment]
The tools going thru some growing pains this PR, I apologize.  If this is the latest of the fix branch, it's reported @odata items as additional and treating them as default Resource.OemObject, which the default behavior (of the tool).  As a result, it overrides normal behavior.

@mraineri might be able to shine some info:  should the xml tag Odata.Additional generally be ignored?  What does it serve if it's usually impossible to determine the type of the item in question?

```
<Term Name="AdditionalProperties" Type="Core.Tag" DefaultValue="true" AppliesTo="EntityType ComplexType">
<Annotation Term="Core.Description" String="Instances of this type may contain properties in addition to those declared in $metadata"/>
<Annotation Term="Core.LongDescription" String="If specified as false clients can assume that instances will not contain dynamic properties, irrespective of the value of the OpenType attribute."/>
</Term>
```
The excerpt from Odata.  However, Redfish's DynamicProperty tag is unrelated to such, and I don't believe we use OpenType?

Meanwhile, it looks like Settings just failed to find itself, that's also a tool bug.  It's good that these testing situations are available, but a test suite for this tool should be made now that it's more mature...

**Comment by mraineri** [comment]
Generally speaking, the Redfish data model sets that tag to false except in the OEM object case. It's probably for the best just to assume it to always be false.

**Comment by jbobzin-insyde** [comment]
after sync with your latest commit

`*** /redfish/v1/Systems/123456789/Bios
         Type (Bios), GET SUCCESS (time: 0.765288)
Traceback (most recent call last):
  File ".\RedfishServiceValidator.py", line 1304, in <module>
    status_code, lastResultsPage, exit_string = main()
  File ".\RedfishServiceValidator.py", line 1239, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1', 'ServiceRoot', expectedJson=jsonData)
  File ".\RedfishServiceValidator.py", line 1089, in validateURITree
    success, linkCounts, linkResults, xlinks, xobj = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 1068, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 1089, in validateURITree
    success, linkCounts, linkResults, xlinks, xobj = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 1068, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 1089, in validateURITree
    success, linkCounts, linkResults, xlinks, xobj = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 1068, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 1079, in validateURITree
    URI, uriName, expectedType, expectedSchema, expectedJson, parent)
  File ".\RedfishServiceValidator.py", line 1022, in validateSingleURI
    .format(sub_item + '.' + key, innerPropType.snamespace))
NameError: name 'sub_item' is not defined`

**Comment by tomasg2012** [comment]
Just a missing keyword like the last one, it just needed to be double checked.  Try `fix-latest` again and I'll ask about hotfixing that in.

**Comment by jbobzin-insyde** [comment]
Retested with latest patch in fix-latest and no crash. And no unexpected validation problems in the report. Congrads - the program successfully validated the worlds largest BIOS page. Total time 12:12
