### ISSUE TITLE
Oem actions incorrectly treated as property

### ISSUE THREAD

**Issue by andy6821** [DMTF/Redfish-Service-Validator#247]
For my implementation, I added an Oem action for the UpdateSevice. With the version 1.1.2 validator, it will complain there is no schema for the Oem action as in the partial log below:

> *** /redfish/v1/UpdateService
ERROR - Something went wrong
Traceback (most recent call last):
  File "/home/piglet/workspace/redfish/Redfish-Service-Validator/traverseService.py", line 870, in __init__
    schemaObj, propOwner, propChild, val, topVersion, customType)
  File "/home/piglet/workspace/redfish/Redfish-Service-Validator/traverseService.py", line 1255, in getPropertyDetails
    propEntry['typeprops'] = createResourceObject(propertyName, 'complex', val, context=schemaObj.context, typename=baseType, isComplex=True)
  File "/home/piglet/workspace/redfish/Redfish-Service-Validator/traverseService.py", line 621, in createResourceObject
    newResource = ResourceObj(name, uri, jsondata, typename, context, parent, isComplex)
  File "/home/piglet/workspace/redfish/Redfish-Service-Validator/traverseService.py", line 750, in __init__
    value_obj = PropItem(propTypeObj.schemaObj, propTypeObj.fulltype, key, val, customType=prop_type)
UnboundLocalError: local variable 'prop_type' referenced before assignment
ERROR - UpdateService.v1_0_0.Actions:Oem :  Could not get details on this property
INFO - 	 Type (UpdateService), GET SUCCESS (time: 0.35761)
ERROR - Actions.Oem: Item is present, but no schema found
INFO - 	  FAIL...
INFO -

**Comment by tomasg2012** [comment]
Would you be able to post the payload responsible, and if you're using the branch `fix-latest`?  I don't think the program handled Oem actions before, and it would help to see.

**Comment by andy6821** [comment]
Using the fix-latest, the no schema error went away, but a different error about patten or type properties missing appeared:

> *** /redfish/v1/UpdateService
INFO - 	 Type (UpdateService), GET SUCCESS (time: 0.191573)
ERROR - Actions.Oem has Redfish.DynamicPropertyPatterns annotation, but Pattern or Type properties missing
WARNING - Actions.Oem.#SMCUpdateService.FWUpdate not defined in schema UpdateService.v1_0_0 (check version, spelling and casing)
INFO - 	  FAIL...
INFO -

**Comment by lindappwu** [comment]
Hi Thomas,
The error comes up even with empty Oem object nested under Actions.

`    "Actions": {
        "#UpdateService.SimpleUpdate": {
            "target": "/redfish/v1/UpdateService/Actions/SimpleUpdate",
            "@Redfish.ActionInfo": "/redfish/v1/UpdateService/SimpleUpdateActionInfo"
        },
        "Oem": {}
    },`

Thanks,
Linda

**Comment by lindappwu** [comment]
Issue fixed by pull #244

**Comment by mraineri** [comment]
Closing per the above comment
