### ISSUE TITLE
Python crash for missing reference in $metadata

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#25]
Python exception in this case -
    Server Page has this "@odata.type": "#Storage.v1_1_1.Storage"
    Highest reference in $metadata is <edmx:Include Namespace="Storage.v1_1_0"/>

This is clearly an implementation error in system. However besides the exception there was no clear hint in the log file. A reasonable message printed in log would save user lots of time during system debug. 

At least that is my recommendation.

Also - the error is not seen when LocalOnlyMode = True.  Appears in this mode the $metadata is bypassed. That is why error slipped past engineer.

Paste of the exception:
` File ".\RedfishServiceValidator.py", line 940, in <module>
    success, counts, results = validateURITree('/redfish/v1', 'ServiceRoot')
  File ".\RedfishServiceValidator.py", line 774, in validateURITree
    linkURI, uriName + ' -> ' + linkName, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 774, in validateURITree
    linkURI, uriName + ' -> ' + linkName, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 774, in validateURITree
    linkURI, uriName + ' -> ' + linkName, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 758, in validateURITree
    validateSingleURI(URI, uriName, expectedType, expectedSchema, expectedJson)
  File ".\RedfishServiceValidator.py", line 838, in validateSingleURI
    success, SchemaSoup = getSchemaDetails( SchemaNamespace, SchemaURI=SchemaURI)
  File ".\RedfishServiceValidator.py", line 124, in getSchemaDetails
    refLink = getReferenceDetails(soup).get(getNamespace(frag))[1]
TypeError: 'NoneType' object is not subscriptable`

Log:
`DEBUG - True, OrderedDict([('@Redfish.Copyright', 'Copyright (c) 2015-2017, Insyde Software Corp. All Rights Reserved.'), ('@odata.context', '/redfish/v1/$metadata#StorageCollection.StorageCollection'), ('@odata.id', '/redfish/v1/Systems/BQWT64900010/Storage'), ('@odata.type', '#StorageCollection.StorageCollection'), ('Name', 'Storage Collection'), ('Members@odata.count', 1), ('Members', [OrderedDict([('@odata.id', '/redfish/v1/Systems/BQWT64900010/Storage/1')])])]), 200
INFO - #StorageCollection.StorageCollection
DEBUG - StorageCollection /redfish/v1/$metadata#StorageCollection.StorageCollection
DEBUG - dont chkauth
DEBUG - callingResourceURI: /redfish/v1/$metadata#StorageCollection.StorageCollection
DEBUG - 200, [200], {'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 26 Feb 2016 23:52:23 GMT', 'Content-Type': 'application/xml', 'X-Frame-Options': 'SAMEORIGIN', 'X-UA-Compatible': 'IE=11', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Server': 'lighttpd/1.4.39'}
`

**Comment by mraineri** [comment]
Fixed with PR #29
