### ISSUE TITLE
Set ServiceMode to True and Validator reports failNoSchema error

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#251]
When I set ServiceMode to True, Validator reports below failNoSchema error:
>ERROR - 2 failNoSchema errors in /redfish/v1/Managers/1/EthernetInterfaces/ToHost/

When I only change the ServiceMode to False, there is no above error.

Here is payload and logs: [ServiceMode_True.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2169952/ServiceMode_True.txt)

**Comment by tomasg2012** [comment]
Seems it appropriately mentions that IPAddresses not accessible from your Service either locally or stored on the server, but it croaks a bit innappropriately.  Can you confirm that IPAddresses_v1.xml is available on your service, or via a local schema cache?

**Comment by JojoWu19** [comment]
The LocalOnlyMode is set to False and the ServiceMode is set to True in my config.ini. I also do not put these standard schema files in the local (./SchemaFiles/metadata). I can use below curl command to get the correct response of IPAddresses_v1.xml from service and redfish.dmtf.org:
`curl -k -X GET http://redfish.dmtf.org/schemas/v1/IPAddresses_v1.xml`
`curl -k -X GET https://x.x.x.x/redfish/v1/metadata/IPAddresses_v1.xml`

But it will return "301 Moved Permanently" if the command is:
`curl -k -X GET http://x.x.x.x/redfish/v1/metadata/IPAddresses_v1.xml`

**Comment by JojoWu19** [comment]
If I modify the metadata document as below, it will pass but I do not know if that is your expected behavior.
From:
`<edmx:Reference Uri="/redfish/v1/metadata/IPAddresses_v1.xml">`
`<edmx:Include Namespace="IPAddresses"/>`
`<edmx:Include Namespace="IPAddresses.v1_0_6"/>`
`</edmx:Reference>`
To:
`<edmx:Reference Uri="/redfish/v1/metadata/IPAddresses_v1.xml">`
`<edmx:Include Namespace="IPAddresses"/>`
`<edmx:Include Namespace="IPAddresses.v1_0_0"/>`
`<edmx:Include Namespace="IPAddresses.v1_0_6"/>`
`</edmx:Reference>`

**Comment by tomasg2012** [comment]
For the first post, there are aspects of redfish's standard URIs that allow for unsecure http connections, but I'm not sure if metadata such as it is listed above is allowed.  As in, I'm not sure if it can be acquired both via http and https or just one of them.  In the second post, those URIs seem legal, but it depends on how consistent your metadata is laid out, is the rest of your metadata stored this way?  You can force your machine to be tested by DMTF sourced schema by using SchemaPack and LocalOnly

ServiceMode is intended to run entirely within the service's URI range and the client does not attempt to ping any outside servers, which means you must have it on the server and use server URIs, or it will default to your local harddrive copy.  From what I can tell, you have the schema stored locally on harddrive?  Why specifically IPAddresses is the problem I am not sure.

**Comment by JojoWu19** [comment]
Yes, all standard 2018.1 metadata files are under /redfish/v1/metadata/ on the service and service only allows https on this path.

And only a few metadata files are located on the local:
`StorageServiceCollection_v1.xml, StorageSystemCollection_v1.xml, StorageService_v1.xml, HostedStorageServices_v1.xml`
`Org.OData.Measures.V1.xml, Org.OData.Capabilities.V1.xml, Org.OData.Core.V1.xml`
`RedfishExtensions_v1.xml, PhysicalContext_v1.xml, Settings_v1.xml, Privileges_v1.xml`

Does validator just not check metadata document when both LocalOnlyMode and ServiceMode are set to False? Because when the ServiceMode is set to True, validator will look up `<Property Name="IPv4Addresses" Type="Collection(IPAddresses.IPv4Address)" Nullable="false">` but  "IPAddresses.IPv4Address" is `Abstract="true"` and there is no "IPAddresses.v1_0_0" in the metadata document so validator reported "failNoSchema"?

The solution is that I need to put all this class's v1_0_0 namespace in the metadata document, is it right?

**Comment by JojoWu19** [comment]
This issue cannot be found in the last version validator with Schema 2018.1. We could close this.

**Comment by tomasg2012** [comment]
I hesitate to close this simply because it might exist as an incompatibility with older schema, but if the issue arises again, then will refer to this issue.
