### ISSUE TITLE
Set AuthType == 'Session' and it shows "/redfish/v1:  URI could not be acquired: 401"

### ISSUE THREAD

**Issue by Jerryat66** [DMTF/Redfish-Service-Validator#253]
At V1.1.4, I set AuthType == 'Session' and username and password are given
but I get the message "/redfish/v1:  URI could not be acquired: 401"

I traced the code and found that   "def startSession(self)" in rfSession.py never been called.

But test works at V1.0.6 and  def startSession(self, user, password, server, chkCert=True, proxies=None) is called at traverseService.py

**Comment by tomasg2012** [comment]
This is a good candidate for unit testing, checking if this header is appropriately sent given the option is used.  Sorry for the trouble, the command must've been lost and assumed that creating the session automatically started the session.

**Comment by mraineri** [comment]
Fixed in latest PR
