### ISSUE TITLE
Incorrect validation on oem extensions from BIOS attribute entries

### ISSUE THREAD

**Issue by lindappwu** [DMTF/Redfish-Service-Validator#255]
The entire BIOS Attributes Registry is an "OEM" list of name/value pairs (and associated meta-data) for BIOS Attributes. 

ERROR - RegistryEntries.Attributes[0].AdditionalData1 not defined in schema AttributeRegistry.v1_2_0 (check version, spelling and casing)

**Comment by lindappwu** [comment]
"RegistryEntries": {
    "Attributes": [
        {
            "CurrentValue": null,
            "DisplayName": "Embedded NIC 1 Boot",
            ....

            "AdditionalData1":"xxxx"
        },
        {
            "CurrentValue": null,
            "DisplayName": "Embedded NIC 2 Boot",
            ....
            "AdditionalData1":"xxxx"
        }
    ]
}

**Comment by tomasg2012** [comment]
I don't see any evidence in AttributeRegistry_v1.xml that would allow a service to add 'AdditionalData1' to a n entry like this, in the ComplexType `Attributes`.  Am I mistaken?

**Comment by mraineri** [comment]
Closing; the current schema definition doesn't allow additional properties in the individual attribute definitions (only at the root level of the resource). Will likely need to discuss more in the main forum if we need a change to the schema.
