### ISSUE TITLE
HTML Output Very Wide

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#26]
In recent tests I see very wide HTML in log file. Lots of spaces. Wide Columns. More than 3 screens wide.

Anyone else seeing this?

Is there some algorithm for determining the column widths?

**Comment by tomasg2012** [comment]
Huh.  Something must be stretching the page wide, I'll put some formatting to prevent that if necessary.  What likely happened is one of the exception tracebacks printed to the html page is too large.

**Comment by jbobzin-insyde** [comment]
No exception this run.
But some errors due to missing Swordfish in the local metadata directory

**Comment by jbobzin-insyde** [comment]
I added the Swordfish Schema files to the local metadata directory and the wide output problem disappeared.  It seemed the problem was caused by the format of the error thrown by a Schema referenced in Service Root but not present in local directory.

**Comment by jbobzin-insyde** [comment]
moved to different thread
