### ISSUE TITLE
Add "Ignore Protocol version" cmd line / config option

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#261]
To test conformance of an existing implementation against the latest version(s) of the specification, it would be handy to have the tool ignore any checks on RedfishVersion or Service Capabilities. 

For testing of prototypes or other non-released implementations, this allows tests against "1.5" protocol while the Service may report "RedfishVersion" of "1.0".

Default setting of course should be to follow the RedfishVersion reported.

**Comment by mraineri** [comment]
8/16: Would like to make this a priority.
