### ISSUE TITLE
Link to NetworkAdapter/NetworkAdapters check failing

### ISSUE THREAD

**Issue by DileepEx** [DMTF/Redfish-Service-Validator#267]
Error:
Links.NetworkAdapter Link: /redfish/v1/Chassis/CARD_001/NetworkAdapters link to: NetworkAdapter Yes FAIL 
ERROR - Links.NetworkAdapter: Could not get schema file for Entity check
WARNING - No such reference NetworkAdapterCollection in local./SchemaFiles/metadata/NetworkInterface_v1.xml 

As per the redfish schema, NetworkInterface_v1.xml says NetworkAdpater is of type NetworkAdapter.NetworkAdapter not of type NetworkAdapterCollection as follows:

-<NavigationProperty Name="NetworkAdapter" Type="NetworkAdapter.NetworkAdapter" Nullable="false">

As per Schema:
NetworkAdapter should link to NetworkAdapter.NetworkAdapter
NetworkAdapters should link to NetworkAdpaterCollection.NetworkAdpaterCollection
But one of the check seems to be is incorrect.

**Comment by tomasg2012** [comment]
Would you be able to zip and post the associated logs with `--debug_logging`?

**Comment by DileepEx** [comment]
[Bug_267_Debuglog.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2362169/Bug_267_Debuglog.zip)

**Comment by DileepEx** [comment]
@mudaliarh

**Comment by tomasg2012** [comment]
Apologies, I had reviewed this error and it seems that you're linking to a collection of NetworkAdaptors when that particular property is supposed to link to a single NetworkAdaptor.  The error isn't specifically clear, however.

In the HTML report:
Links.NetworkAdapter | Link: /redfish/v1/Chassis/CARD_001/NetworkAdapters | link to: NetworkAdapter | Yes | FAIL

**Comment by mraineri** [comment]
So, the root of the issue is the fact that in the resource "NetworkInterface", the property "NetworkAdapter" is supposed to be pointing to a NetworkAdapter resource, but in this implementation it's pointing to a NetworkAdapterCollection resource. The error message does need work to highlight this, but it's certainly an error condition.

**Comment by DileepEx** [comment]
Thanks for the support. We fixed the link to point to a NetworkAdapter instance, and the validator approves the same.
@tomasg2012 , @mraineri, 
Should I close the bug or keep the Bug open to fix the error message?

**Comment by mraineri** [comment]
Please keep it open; we'd like to make the error message more useful in the future.

**Comment by mraineri** [comment]
Closing; fixed in latest PR
