### ISSUE TITLE
The Tool is reporting wrong DateTime format 

### ISSUE THREAD

**Issue by Ghazibelaam** [DMTF/Redfish-Service-Validator#268]
When this tool is run on /systems/1/bios/, it display an error

ERROR - Settings.v1_0_0.Settings:Time: String '' does not match pattern '.*(Z\|(\+\|-)[0-9][0-9]: [0-9][0-9])' ERROR - 	...: Malformed DateTimeOffset
--
This the time format that it complains about
"Time": "2018-04-10T19:26:55+00:00"  or
"Time": "2018-08-31T16:39:15-05:00"

I don't see anything wrong with this format, is the tool correct? 
https://tools.ietf.org/html/rfc3339

**Comment by billdodd** [comment]
It looks like the pattern is being tested against an empty DateTimeOffset string in this case rather than one of the 2 strings you quoted above, so it is not passing the validation. 

Can you rerun the validation with the --debug_logging option and zip up the resulting logs and attach them here?

**Comment by tomasg2012** [comment]
This does also bring up the problem that the regex string is being escaped when printed.

**Comment by tomasg2012** [comment]
@Ghazibelaam have you any more information about this issue?

**Comment by Ghazibelaam** [comment]
yes, I am running test and get you the log
I am working with d8617ce1acef966d2e0da53d5838e646cc390aa0
because the latest does not run:
C:\Users\belaam\Documents\GitHub\Redfish-Service-Validator>py -3 RedfishServiceValidator.py -c config/config.ini -v
Unsupported payloadmode
Unsupported payloadfilepath
Unsupported logpath
Setting up service...
Session successfully created
Constructing metadata...
getting Schema of $metadata /redfish/v1/$metadata
Should be XML
dont chkauth
Service could not be started: local variable 'payload' referenced before assignment

**Comment by Ghazibelaam** [comment]
@tomasg2012

**Comment by tomasg2012** [comment]
Would you be able to zip the latest using --debug_logging?

**Comment by Ghazibelaam** [comment]
@tomasg2012 the latest with --debug_logging, this is all it spits:
INFO - Setting up service...
INFO - Constructing metadata...
DEBUG - getting Schema of $metadata /redfish/v1/$metadata
DEBUG - Should be XML
DEBUG - dont chkauth
ERROR - Service could not be started: local variable 'payload' referenced before assignment

**Comment by Ghazibelaam** [comment]
@tomasg2012  with the same config file I have no problem running the tool with "d8617ce1acef966d2e0da53d5838e646cc390aa0"

**Comment by tomasg2012** [comment]
Would you be able to try the branch `oem-check-fix` located on this repo?

**Comment by Ghazibelaam** [comment]
@tomasg2012  yes the tool works now thank you

**Comment by Ghazibelaam** [comment]
I am going to close the issue
The info that was giving to me by the tester is wrong as was stated above, it was complaining about an empty string, it should have been null
Thank you
