### ISSUE TITLE
The last validator of master reports exceptionResource errors.

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#271]
The last validator of master reports exceptionResource errors. Below is the debug log:
[ConformanceLog_09_10_2018_145001.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2366074/ConformanceLog_09_10_2018_145001.txt)

**Comment by tomasg2012** [comment]
If you're continuing to use oemcheck then it seems like you must use the `oem-check-fix` branch, until it gets merged proper into the master branch.  This seems pretty important, might have to ask to have it merged ahead of time.

**Comment by JojoWu19** [comment]
Get it. 
If I want setting oemcheck to false, I need to use the `oem-check-fix` branch until the branch is merged back to the master.

**Comment by tomasg2012** [comment]
Closed with 09/13 PR.
