### ISSUE TITLE
The result of setting UriCheck to True is not expected

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#279]
When setting UriCheck to True, validator reports some errors that URI of resources don't conform to schema definition. But there are some expected errors not be reported, for example: `/redfish/v1/Chassis/1/Power/` is wrong and shall be `/redfish/v1/Chassis/1/Power`.

Here is the debug log:
[ConformanceLog_10_02_2018_184720.zip](https://github.com/DMTF/Redfish-Service-Validator/files/2437563/ConformanceLog_10_02_2018_184720.zip)

**Comment by tomasg2012** [comment]
Removed the lines that would strip out trailing slashes for stricter testing.  If you still have problem URIs, you might want to try and see if they're detected now.

**Comment by JojoWu19** [comment]
I will verify at next week and let you know the result, thank you.

**Comment by tomasg2012** [comment]
Ah, seems it was written "re.match" instead "re.fullmatch", so it tests that part of the URI is the regex and not that the full URI is exactly regex.  This would require replacing line 493...

**Comment by tomasg2012** [comment]
Should be fixed with last PR.
