### ISSUE TITLE
Current version requires all referenced schema be present. Should it be more forgiving?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#28]
The service root will reference schema that are not used in a particular implementation. Currently the design of the tool assigns an error to this circumstance.
Example, recent ServiceRoot xml references Swordfish schemas so the program requires access to Swordfish xml locally even in a system that does not supply Swordfish services.

Is this correct?

What is the Redfish rule for local-supplied schema?
  A. Must supply xml for every Schema referenced by any xml?  Since we start with Service Root, in practical terms, this is every xml schema in the Redfish/Swordfish universe.
or
 B. Must supply xml that describes every page that is present and used. Namely, every Schema referenced by odata.type in a real page.

**Comment by tomasg2012** [comment]
Does this tool assign an error?  I think it only throws an error if it needs that schema at any point, but I hadn't seen any interaction with Swordfish schema up until this point.

The tool itself runs on the assumption that a local schema is named after the Namespace of the type provided, such as ServiceRoot.v1_0_0 would grab ServiceRoot_v1.xml.  Ultimately this should be redesigned around the references URIs.

**Comment by jbobzin-insyde** [comment]
It throws an error
`Something went wrong: [Errno 2] No such file or directory: 'metadata/StorageSystemCollection_v1.xml'
innerSoup doesn't exist...? ServiceRoot.v1_1_0`

I'm not sure but I think this is the error that wrecks the HTML columns.

You will see this if you put 2016.3 or 2017.1 redfish schema files into local metadata directory, omit the swordfish schemas,  and set LocalOnlyMode = True 

My question is - Is it even an error to omit the swordfish files if the redfish manager produces no swordfish pages.

After I added the swordfish schema the HTML was normal again.

**Comment by tomasg2012** [comment]
This is an error in getPropertyDetails, seems that it's trying to find ServiceRoot in StorageSystemCollection's xml.  This is an observant error.  I didn't consider the fact that a property might not be supported or exist on the service, but the tool will still attempt to first accumulate info on a property then check that property.  If the service-provided schema is modified to remove properties it doesn't support, then this would not happen I assume.

I would imagine this SHOULD be B, but I could ask for advice.

**Comment by jbobzin-insyde** [comment]
Actually I would guess slightly different cause - program is processing ServiceRoot xml and the algorithm tries to find xml for every type listed in ServiceRoot.

I would suggest a result similar to the following would be optimal:
1) While parsing xml, the program discovers the xml for a referenced type is not found in schema store (could be local from service rather than from dmtf.org)
2) A warning is logged - "Warning: Referenced Type <xxxx.xxxx> Not Available In Schema Store". (And the HTML is not wrecked.)
3) If later when reading the json, an odata.type references a type with no XML a fatal error is printed.
 "Critical: No XML available in Schema Store for type <xxxx.xxxx> at </redfish/v1/nnnn/mmm/iii>

**Comment by tomasg2012** [comment]
Did this problem change with the new version?

**Comment by jbobzin-insyde** [comment]
Traveling for a few days.  Will check later this week. Also Waiting for patch from my guys.

Sent from my Windows Phone
________________________________

**Comment by tomasg2012** [comment]
Ok, thank you.  I recall that you suggested a method to test this myself, I will give that a shot.

**Comment by jbobzin-insyde** [comment]
Running local only, still prints lots of confusing errors in this case - when the XML of a JSON page is processed, if that XML references a XML type that is not present, even if the actual JSON of the page being processed does not reference contain a property needing the missing XML.
To duplicate, I unzipped 2016.3 release metadata into the local directory (without swordfish) and processed a device with ServiceRoot.v1_1_1.  Other than the confusing errors and traceback the tool is still usable. It correctly assigns DNE/SkipOptional to the properties with the missing types. So a cleanup of the print is all that is suggested.

`ERROR - Something went wrong
Traceback (most recent call last):
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 174, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + Alias + suffix, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/metadata.xml'
ERROR - Something went wrong
Traceback (most recent call last):
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 174, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + Alias + suffix, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/StorageSystemCollection_v1.xml'
ERROR - innerSoup doesn't exist...? ServiceRoot.v1_1_0
ERROR - Something went wrong
Traceback (most recent call last):
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 174, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + Alias + suffix, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/StorageServiceCollection_v1.xml'
ERROR - innerSoup doesn't exist...? ServiceRoot.v1_1_0`

**Comment by tomasg2012** [comment]
Sounds good!  It would just require a much nicer exception catch then
currently used, it's just saying there's no such file and returning an
empty object.
