### ISSUE TITLE
Service Validator may be sending wrong header.

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#280]
RedDrum-Redfish frontend gives no auth header 401
on requests.
redfishtool sends header:
'**Authorization': 'Basic**
Redfish-Service-Validator sends header:
'**WWW-Authenticate': 'Basic'**

I kinda wonder why not use redfish transport in test tools.

**Comment by tomasg2012** [comment]
At the time of developing the tool, it was a consideration to not use redfishtool for everything to avoid making one tool dominate the API, so to speak.  As in, we're developing for redfish API not redfishtool API.

However, shared codebase has never been an issue so I'll talk about it.

**Comment by PhillipWatts1012** [comment]
No, I would never use redfishtool directly in a test.

I meant the redfish transport module.


________________________________

**Comment by tomasg2012** [comment]
I meant it as "we, as developers, don't want to use a single library for all redfish development of tools".

Talking to Mike about the Authorization thing in the spec.

**Comment by tomasg2012** [comment]
Try applying the following diffpatch to your tool and see what appears, or manually add the lines.  No `--debug_logging` required, so it will be easier to see what it's sending.  This reveals what basic credentials you are using, which _reveals your password,_ so remove the line or information if you post if necessary.

From my end, the tool does send the proper Authorization.
```
diff --git a/traverseService.py b/traverseService.py
index 7e8c69a..9cf1141 100644
--- a/traverseService.py
+++ b/traverseService.py
@@ -410,8 +410,10 @@ class rfService():
             expCode = [200]
             elapsed = response.elapsed.total_seconds()
             statusCode = response.status_code
-            traverseLogger.debug('{}, {}, {},\nTIME ELAPSED: {}'.format(statusCode,
+            traverseLogger.info('{}, {}, {},\nTIME ELAPSED: {}'.format(statusCode,
                                  expCode, response.headers, elapsed))
+            traverseLogger.info('my basic auth: {}'.format(auth))
+            traverseLogger.info('request headers: {}'.format(response.request.headers))
             if statusCode in expCode:
                 contenttype = response.headers.get('content-type')
                 if contenttype is None:
```

**Comment by PhillipWatts1012** [comment]
I tried it with this:
curl -u root:password http://localhost/redfish/v1/Systems -vvvv
 Connected to localhost (::1) port 80 (#0)
* Server auth using Basic with user 'root'
> GET /redfish/v1/Systems HTTP/1.1
> **Authorization: Basic cm9vdDpwYXNzd29yZA==**   <---
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: */*
> 
< HTTP/1.1 200 OK

**Comment by billdodd** [comment]
Hi, Phillip.

The Service Validator does send a proper Authorization header for basic auth (and should never send a WWW-Authenticate header, which is a response header).

So we're trying to figure out exactly what is happening in your scenario. My suspicion is that for some reason the tool is not sending authentication at all and the service is responding with the `WWW-Authenticate: Basic` header in the 401 response.

Potential config problems that could cause this result:

- If you are using the config.ini file and have specified the `UserName` and `Password` params in the file, also check to be sure the `AuthType` param is set to `Basic`.
- Or likewise, if you are using command-line args `-u USER` and `-p PASSWORD`, be sure you also have `--authtype Basic`

If you have the AuthType set to Basic and are still seeing the problem, it would help us see what is going on if you could run the tool with the patch Tomas suggested above and then zip up the logs and attach them here.

**Comment by PhillipWatts1012** [comment]
problem solved.  I did not see the --forceauth option.
