### ISSUE TITLE
Validator can't check usessl option through command line.

### ISSUE THREAD

**Issue by hyche** [DMTF/Redfish-Service-Validator#283]
Hi,

I couldn't run the tool through the command line with usessl=True.
`python3 RedfishServiceValidator.py --nochkcert --authtype=Basic -i xx.xx.xx.xx:pppp -u yyyy -p zzzz`
Here is the log
```
First run suggested to create and own local schema files, please download manually or use --schema_pack latest
Alternatively, use the option --prefer_online to skip local schema file checks
Redfish Service Validator, version 1.2.0
Setting up service...
Constructing metadata...
Service could not be started: 'usessl'
```

But I am able to run it with config file option, 
`python3 RedfishServiceValidator.py -c config.txt`
[config.txt](https://github.com/DMTF/Redfish-Service-Validator/files/2463639/config.txt)

Are they different ?

**Comment by tomasg2012** [comment]
Appears the `defaultconfig` in traverseService.py does not include 'usessl', which trips up resource calls.  A simple patch would be to add 'usessl' to that dictionary.  Otherwise, will be fixed.

**Comment by tomasg2012** [comment]
Closing; fixed in latest PR
