### ISSUE TITLE
Undefined variable ?

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#284]
Help with this?   I got a bunch of these, all to do with EthernetInterfaces

*** /redfish/v1/Systems/Rack1-Block1-Sled3-Node1/EthernetInterfaces/NIC.Embedded.1-1-1
EthernetInterface.v1_0_0.EthernetInterface:VLAN :  Could not get details on this property (local variable 'uri' referenced before assignment)
     Type (#EthernetInterface.v1_3_0.EthernetInterface), GET SUCCESS (time: 0.004542)
      FAIL...

uri (lowercase) is not in the resource or the schema. That error could happen anywhere
in the code so I couldn't find it

**Comment by tomasg2012** [comment]
This is a tool Exception, not a user error.  please post a --debug_logging if you're using the latest version

**Comment by PhillipWatts1012** [comment]
The error goes away with that addition.

**Comment by mraineri** [comment]
Closing; fixed in latest PR
