### ISSUE TITLE
Empty string?

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#285]
We (Paul Vancil) disagree. An empty string is a string.
Null has different meaning than "".

*** /redfish/v1/Chassis/Rack1-PowerBay1
     Type (#Chassis.v1_4_0.Chassis), GET SUCCESS (time: 0.004742)
SerialNumber: Empty string found - Services should omit properties if not supported
AssetTag: Empty string found - Services should omit properties if not supported
Links.CooledBy[0]: Could not get resource for Entity check
      FAIL...

**Comment by mraineri** [comment]
While an empty string is a string, we've had discussions in the forum that using an empty string for something unknown is bad behavior. For properties that are not settable by clients, we'd normally expect a non-empty string, or null if the service is unable to determine the value. This behavior was requested in issue #193

**Comment by mraineri** [comment]
The actually failure in your report is due to the fact that the "CooledBy" reference is not resolving properly. The empty string is just a warning message.

**Comment by pwvancil** [comment]
The main issue is AssetTag.   Customers can set this property and in fact at times have set it to and empty string.   So it seems difficult to prevent a customer from setting it and this getting an error.
If an empty string is not valid I think we need to make that invalid in schema.
unsettable properties are a different argument eg serialNumber.

**Comment by mraineri** [comment]
AssetTag should not be flagged as an issue since it's a writable property; the check for empty strings should only be done on read only properties (like serial number).

**Comment by pwvancil** [comment]
very good.  I agree!
