### ISSUE TITLE
DMTF/Redfish-Service-Conformance-Check --  Assertion Failures

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Validator#288]
Assertion: 6.4.2.3
~ GET: /redfish/v1/ HTTP status 200:OK with request header: OData-Version and incorrect value: 3.0 passed, which is an unexpected behavior
Assertion Description: b'\nOData-Version\nYes\n4.0\nServices shall reject requests which specify an unsupported OData version.\n'
<--- Assertion 6.4.2.3: FAIL

**NOTE**:  The client sent odata-version 3.0.  Redfish should have responded with a 400 bad request
-------------------------------------------------
---> Assertion: 6.4.26
status from POST is 405
~ POST:/redfish/v1/SessionService/Sessions/Members failed : HTTP status 405:Method Not Allowed, Expected statuses: [200, 201, 202, 204]
Assertion Description: b'Submitting a POST request to a resource representing a collection is equivalent to submitting the same request to the Members property of that resource. Services that support adding members to a collection shall support both forms.'
<--- Assertion 6.4.26: FAIL
**NOTE**: Sessions/Members should allow POST

**Comment by mraineri** [comment]
I don't think there's an issue with the tool.

For the first assertion, the service responded with "200 OK" when the OData-Version header contained "3.0"; that looks like an appropriate failure.

For the second assertion, the service responded with "405 Method Not Allowed" when the client performed a POST on /redfish/v1/SessionService/Sessions/Members; that also looks like an appropriate failure.

**Comment by mraineri** [comment]
And these are assertions from the Service Conformance Check; this repo is for the Service Validator (a different tool)

**Comment by PhillipWatts1012** [comment]
Dang it. Posted to the wrong repo.  Closing
