### ISSUE TITLE
Schema validation for only a select  few properties 

### ISSUE THREAD

**Issue by pradeep-bose** [DMTF/Redfish-Service-Validator#295]
Hi I would like to validate Schema for only for Memory , MemoryChunks and MemoryDomain. 
So i tried to run in Local mode in the config file and provided only the xml files related to Memory. 
The test does not complete and throws errors that the other xml schemas are not available . 
How do i run test specific for Memory alone ? 
In the report the failure is not specific for what property in memory has failed , instead see generic messages as below  
1 failProp errors in /redfish/v1/Systems/1/Memory/proc2dimm6/
1 failComplex errors in /redfish/v1/Systems/1/Memory/proc2dimm8/

**Comment by pradeep-bose** [comment]
@tomasg2012 Its perfect to generate report for targeted properties alone. Its a good a comprehensive report.
but @mraineri I would be doing beta testing some newer schema of Memory v1_7_0 JSON schema which i have only the JSON-schema not the xml file CSDL file. 
Hence i would be using https://github.com/DMTF/Redfish-JsonSchema-ResponseValidator
with my  1.7 Memory JSON schema as input. 
As i believe this tool works with the CSDL xml file as input ?

**Comment by mraineri** [comment]
@pradeep-bose unless you belong to a member company of the Redfish Forum, you should not have access to Memory 1.7.0 (in either CSDL or JSON Schema forms) since we have not approved its release to the public.

**Comment by jautor** [comment]
@pradeep-bose if you are working on un-released (and therefore unapproved and DMTF Confidential) material, please work with your DMTF representatives to have questions or issues raised with the Redfish Forum.

**Comment by pradeep-bose** [comment]
Thanks guys for the help
