### ISSUE TITLE
Redfish 2018.3 schemas cause false positive errors on deprecated properties

### ISSUE THREAD

**Issue by edtanous** [DMTF/Redfish-Service-Validator#300]
The latest versions of the schema pack for redfish contains changes to previous schemas, marking some properties as deprecated.  One example of this is in the memory schema.  This causes the following errors to be flagged for implementations that implement the 2018.3 schemas.
```
ERROR - Memory.v1_0_0.Memory:FunctionClasses :  Could not get details on this property ('Term')
ERROR - Memory.v1_0_0.Memory:VendorID :  Could not get details on this property ('Term')
ERROR - Memory.v1_0_0.Memory:DeviceID :  Could not get details on this property ('Term')
ERROR - Memory.v1_0_0.Memory:SubsystemVendorID :  Could not get details on this property ('Term')
ERROR - Memory.v1_0_0.Memory:SubsystemDeviceID :  Could not get details on this property ('Term')
```

For reference, this is an example of a failing payload being returned from OpenBMC:

``` json
{
    "@odata.context": "/redfish/v1/$metadata#Memory.Memory",
    "@odata.id": "/redfish/v1/Systems/system/Memory/dimm17",
    "@odata.type": "#Memory.v1_6_0.Memory",
    "Id": "dimm17",
    "Name": "DIMM Slot",
    "Status": {
        "Health": "OK",
        "State": "Absent"
    }
}
```

To my knowledge, the payload looks properly formed, and correct per the standard.

There is also a similar failure on the Fans schema.
ERROR - Thermal.v1_0_0.Fan:FanName :  Could not get details on this property ('Term')

**Comment by lindappwu** [comment]
We encountered the same issue with 2018.3 schemas.

**Comment by tomasg2012** [comment]
Will be fixing this momentarily, seems the new type of tagging for deprecation might disagree with the program.

**Comment by mraineri** [comment]
PR with the fix has been merged
