### ISSUE TITLE
Processors error - Could not get resource for Entity check

### ISSUE THREAD

**Issue by DileepEx** [DMTF/Redfish-Service-Validator#303]
We are seeing the following issue, by the validator.

Processors | Link: /redfish/v1/StorageSystems/FPGA_000/Processors | link to: ProcessorCollection | Yes | FAIL
-- | -- | -- | -- | --

ERROR - Processors: Could not get resource for Entity check

Is this a mandatory implementation? What is the meaning of the error?

**Comment by mraineri** [comment]
I believe it means you provided the link "/redfish/v1/StorageSystems/FPGA_000/Processors" inside a resource, but when the validator went to read the link, it got an error.

**Comment by DileepEx** [comment]
For the sake of passing the compliance, I added implementation to return processor count 0.
GET Response:
{
  "@odata.context": "/redfish/v1/$metadata#ProcessorCollection.ProcessorCollection",
  "@odata.id": "/redfish/v1/StorageSystems/FPGA_000/Processors",
  "@odata.type": "#ProcessorCollection.ProcessorCollection",
  "Members": [  ],
  "Members@odata.count": 0,
  "Name": "Processor Collection"
}

But, it gives following compliance issue.

/redfish/v1/StorageSystems/FPGA_000/Processors (response time: )
--
/redfish/v1/StorageSystems/FPGA_000/Processors(response time: )Show ResultsContext: File Origin: NoneResource Type: GET FailureexceptionResource: 1 | /redfish/v1/StorageSystems/FPGA_000/Processors(response time: )Show Results | Context: File Origin: NoneResource Type: | GET Failure | exceptionResource: 1
/redfish/v1/StorageSystems/FPGA_000/Processors(response time: )Show Results | Context: File Origin: NoneResource Type: | GET Failure | exceptionResource: 1
Property NameValueTypeExistsResultMembers@odata.count0stringYesPASS@odata.id/redfish/v1/StorageSystems/FPGA_000/ProcessorsstringYesPASS@odata.context/redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionstringYesPASS@odata.type#ProcessorCollection.ProcessorCollectionstringYesPASSERROR - Could not find item in $metadata ProcessorCollectionERROR - ResourceObject creation: No schema XML for None #ProcessorCollection.ProcessorCollection /redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionERROR - Traceback (most recent call last):  File "RedfishServiceValidator.py", line 960, in validateSingleURI    uriName, URI, expectedJson, expectedType, expectedSchema, parent)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 427, in createResourceObject    newResource = ResourceObj(name, uri, jsondata, typename, context, parent, isComplex)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 513, in __init__    raise ValueErrorValueError | Property NameValueTypeExistsResultMembers@odata.count0stringYesPASS@odata.id/redfish/v1/StorageSystems/FPGA_000/ProcessorsstringYesPASS@odata.context/redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionstringYesPASS@odata.type#ProcessorCollection.ProcessorCollectionstringYesPASS | Members@odata.count | 0 | string | Yes | PASS | @odata.id | /redfish/v1/StorageSystems/FPGA_000/Processors | string | Yes | PASS | @odata.context | /redfish/v1/$metadata#ProcessorCollection.ProcessorCollection | string | Yes | PASS | @odata.type | #ProcessorCollection.ProcessorCollection | string | Yes | PASS | ERROR - Could not find item in $metadata ProcessorCollectionERROR - ResourceObject creation: No schema XML for None #ProcessorCollection.ProcessorCollection /redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionERROR - Traceback (most recent call last):  File "RedfishServiceValidator.py", line 960, in validateSingleURI    uriName, URI, expectedJson, expectedType, expectedSchema, parent)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 427, in createResourceObject    newResource = ResourceObj(name, uri, jsondata, typename, context, parent, isComplex)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 513, in __init__    raise ValueErrorValueError
Property NameValueTypeExistsResultMembers@odata.count0stringYesPASS@odata.id/redfish/v1/StorageSystems/FPGA_000/ProcessorsstringYesPASS@odata.context/redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionstringYesPASS@odata.type#ProcessorCollection.ProcessorCollectionstringYesPASS | Members@odata.count | 0 | string | Yes | PASS | @odata.id | /redfish/v1/StorageSystems/FPGA_000/Processors | string | Yes | PASS | @odata.context | /redfish/v1/$metadata#ProcessorCollection.ProcessorCollection | string | Yes | PASS | @odata.type | #ProcessorCollection.ProcessorCollection | string | Yes | PASS

Members@odata.count | 0 | string | Yes | PASS
@odata.id | /redfish/v1/StorageSystems/FPGA_000/Processors | string | Yes | PASS
@odata.context | /redfish/v1/$metadata#ProcessorCollection.ProcessorCollection | string | Yes | PASS
@odata.type | #ProcessorCollection.ProcessorCollection | string | Yes | PASS
ERROR - Could not find item in $metadata ProcessorCollectionERROR - ResourceObject creation: No schema XML for None #ProcessorCollection.ProcessorCollection /redfish/v1/$metadata#ProcessorCollection.ProcessorCollectionERROR - Traceback (most recent call last):  File "RedfishServiceValidator.py", line 960, in validateSingleURI    uriName, URI, expectedJson, expectedType, expectedSchema, parent)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 427, in createResourceObject    newResource = ResourceObj(name, uri, jsondata, typename, context, parent, isComplex)  File "/root/dileep/Redfish-Service-Validator/traverseService.py", line 513, in __init__    raise ValueErrorValueError

**Comment by billdodd** [comment]
I think the error is saying that you do not have a reference to the ProcessorCollection schema in your /redfish/v1/$metadata. You probably need to add an entry like this to the $metadata:

```
  <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/ProcessorCollection_v1.xml">
    <edmx:Include Namespace="ProcessorCollection"/>
  </edmx:Reference>
```

**Comment by mraineri** [comment]
@DileepEx if having a ProcessorCollection doesn't make sense for your implementation, it might be better to simply not report the "Processors" property.

**Comment by DileepEx** [comment]
Thanks for your suggestions. The issue with $metadata was due to my validator configuration. When I fixed it, validator approves the same. Closing the bug.
