### ISSUE TITLE
KeyError: 'OriginOfCondition.OriginOfCondition'

### ISSUE THREAD

**Issue by damon3000** [DMTF/Redfish-Service-Validator#305]
I use 2016.3 schema files to run "python3 RedfishServiceValidator.py -c config/config.ini --debug_logging" the command, got the error message as following:

*** /redfish/v1/JsonSchemas/Configurations.v1_0_0
@odata.etag @odata item not checked: W/"1694301301"
         Type (#JsonSchemaFile.v1_0_3.JsonSchemaFile), GET SUCCESS (time: 0.401031)
         PASS
Referenced URI acquired ends in slash: /redfish/v1/
**Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1442, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 1390, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "RedfishServiceValidator.py", line 1228, in validateURITree
    ref_link.uri = ''.join(links[linkName].uri.split('/')[:-1])
KeyError: 'OriginOfCondition.OriginOfCondition'**

But I use 2018.2 schema files , no this issue.

**Comment by damon3000** [comment]
Sorry, they are metadata files which format is *.xml, not *.json.

**Comment by tomasg2012** [comment]
Seems that on line 1228 in the code file, it uses links[linkName] rather than refLinks[linkName].  This is a tool issue.

**Comment by damon3000** [comment]
Modify line 1228 from links[linkName] to refLinks[linkName] and then run the test, got the result:

Referenced URI acquired ends in slash: /redfish/v1/
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1442, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 1390, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "RedfishServiceValidator.py", line 1228, in validateURITree
    ref_link.uri = ''.join(refLinks[linkName].uri.split('/')[:-1])
AttributeError: 'tuple' object has no attribute 'uri'

**Comment by tomasg2012** [comment]
Would you be able to post the payload associated with this issue?

**Comment by tomasg2012** [comment]
I overlooked how that piece of code works, if you are able to test with the branch `reflink_fix` it should fix it.

**Comment by damon3000** [comment]
I test the reflink_fix and got the result:
Referenced URI acquired ends in slash: /redfish/v1/
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1442, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 1390, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "RedfishServiceValidator.py", line 1228, in validateURITree
    ref_link.uri = ''.join(ref_link.uri.split('/')[:-1])
AttributeError: can't set attribute

Thanks very much for doing a favor.

**Comment by tomasg2012** [comment]
Sorry, this is harder than expected to try and pinpoint the issue when I can't seem to replicate the problem.  Is there an "OriginOfCondition" annotation somewhere on the system pointing to the root?

I uploaded another attempt at a fix to the same repository.

**Comment by damon3000** [comment]
This version can fix the issue. Thanks.
