### ISSUE TITLE
Regex for odata.context does not capture certain URIs

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Service-Validator#308]
The following example appears to be valid but is not correct to the tool:

`/redfish/v1/$metadata#Registries/Members/$entity`

**Comment by mraineri** [comment]
Would like to harden the check to be in this form:
`/redfish/v1/$metadata#ComputerSystem.ComputerSystem`

The `ComputerSystem.ComputerSystem` would need to be determined based on the `@odata.type` value.

**Comment by mraineri** [comment]
Given the lack of usage of `@odata.context` by Redfish clients, and the fact it's now optional, maybe we skip verification of `@odata.context` altogether.

**Comment by mraineri** [comment]
Changes made to reduce the severity since `@odata.context` is not required anymore
