### ISSUE TITLE
Crashes on links that lack an @odata.id property

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#309]
Links that have a malformed/missing odata.id property are assumed to have one, but the resulting property value causes a crash when the string uri.spilt occurs in one of two places  (line 1202 and 1222).  

For example, the following invalid links will cause the crash (missing "o"):
```
    "Links": {
        "Role": {
            "@data.id": "/redfish/v1/AccountService/Roles/manager"
        }
    }
```

and (capital 'I')

```
    "Links": {
        "Role": {
            "@odata.Id": "/redfish/v1/AccountService/Roles/manager"
        }
    }
```

**Comment by jautor** [comment]
Crash is (same fault, may not match data from example above):
```
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 1442, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 1390, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1/', '
ServiceRoot', expectedJson=jsonData)
  File "RedfishServiceValidator.py", line 1222, in validateURITree
    if ref_link.uri.split('#')[0].endswith('/'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jautor** [comment]
more information on this - the crash occurs when the tool is attempting to report an error about an invalid link (in the example above, there is no Role called "manager").   If that "@data.id" (no O) pointed to a valid URI for a Role, the crash doesn't occur.

**Comment by mraineri** [comment]
Fixed in latest PR
