### ISSUE TITLE
Returning resource error for Get operation on telemetry uri from conformance tool

### ISSUE THREAD

**Issue by Badriprasadv** [DMTF/Redfish-Service-Validator#317]

**Comment by jautor** [comment]
@billdodd  Agree that this appears to be an implementation issue, not a tool issue.
However, there is at least one error message here that should be improved:

"ERROR - MetricReport: Could not get resource for Entity check"  

would be much more logical to read as:

"ERROR - MetricReport: GET of resource at URI "/redfish/v1/<uri...>" returned HTTP 404.  Check URI.
