### ISSUE TITLE
Redfish Complaint Failing For Complex Type Action Validation

### ISSUE THREAD

**Issue by MANIKUME24** [DMTF/Redfish-Service-Validator#322]
RedfishServiceValidator.py file at line 57  `actionsDict = {act.name: (val.get(act.name, 'n/a'), act.actTag) for act in parentTypeObj.getActions()}` is failing when validating Action Complex Type. Getting below error

CompositionService.v1_0_0.CompositionService:Actions: Could not finish check on this property (generator raised StopIteration)
Actions not defined in schema CompositionService.v1_1_1 (check version, spelling and casing)
          FAIL...

**Comment by mraineri** [comment]
The resource response in question looks like this:
```
{
    "@odata.context": "/redfish/v1/$metadata#CompositionService.v1_0_0.CompositionService",
    "@odata.id": "/redfish/v1/CompositionService",
    "@odata.type": "#CompositionService.v1_0_0.CompositionService",
    "Actions": {
        "Oem": {}
    },
    "Description": "Composition Service",
    "Id": "CompositionService",
    "Name": "Composition Service",
    "ResourceBlocks": {
        "@odata.id": "/redfish/v1/CompositionService/ResourceBlocks"
    },
    "ResourceZones": {
        "@odata.id": "/redfish/v1/CompositionService/ResourceZones"
    },
    "ServiceEnabled": true,
    "Status": {
        "Health": "OK",
        "HealthRollup": "OK",
        "State": "Enabled"
    }
} 
```

Which to me looks valid based on the schema. It's probably not intuitive to have a single, empty "Oem" property inside of "Actions", but it is legal based on the schema rules.

**Comment by tomasg2012** [comment]
Weird, I was under the impression that StopIteration was supposed to be caught in for loops like this.  Let me test this and fix.

**Comment by tomasg2012** [comment]
If possible, try this again with `generator-fix`.  I cannot seem to replicate the issue so easily, which might make it some sort of environment running difference.

**Comment by billdodd** [comment]
Probably a Python 3.7 thing:

https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

**Comment by mraineri** [comment]
@MANIKUME24 would you be able to try out the latest version of the tool? Tomas pushed a change yesterday that should resolve the issue.

**Comment by MANIKUME24** [comment]
@mraineri The changes are working fine. Thanks a lot for such a quick turn around.

**Comment by mraineri** [comment]
Closing; fixed in latest PR
