### ISSUE TITLE
odata annotations incorrectly required within Registry documents

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#325]
Message registries and other Registry documents are not required to have the Resource-required properties (odata.id, odata.context, odata.etag, etc.)  - although odata.type is used to show the schema type/version within the file.

This comes from the default handling for all Redfish resources, but at this level, these are really "hosted JSON documents".  It's great that the tool is validating the Registry contents, but need to make exceptions for non-resource documents.

**Comment by mraineri** [comment]
Need to have exception case for MessageRegistry, PrivilegeRegistry, and AttributeRegistry to not enforce the presence of `@odata.id`

**Comment by tomasg2012** [comment]
Curious is the following two images, is different behavior for if A) traversed thru the entire service or B) just a single payload entry

![image](https://user-images.githubusercontent.com/5571676/61090658-065c1300-a405-11e9-8ab6-df87ac7c551e.png)
![image](https://user-images.githubusercontent.com/5571676/61090684-183db600-a405-11e9-8781-c3383d58a742.png)

Must not be detecting that it's a registry file if using a `--payload Single`, it may be doing the same in other instances

**Comment by mraineri** [comment]
@jautor do you have a sample log from when you originally ran into this issue? I'm wondering if because of the method of getting to registries requires going through the "Uri" property, which is handled specially, we won't actually be checking `@odata.id`. Maybe the only issue was with `@odata.context`, which has been removed from checks.

**Comment by mraineri** [comment]
@jautor were you able to follow up with the above request?

**Comment by jautor** [comment]
Not sure if this cleared up via other fixes, or if other service bugs were exposing this.  Suggest closing and if some case comes up we can reopen.

**Comment by mraineri** [comment]
Sounds good to me
