### ISSUE TITLE
Fails to detect schema reference errors in Oem Actions

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#326]
Oem Action sample in spec
{
"Actions": {
"Oem": {
"#Contoso.Ping": {
"target":"/redfish/v1/Systems/1/Actions/Oem/Contoso.Ping"}}},
}

In this example Contoso must be a Schema namespace (defined in a file loaded by $metadata) and Ping must be an Action name in that namespace. Missspelling of the namespace leading to no namespace match is not flagged as an error currently. The Action name is also not matched to the schema. In my tests oemcheck was true.

Once complication - the xml file defining Contoso is loaded from local schema store and not from dmtf over web.

**Comment by mraineri** [comment]
Closing; should be addressed by a PR that was tagged for another (duplicate) issue.
