### ISSUE TITLE
Allow for special handling of OriginOfCondition's missing content

### ISSUE THREAD

**Issue by vikingrobert** [DMTF/Redfish-Service-Validator#333]
In LogEntry - Links: Using OriginOfCondition it is possible to display the URI of the resource that caused the log. 
If the resource has since been deleted after the log entry was created then the validator fails citing a 404 error on that missing resource.

**Comment by tomasg2012** [comment]
Would like to know, is it an ERROR on the Property itself i.e `OriginOfCondition` or the Resource itself i.e. `exceptionResource` (or something similar to that)
