### ISSUE TITLE
Type RAIDType not found under namespace Volume

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Service-Validator#335]
For reference, see also https://github.com/DMTF/Redfish/issues/3248

During the recent APTS Plugest, the service validator reported this error on three of the target Redfish services:

> ERROR - Type RAIDType not found under namespace Volume in schema localFile:./SchemaFiles/metadata/Volume_v1.xml

I'm not sure if this is a tool error, user error or service error.

But here's what I've seen and suspect:

- On the 3 services that got this error, the `$metadata` file referenced a `Volume_v1.xml` file hosted by the service.
- I scraped each service using the Mockup-Creator. And looking at the `Volume_v1.xml` files hosted on those services, none of them included the `RAIDType` property.
- Based on the above, I think the errors are service errors: the `Volume_v1.xml` schema hosted by the services should include the RAIDType property. Or the services should  point to the `Volume_v1.xml` file hosted at http://redfish.dmtf.org/schemas/swordfish/v1/Volume_v1.xml

Here are the `$metadata` `Volume_v1.xml` schema references from those three services

> <edmx:Reference Uri="/redfish/v1/Schemas/Volume_v1.xml">

> <edmx:Reference Uri="/redfish/v1/schema/Volume_v1.xml">

> <edmx:Reference Uri="/redfish/v1/metadata/Volume_v1.xml">

**Comment by mraineri** [comment]
Since a service is using a newer version of "Storage" with new definitions that reference the SNIA version of "Volume", I would think it should be the responsibility of the service provider to update their local copy of Volume as needed (since they're already updating their implementation of Storage to reference new properties).

**Comment by billdodd** [comment]
@jbobzin-insyde Please review this issue. I think this explains the Service-Validator error that we discussed at the Plugfest.

**Comment by jbobzin-insyde** [comment]
Yes, this issue is open in our internal Redmine. An engineer is assigned but %done is at 0 when checked today. Thanks for the reminder.

**Comment by mraineri** [comment]
@billdodd @jbobzin-insyde should we close out this issue since this was a service-side issue?

**Comment by jbobzin-insyde** [comment]
yes

**Comment by mraineri** [comment]
Thanks; closing
