### ISSUE TITLE
Compliance error on implemented mandatory properties of Get Log Entry 

### ISSUE THREAD

**Issue by DileepEx** [DMTF/Redfish-Service-Validator#336]
Experts,
We are using v1.2.8.
Please check the error and our implementation and advise if we are missing something.

**Compliance Error:**
VERBO - ServiceRoot -> StorageSystems.StorageSystems -> Members.ComputerSystem#0 -> LogServices.LogServices -> Members.LogService#0, LogService.v1_1_0, LogService
VERBO - @odata.context                                          PASS
VERBO - @odata.id                                               PASS
VERBO - @odata.type                                             PASS
VERBO - Description                                             PASS
VERBO - Entries                                                 FAIL
VERBO - Id                                                      PASS
VERBO - MaxNumberOfRecords                                      PASS
VERBO - Name                                                    PASS
VERBO - Oem                                                  complex
VERBO - OverWritePolicy                                         PASS
VERBO - ServiceEnabled                                      Optional
VERBO - DateTime                                            Optional
VERBO - DateTimeLocalOffset                                 Optional
VERBO - Actions                                             Optional
VERBO - Status                                              Optional
VERBO - Oem.Attala                                              FAIL
INFO - 	  FAIL...
VERBO - LogService.v1_1_0.LogService, Counter({'pass': 6, 'skipOptional': 5, 'failComplex': 1, 'passGet': 1, 'failProp': 1, 'err.LogEntryCollection.LogEntryCollection': 1})

**Get Log Entry response from our implementation:**
{
  "@odata.context": "/redfish/v1/$metadata#LogEntry.LogEntry",
  "@odata.id": "/redfish/v1/StorageSystems/FPGA_000/LogServices/TGT_1970_01_01_00_22_50_480102/Entries/TGT_1970_01_01_00_22_44_980052",
  "@odata.type": "#LogEntry.v1_0_0.LogEntry",
  "Description": "Information of Log entry",
  "EntryType": "Event",
  "EventTimestamp": "1970-01-01 00:22:44.980052 T 00:00",
  "EventType": "TBD",
  "Id": "TGT_1970_01_01_00_22_44_980052",
  "Message": "NVMe AER sent",
  "Name": "Log Entry",
  "Severity": "info"
}

**Comment by mraineri** [comment]
What about the LogService resource? That's where the error is from.

**Comment by DileepEx** [comment]
GET /redfish/v1/StorageSystems/{fpga_num}/LogServices/{sel} 
Response for a particular  SEL.

{
  "@odata.context": "/redfish/v1/$metadata#LogService.LogService",
  "@odata.id": "/redfish/v1/StorageSystems/FPGA_000/LogServices/TGT_1970_01_01_00_22_50_480102",
  "@odata.type": "#LogService.v1_0_0.LogService",
  "Description": "Information about Log service",
  "Entries": {
    "@odata.id": "/redfish/v1/StorageSystems/FPGA_000/LogServices/TGT_1970_01_01_00_22_50_480102/Entries"
  },
  "Id": "TGT_1970_01_01_00_22_50_480102",
  "MaxNumberOfRecords": 15,
  "Name": "Log Service",
  "Oem": {
    "Attala": {
      "Entries": {
        "@odata.id": "/redfish/v1/StorageSystems/FPGA_000/LogServices/TGT_1970_01_01_00_22_50_480102/Events"
      }
    }
  },
  "OverWritePolicy": "WrapsWhenFull"
}

**Comment by mraineri** [comment]
I think the lack of `@odata.type` inside of the "Attala" object might be the source of the issue. `@odata.type` is needed in the OEM objects in order for a client to know where to find information about the object's definition. I would expect it to be something like this:
```
{
    "Oem": {
        "Attala": {
            "@odata.type": "#AttalaExtensions.LogService",
            "Entries": { ... }
        }
    }
}
```

@tomasg2012 does this sounds like the source of the issue to you? Any other recommendations?

**Comment by tomasg2012** [comment]
Since Entries is an EntityType link, if there's no @odata.type there is not really a way to assume what the target resource is supposed to be.  If "#AttalaExtensions.LogService" resolves into a LogService, then it should be a Pass.

**Comment by mraineri** [comment]
Okay, so it would be worth checking "/redfish/v1/StorageSystems/FPGA_000/LogServices/TGT_1970_01_01_00_22_50_480102/Events" to ensure it has the property `@odata.type` with the value `#LogEntryCollection.LogEntryCollection`.

**Comment by tomasg2012** [comment]
I may have misunderstood the Resource path here, there is a possibility that there is an underlying tool, but a full verbose test log might be more useful to know if Entries is passing or not.

**Comment by DileepEx** [comment]
Debug log attached.
[DebugLog.txt](https://github.com/DMTF/Redfish-Service-Validator/files/3483554/DebugLog.txt)

**Comment by DileepEx** [comment]
Experts,
Any suggestions on this?

**Comment by mraineri** [comment]
Going back to the LogEntry resource, I missed the fact that "LogEntryType" is not in the resource for your implementation. It's a required property, so you need to support it in the payload.

There are a couple of other errors I see:
- The "Attala" object in various requires requires the `@odata.type` property so clients know the definition of the "Attala" object.
- I see there's also mention of the "Id" and "Name" properties missing on the Log Entry resources; this appears to be relative to the Log Entry Collection resource where the Log Entry resources are expanded.

**Comment by mraineri** [comment]
As a general comment about the usage of "Oem" here, since the only property is "Entries" and is the same as the standard "Entries" property at the root level of the object.

**Comment by jautor** [comment]
@DileepEx did that resolve your issue -we believe this is correct in the code as-is...

**Comment by mraineri** [comment]
Last comment asking if this issue has been addressed was posted a while ago; closing. Please reopen if further help is needed.
