### ISSUE TITLE
Unexpected Error in Manager Actions: list

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#34]
Reviewing output I see these error - 
  ERROR - #Manager.ForceFailover: action not Found
  ERROR - #Manager.ModifyRedundancySet: action not Found

These 2 actions are indeed not available in the page but should the test tool note this as an error?

**Comment by jbobzin-insyde** [comment]
The test leading to this issue was done with schema from redfish.dmtf.org, because LocalOnlyMode and ServiceMode are both set to false in config.ini

**Comment by tomasg2012** [comment]
It depends on whether or not Actions are considered Mandatory by nature.  If they are not, then a missing action is simply considered optional.  I will have to read into the spec or ask about that.  When I had written the Action validation, I was also not sure if certain entries such as 'target' are necessary at all, let alone the action itself.

**Comment by jbobzin-insyde** [comment]
Tomas - see for answers
https://github.com/DMTF/spmf/issues/2079
https://github.com/DMTF/spmf/issues/2080

Actions are optional unless they have Redfish.Required
Properties inside complex types like actions are optional unless they have Redfish.Required

**Comment by tomasg2012** [comment]
Thank you for the clarification, jeff!

**Comment by tomasg2012** [comment]
This should be fixed in the next pull.

**Comment by tomasg2012** [comment]
This should be in the branch 'enhancements-06-12' now ( it previously had bad indentation that prevented some actions from being identified ).

**Comment by jbobzin-insyde** [comment]
Fixed in the latest branch
