### ISSUE TITLE
Action patternProperties unexpected error

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-Service-Validator#340]
Hi,

I see some action properties (patternProperties) show as an error in report but it shall not be.

For example, below is ComputerSystem Reset Action properties and "@Redfish.OperationApplyTimeSupport" is reported as below error, but in schema definition, this is allowed.

ERROR - Actions.#ComputerSystem.Reset: Property "@Redfish.OperationApplyTimeSupport" is not allowed in actions property. Allowed properties are "target", "title", "@Redfish.ActionInfo" and "*@Redfish.AllowableValues"

Example
"Actions": {
        "#ComputerSystem.Reset": {
            "@Redfish.ActionInfo": "/redfish/v1/Systems/Self/ResetActionInfo",
            "@Redfish.OperationApplyTimeSupport": {
                "@odata.type": "Settings.v1_2_1.Settings.OperationApplyTimeSupport",
                "MaintenanceWindowDurationInSeconds": 600,
                "MaintenanceWindowResource": {
                    "@odata.id": "/redfish/v1/Systems/Self"
                },
                "SupportedValues": [
                    "Immediate",
                    "AtMaintenanceWindowStart"
                ]
            },
            "target": "/redfish/v1/Systems/Self/Actions/ComputerSystem.Reset"
        }
    },

Please help to check, thanks

**Comment by billdodd** [comment]
I think that at the time the Actions validation logic was last updated, the @Redfish.OperationApplyTimeSupport annotation had not been added to the spec. And the logic was explicitly looking the annotations that would be expected (@Redfish.ActionInfo and *@Redfish.AllowableValues).

I'm not sure whether we should just add the @Redfish.OperationApplyTimeSupport to the list of allowed properties or loosen the check to allow any Redfish annotation (using the patternProperties regex or similar). The later would match the schema and avoid similar issues in the future.

**Comment by tomasg2012** [comment]
If the latter is true, then the Actions property should just be treated as
such.  The tool currently treats "Actions" as an exception to other
ComplexTypes and I believe doesn't process it similarly, so I can look into
lacing those principles.

**Comment by mraineri** [comment]
I think we should be a little explicit and keep a short list since other Redfish annotations really don't belong in Actions

**Comment by snk20501** [comment]
FYR.
In schema ComputerSystem.v1_7_0.json, "patternProperties" is defined for "Reset" action.

`      "Reset": {
            "additionalProperties": false,
            "description": "This action is used to reset the system.",
            "longDescription": "This action shall perform a reset of the ComputerSystem.  For systems which implement ACPI Power Button functionality, the PushPowerButton value shall perform or emulate an ACPI Power Button push.  The ForceOff value shall remove power from the system or perform an ACPI Power Button Override (commonly known as a 4-second hold of the Power Button).  The ForceRestart value shall perform a ForceOff action followed by a On action.",
            "parameters": {
                "ResetType": {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Resource.json#/definitions/ResetType",
                    "description": "The type of reset to be performed.",
                    "longDescription": "This parameter shall define the type of reset to be performed.  The service may accept a request without the parameter and perform an implementation specific default reset."
                }
            },
            "patternProperties": {
                "^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\\.[a-zA-Z_][a-zA-Z0-9_]*$": {
                    "description": "This property shall specify a valid odata or Redfish property.",
                    "type": [
                        "array",
                        "boolean",
                        "integer",
                        "number",
                        "null",
                        "object",
                        "string"
                    ]
                }
            },`

**Comment by mraineri** [comment]
Yes, the OperationApplyTime value is valid here. I think given the usage of other annotations though, we shouldn't blindly allow for any Redfish annotations and think the change should be to just add OperationApplyTime.

**Comment by billdodd** [comment]
Thanks for the input @mraineri. I made that small change.

**Comment by snk20501** [comment]
@mraineri @billdodd Thanks for your help. :)
