### ISSUE TITLE
Unexpected errors for /Thermal#/Temperatures , /Thermal#/Fans and /Power#/Voltages

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-Service-Validator#341]
Hi,

I found one error that always shows for Chassis Thermal and Chassis Power resources.

In Thermal and Power resources, we implement "@odata.id" for each sensor numbers by following Spec. ask. In validator report, it always shows two error as following, but I can't see what's the actual issue. Please help to clarify.

ERROR - Decoded object no longer a dictionary /redfish/v1/Chassis/Self/Power
ERROR - @odata.id of ReferenceableMember does not properly resolve: /redfish/v1/Chassis/Self/Power#/Voltages/145
GET Success HTTP Code (-1)

For Example,
"Voltages": [
        {
            "@odata.id": "/redfish/v1/Chassis/Self/Power#/Voltages/145",
            "LowerThresholdCritical": 2.8,
            "LowerThresholdFatal": 2.66,
            "LowerThresholdNonCritical": 2.96,
            "MaxReadingRange": 5.1,
            "MemberId": "VoltageSensor145",
            "MinReadingRange": 0,
            "Name": "P3V3",
            "PhysicalContext": "VoltageRegulator",
            "RelatedItem@odata.count": 0,
            "SensorNumber": 145,
            "Status": {
                "State": "Absent"
            },
            "UpperThresholdCritical": 3.8,
            "UpperThresholdFatal": 3.98,
            "UpperThresholdNonCritical": 3.62
        }
]

Thanks

**Comment by mraineri** [comment]
The `@odata.id` property needs to resolve as a JSON pointer in the Voltage resource. That means the last portion of the URI will need to be the array index. Using "Voltages/145" implies that this object is the 145th element of the Voltages array.

**Comment by mraineri** [comment]
Generally speaking, anytime there is a # in the URI, this divides the URI into two portions. The left portion being the URI of the resource, and the right portion being an RFC6901 conformant JSON pointer.

**Comment by tomasg2012** [comment]
A stricter regex should probably be written to keep the confusion to a
minimum, but yes, the above urls wouldn't resolve since it starts with an
blank after the pound sign.  Decoded message is vague.

**Comment by jautor** [comment]
Also, the `MemberId` property must contain the (string) value equal to the array offset - in your example it's "VoltageSensor145", and it should be "1" (or whatever the actual array member is).

**Comment by snk20501** [comment]
Hi All,

Thanks for the clarification. So the correct implementation shall be as following, right?
The Id shall start with 0 or 1?

"Voltages": [
{
"@odata.id": "/redfish/v1/Chassis/Self/Power#/Voltages/1",
"MemberId": "1"
},
{
"@odata.id": "/redfish/v1/Chassis/Self/Power#/Voltages/2",
"MemberId": "2"
},
{
"@odata.id": "/redfish/v1/Chassis/Self/Power#/Voltages/3",
"MemberId": "3"
},
{
"@odata.id": "/redfish/v1/Chassis/Self/Power#/Voltages/4",
"MemberId": "4"
}
.
.
.
]

Thanks

**Comment by mraineri** [comment]
Since JSON arrays are indexed from 0, then it needs to also start from 0

**Comment by mraineri** [comment]
But even though the problem is with the implementation, I'd like to keep this issue open so we can clarify the error message.

**Comment by snk20501** [comment]
Okay. We will change implementation then see how it goes.
