### ISSUE TITLE
Validator reports the other Error on Chassis with the schema 2019.2

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#349]
After verifying with the last PR, the original error is gone but there is a new error is reported:
`ERROR - 1 failAdditional errors in /redfish/v1/Chassis/1`
=> ERROR - PCIeDevices not defined in schema Chassis.v1_9_2 (check version, spelling and casing)
But the property `PCIeDevices` is exist in the Chassis.v1_10_0.

Here is the debug log:
[ConformanceLog_10_18_2019_171951.txt](https://github.com/DMTF/Redfish-Service-Validator/files/3743249/ConformanceLog_10_18_2019_171951.txt)

**Comment by mraineri** [comment]
That looks correct to me; if your Chassis resource is reporting v1_9_2, then it cannot have PCIeDevices in its payload since it was added in a later version. If you correct your `@odata.type` property to report v1_10_0, then it should resolve your error.

**Comment by tomasg2012** [comment]
Notably though, the payload is using v1_10_0, I believe, in its
@odata.type.  Tool was just not expecting double digits so it is still not
properly comparing a version numbers correctly.

**Comment by mraineri** [comment]
Ah, I missed that; I thought it was reporting v1_9_2. Good catch.
