### ISSUE TITLE
The newest Validator reports errors that are not exist before

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#352]
The newest version Validator reports below errors that are not exist before this version:
```
ERROR - Error message present in /redfish/v1/Chassis/1/Power#/PowerControl/0
ERROR - Error message present in /redfish/v1/Chassis/1/Power#/PowerControl/1
ERROR - Error message present in /redfish/v1/Chassis/1/Power#/PowerControl/2
ERROR - Error message present in /redfish/v1/Chassis/1/Power#/Redundancy/0
```
Here is the debug log:
[ConformanceLog_10_25_2019_163137.txt](https://github.com/DMTF/Redfish-Service-Validator/files/3771287/ConformanceLog_10_25_2019_163137.txt)

Please help to check this. Or implementation shall add `@odata.type` into all instances of ReferenceableMember now?

Thank you

**Comment by tomasg2012** [comment]
On closer inspection of the payload, it seems there might be a mix-up in the program that improperly finds the highest type for payloads without `@odata.type`.  It is true, `@odata.type` should still not be mandatory.

**Comment by JojoWu19** [comment]
@tomasg2012 , Do you need the other information? or this is enough for you?

**Comment by tomasg2012** [comment]
The log contains the payload data and is sufficient enough, I don't believe the OEM/Service information is related.  Thank you!

**Comment by JojoWu19** [comment]
Get it, and thank for your response.

**Comment by tomasg2012** [comment]
The branch `version-top-fix` should have a remedy for this error, if you are able to check for yourself.

**Comment by JojoWu19** [comment]
It reports different errors:
```
Error message present in /redfish/v1/Systems/1/NetworkInterfaces
Error message present in /redfish/v1/Systems/1/Memory
...
```
Here is the debug log:
[ConformanceLog_10_25_2019_183554.txt](https://github.com/DMTF/Redfish-Service-Validator/files/3771653/ConformanceLog_10_25_2019_183554.txt)

**Comment by JojoWu19** [comment]
I am going to offline. If you have new fix that need to check, I could check at Monday.
Thank you

**Comment by geissonator** [comment]
We seemed to have hit this as well over in OpenBMC. We run the validator as a part of our HW CI and it all suddenly started failing:
```
ERROR - Verifying property that does not belong to this version: Power.v1_5_0.PowerSupply:PowerInputWatts
ERROR - Verifying property that does not belong to this version: Power.v1_1_0.PowerSupply:Manufacturer
```
Even though we have the latest JsonSchema files on our system.

**Comment by jmbills** [comment]
For OpenBMC, we just implemented the Chassis.v1_10_0 schema which fails if we don't use the latest validator, but with the latest we hit this issue.  Is there any ETA on a fix for this issue so we can continue using the validator?

**Comment by tomasg2012** [comment]
Will be a fix by Thursday.

**Comment by JojoWu19** [comment]
The issue is fixed to me.
Thank you.

**Comment by mraineri** [comment]
Thanks for confirming!
