### ISSUE TITLE
TooManyRedirects error

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-Service-Validator#353]
When I run latest tool, I see following error and tool stopped. Our current implementation for "/redfish/v1" is to return status code 302 not 200. Is this the root cause? Please help to check. Thanks.

![Screenshot from 2019-10-30 17-43-58](https://user-images.githubusercontent.com/21072491/67847128-4a525f80-fb3d-11e9-9524-37f46fd90f13.png)

**Comment by billdodd** [comment]
A couple of questions:

1. When your service returns the 302 status for `/redfish/v1`, what is returned in the `Location` header?
2. What are the results when you try to access `/redfish/v1` using a browser, curl, postman, etc.?

**Comment by snk20501** [comment]
@billdodd You just point out the problem. The Location header is still "/redfish/v1" and not point to the right uri, so this a bug in our implementation. Even thought I think it will be better that tool can keep running and finish the test.

Thank you.

**Comment by billdodd** [comment]
Glad to hear you found the issue in the implementation.

The RSV tool doesn't perform the redirect handling logic itself; it relies on the `requests` package (or a lower-level Python package that the `requests` package uses). So we don't have much control over that.

**Comment by snk20501** [comment]
@billdodd got it.

**Comment by tomasg2012** [comment]
Closed with solution.
