### ISSUE TITLE
@odata item not conformant ERROR

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-Service-Validator#358]
Hi,

We use latest tool to validate service and get oem errors for ServiceRoot. We implement some Oem properties as below.

 "Oem": {
        "Ami": {
            "@odata.type": "AMIServiceRoot.v1_0_0.AMIServiceRoot",
            "RtpVersion": "1.7.0",
            "configurations": {
                "@odata.id": "/redfish/v1/configurations"
            }
        },
        "Dre": {
            "@odata.type": "#AMIDynamicExtension.v1_0_0.AMIDynamicExtension",
            "DynamicExtension": {
                "@odata.id": "/redfish/v1/DynamicExtension"
            }
        }
    },

![err](https://user-images.githubusercontent.com/21072491/69510731-05252000-0f79-11ea-9b1e-8f1df2407e23.JPG)

Before run the tool, I do put Oem schema xml in assigned schema folder. Now I'm not sure what can be the reason to cause this error. Please help.

**Comment by mraineri** [comment]
That error looks correct; `@odata.type` is not in the right format. All values for that property start with a `#`, followed by the namespace name, followed by a `.`, and then the type name. The one inside of `Ami` is missing the `#`.

**Comment by jautor** [comment]
Let's add a check for this, perhaps for testing the format of `@odata.type` in general.  Then the tool can spit out a more helpful error message.

**Comment by mraineri** [comment]
I think that's what this check is; it's complaining about the format of value found in the property. We could just add something along the lines of "Expected format is `#Namespace.Type`".

**Comment by snk20501** [comment]
@mraineri @jautor Thanks for your help and that will be great to have extra message.

I would like to check the "Warning" part also. Just like I mentioned, I see the "Warning" even if I put the xml in the schema file folder. I attach a example for reference.

[example.zip](https://github.com/DMTF/Redfish-Service-Validator/files/3889649/example.zip)

**Comment by mraineri** [comment]
`AMIServiceRoot` inside of `AMIServiceRoot.v1_0_0` needs to be a `ComplexType`; `EntityType` is used for resources (whereas you're just defining a JSON object within a resource).

In addition, the `AMIServiceRoot.v1_0_0` namespace does not contain a definition for `AMIDynamicExtension`.

OData clients parse `@odata.type` to look up definitions in schema files. When you make a reference like `#AMIServiceRoot.v1_0_0.AMIDynamicExtension`, this means "Go to the `AMIServiceRoot.v1_0_0` namespace, and look for the definition of `AMIDynamicExtension`". It might be worth reviewing our OData white paper to see some of the details behind the CSDL construction: https://www.dmtf.org/sites/default/files/standards/documents/DSP2052_1.0.0.pdf

**Comment by snk20501** [comment]
@mraineri Got it. We will check this issue. Thanks for the reminder.

**Comment by mraineri** [comment]
@snk20501 were you able to resolve your issue with the comments provided earlier?

**Comment by snk20501** [comment]
@mraineri Yes, please close this issue. Thank you very much.

**Comment by mraineri** [comment]
Error message updated in recent PR
