### ISSUE TITLE
Result contains a lot of FAIL in MessageRegistryFile

### ISSUE THREAD

**Issue by ginny183** [DMTF/Redfish-Service-Validator#359]
We got a lot of FAIL when executing Redfish-Service-Validator 1.3.4. Especially for this validation:
/redfish/v1/Registries/BiosAttributeRegistry0ACIJ.0.22.0.json. There are failAdditional: 181 and failMandatoryExist: 9. Could you help to check it?
 **The ERROR as below.**
ERROR - Languages[0]: Mandatory prop does not exist
ERROR - Languages[1]: Mandatory prop does not exist
ERROR - Languages[2]: Mandatory prop does not exist
ERROR - Registry: Mandatory prop does not exist
ERROR - Location[0]: Mandatory prop does not exist
ERROR - Location[1]: Mandatory prop does not exist
ERROR - Location[2]: Mandatory prop does not exist
ERROR - Id: Mandatory prop does not exist
ERROR - Name: Mandatory prop does not exist
ERROR - ACPI003 not defined in schema MessageRegistryFile.v1_1_3 (check version, spelling and casing)
ERROR - ACPI004 not defined in schema MessageRegistryFile.v1_1_3 (check version, spelling and casing)
.
.
.
**The registry content as below.**
{     
"@odata.context": "/redfish/v1/$metadata#MessageRegistryFile.MessageRegistryFile",     
"@odata.etag": "W/\"1574250041\"",     
"@odata.id": "/redfish/v1/Registries/BiosAttributeRegistry0ACIJ.0.22.0.json",     
"@odata.type": "#MessageRegistryFile.v1_1_0.MessageRegistryFile",     
"ACPI003": {        
 "Type": "Boolean"     
},     
"ACPI004": {         
"Type": "Boolean"     
},     
.
.
.

**Comment by tomasg2012** [comment]
The structure of this payload appears to be missing critical information, based on what the report is saying.  I cannot tell if this is the full payload, but I don't believe entries such as ACPI003 are supposed to be at the root of the resource itself, rather a sub entry.  Do you have the full json of the resource, or an HTML log from the run?

**Comment by mraineri** [comment]
It looks like you're trying to create an Attribute Registry resource and not a Message Registry File resource. The former is for describing BIOS attributes, and the latter is for describing the location of a registry file. The errors look correct to me given the very different schema definitions.

**Comment by mraineri** [comment]
It would be good to check out the resource guide and see examples of the Attribute Registry and Message Registry File resources.

https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2019.3.pdf

**Comment by ginny183** [comment]
I have no more question for this ticket. Thank you for your kindly reply.
