### ISSUE TITLE
Error -  LogService was not found in payload  in TelemetryService.

### ISSUE THREAD

**Issue by yinchilee** [DMTF/Redfish-Service-Validator#361]
Hi,

We use the latest tool to validate service and get "ERROR - LogService was not found in payload, attempting closest match: LogServices".

![12345](https://user-images.githubusercontent.com/55127828/72488607-5f8d7f00-384c-11ea-9e37-50ffa95e8a7d.jpg)

Followed TelemetryService.v1_1_1.json  - LogService
![telem](https://user-images.githubusercontent.com/55127828/72488649-8d72c380-384c-11ea-91ac-3b71162abec0.jpg)

Followed  Schema Manager.v1_5_2.json - LogServices
![logser](https://user-images.githubusercontent.com/55127828/72488724-c6129d00-384c-11ea-903e-8b2e008f5a6c.jpg)

**Comment by mraineri** [comment]
That error is correct; TelemetryService points to a single LogService, so the property is named "LogService".

Other devices (Managers, ComputerSystems, Chassis) may have multiple logs, hence they point to a LogServiceCollection with a "LogServices" property.

**Comment by tomasg2012** [comment]
Closed for solution.
