### ISSUE TITLE
Id,Name returning Error message 

### ISSUE THREAD

**Issue by SelviRaju** [DMTF/Redfish-Service-Validator#362]
Hi,

Created New URI and xml for configuration,Getting error in ID and Name by using latest Redfish Validation Tool.

**/redfish/v1/configurations**

For **Id,Name** defined in Resource_v1.xml but got error while running Redfish validation tool.

**CertificateAuthorityUrl** showing as Json object,initially value will be empty string,once patch is success,value will be shown in json object.

Changes to showing as jsonobject,but got error message

Please find the response,validation error message and xml file

![configuration_error](https://user-images.githubusercontent.com/60085258/72699791-cb832680-3b6f-11ea-85a4-b862a10f5fa0.png)

![configuration_response](https://user-images.githubusercontent.com/60085258/72699793-cc1bbd00-3b6f-11ea-8dfc-5fe1afc17ad5.png)

[configuration_xml.txt](https://github.com/DMTF/Redfish-Service-Validator/files/4084492/configuration_xml.txt)

Thanks & Regards,
R.Selvi

**Comment by mraineri** [comment]
At least on initial inspection the OEM schema does appear to be properly constructed; Configurations.v1_0_0.Configurations inherits from Configurations.Configurations, which in turn inherits from Resource.v1_0_0.Resource.

I haven't looked much deeper into the schema than that though.

**Comment by mraineri** [comment]
On a side note, one thing I'd recommend reviewing are some clauses in the spec with regards to naming of OEM schemas and using OEM URIs. While what you have is programmatically valid from what I can see, there are potential OEM collisions that can happen if you don't follow our guidelines (like using your company name as part of the schema name).

**Comment by billdodd** [comment]
I think the problem may be that the new schema is not registering the `"Redfish"` namespace. Try patching your schema like this and see if that helps:

```
*** Configuration_v1.xml.save	2020-01-20 11:48:58.000000000 -0600
--- Configuration_v1.xml	2020-01-20 11:56:08.000000000 -0600
***************
*** 18,23 ****
--- 18,26 ----
      <edmx:Include Namespace="Resource"/>
      <edmx:Include Namespace="Resource.v1_0_0"/>
    </edmx:Reference>
+   <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
+     <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
+   </edmx:Reference>

  <edmx:DataServices>

```

**Comment by SelviRaju** [comment]
Thanks you very much for immediate support, i will add this changes in xml file and will update in forum.

**Comment by mraineri** [comment]
@SelviRaju did this address your problem? Can we close out this issue?

**Comment by SelviRaju** [comment]
@mraineri with this changes ,Id and Name fixed,thank you very much.
