### ISSUE TITLE
Could not get service root

### ISSUE THREAD

**Issue by Sumitkm897** [DMTF/Redfish-Service-Validator#363]
Redfish Service Validator, version 1.3.4
Setting up service...
Constructing metadata...
Could not get ServiceRoot
ConfigURI: 127.0.0.1:8000
System Info: No desc
authtype: None
cachefilepath: ./cache
cachemode: Off
certificatecheck: False
config: config/config.ini
configuri: http://127.0.0.1:8000
debug_logging: True
forceauth: True
linklimit: {'LogEntry': 20}
localonlymode: True
logpath: ./logs
metadatafilepath: C:\Users\Administrator\Desktop\Redfish\Redfish-Service-Validator-master\DSP8010_2019.4\DSP8010_2019.4
oemcheck: True
payloadfilepath: C:\Users\Administrator\Desktop\Redfish\Redfish-Mockup-Creator-master\iLOmockup\redfish\v1\AccountService\index.json
payloadmode: TreeFile
preferonline: False
sample: 0
schemasuffix: _v1.xml
servicemode: True
timeout: 30
uricheck: False
username: Administrator
usessl: False
v: True
verbose_checks: True
Start time: 03/03/20 - 15:42:59

while validating the mockup locally, validator is not able to get the URL for all resources:

Chassis: GET of resource at URI /redfish/v1/Chassis/ returned HTTP 503. Check URI.
	FAIL
Systems: GET of resource at URI /redfish/v1/Systems/ returned HTTP 503. Check URI.
	FAIL
UpdateService: GET of resource at URI /redfish/v1/UpdateService/ returned HTTP 503. Check URI.
	FAIL
TelemetryService: GET of resource at URI /redfish/v1/TelemetryService/ returned HTTP 503. Check URI.
	FAIL

**Comment by Sumitkm897** [comment]
Same problem occurred stating that URI cannot  be acquired.
ServiceRoot.v1_6_0.ServiceRoot, Counter({'pass': 16, 'failProp': 11, 'skipOptional': 10, 'passGet': 1, 'err.TelemetryService.TelemetryService': 1, 'err.UpdateService.UpdateService': 1, 'err.ComputerSystemCollection.ComputerSystemCollection': 1, 'err.ChassisCollection.ChassisCollection': 1, 'err.ManagerCollection.ManagerCollection': 1, 'err.TaskService.TaskService': 1, 'err.SessionService.SessionService': 1, 'err.AccountService.AccountService': 1, 'err.EventService.EventService': 1, 'err.MessageRegistryFileCollection.MessageRegistryFileCollection': 1, 'err.JsonSchemaFileCollection.JsonSchemaFileCollection': 1, 'err.SessionCollection.SessionCollection': 1, 'failMandatoryProp': 1, 'failComplex': 1})
Elapsed time: 0:00:46
1 failComplex errors in C:\Users\Administrator\Desktop\Redfish\Redfish-Mockup-Creator-master\iLOmockup\redfish\v1\index.json
1 failMandatoryProp errors in C:\Users\Administrator\Desktop\Redfish\Redfish-Mockup-Creator-master\iLOmockup\redfish\v1\index.json
11 failProp errors in C:\Users\Administrator\Desktop\Redfish\Redfish-Mockup-Creator-master\iLOmockup\redfish\v1\index.json
Counter({'metadataNamespaces': 177, 'pass': 16, 'failProp': 11, 'skipOptional': 10, 'serviceNamespaces': 3, 'badNamespaceInclude': 2, 'passGet': 1, 'err.TelemetryService.TelemetryService': 1, 'err.UpdateService.UpdateService': 1, 'err.ComputerSystemCollection.ComputerSystemCollection': 1, 'err.ChassisCollection.ChassisCollection': 1, 'err.ManagerCollection.ManagerCollection': 1, 'err.TaskService.TaskService': 1, 'err.SessionService.SessionService': 1, 'err.AccountService.AccountService': 1, 'err.EventService.EventService': 1, 'err.MessageRegistryFileCollection.MessageRegistryFileCollection': 1, 'err.JsonSchemaFileCollection.JsonSchemaFileCollection': 1, 'err.SessionCollection.SessionCollection': 1, 'failMandatoryProp': 1, 'failComplex': 1, 'warningPresent': 1, 'missingNamespaces': 1})
Validation has failed: 15 problems found

**Comment by tomasg2012** [comment]
You still need a live mockup/server for the payload method you are using
"TreeFile", hosted by something like RedfishMockupServer.  It will not
traverse a filesystem on its own, it is only good for testing a single
correction to a payload.

If you want to do something like what you're doing, you may want to try the
cachemode and cachedir options, which allows you to overwrite server calls
with local files.

**Comment by Sumitkm897** [comment]
Thanks for the above suggestion.
 
but i'm not able to get the response from any URI. Stating that...
URI could not be acquired

GET of resource at URI /redfish/v1/SessionService/Sessions/ returned HTTP 503. Check URI.
	FAIL
GET of resource at URI /redfish/v1/JsonSchemas/ returned HTTP 503. Check URI.
	FAIL
similarly...for all other resources its failing

Redfish Service Validator, version 1.3.4
Setting up service...
Constructing metadata...
Could not get ServiceRoot....//Not able to get serviceRoot
ConfigURI: 127.0.0.1:8000

**Comment by Sumitkm897** [comment]
Thank you so much for your help and support. It is really helpful

**Comment by tomasg2012** [comment]
You're welcome.  A 503 is not a common result, so I only assumed the
service you were attempting to access was not Redfish.

However, it could have been a Username Password inconsistency, or a live
service.  I hope my advice helped, but I do not know if that was the
solution.
