### ISSUE TITLE
$metadata issue 

### ISSUE THREAD

**Issue by yinchilee** [DMTF/Redfish-Service-Validator#364]
Hi,

We use the latest tool to validate service and get Error:
ERROR - The following namespaces included in $metadata could not be found in the referenced schema URI:
Namespace Sensor.v1_0_3 not found in schema http://redfish.dmtf.org/schemas/v1/Sensor_v1.xml
![sensor](https://user-images.githubusercontent.com/55127828/76136629-73947680-606e-11ea-8948-f4611f6a1461.jpg)

I user Schema DSP8010_2019.2 and I have check "Sensor_v1.xml"  it support  "Sensor.v1_0_2" Instead of  "Sensor.v1_0_3".
[
![sernsor1 02](https://user-images.githubusercontent.com/55127828/76136607-3def8d80-606e-11ea-88f5-434cb7dd699e.jpg)
](url)

**Comment by billdodd** [comment]
Check your metadata document at /redfish/v1/$metadata. It looks like it is including Sensor.v1_0_3, but the schema file referenced only defines v1_0_0, v1_0_1, and v1_0_2. You can either change your $metadata to include the Sensor.v1_0_2 namespace or use the DSP8010_2019.3 or DSP8010_2019.4 schemas (which will define Sensor.v1_0_3).

**Comment by yinchilee** [comment]
Ok, Thank you for your explanation.

**Comment by tomasg2012** [comment]
Closed for explanation.
