### ISSUE TITLE
csv log file opening issue

### ISSUE THREAD

**Issue by chandu-tmba** [DMTF/Redfish-Service-Validator#368]
python3  RedfishServiceValidator.py -c config/config.ini -v
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 19, in <module>
    from tohtml import renderHtml, writeHtml, count_errors
  File "/home/openbmc/Redfish_schema_validator/Redfish-Service-Validator/tohtml.py", line 306
    output = open(f'./logs/{outputLogName}.csv','w',newline='')
                                              ^
SyntaxError: invalid syntax

**Comment by gtmills** [comment]
I hit this as well. 

https://github.com/DMTF/Redfish-Service-Validator/commit/b8fdad3a1786f8f3fa8e8d31a3b4c8ff346e3ee3 seems to have broken this.

https://github.com/DMTF/Redfish-Service-Validator/blob/b8fdad3a1786f8f3fa8e8d31a3b4c8ff346e3ee3/tohtml.py#L306

https://docs.python.org/3/library/functions.html#open 

```
python3 --version
Python 3.5.6
```

**Comment by tomasg2012** [comment]
Seems that string doesn't make sense?  Will have to change it to a proper
formatted string..

**Comment by billdodd** [comment]
> Seems that string doesn't make sense? Will have to change it to a proper formatted string..

Yeah, f strings are only supported in Python 3.6 and later.

**Comment by mraineri** [comment]
Closed; latest PR fixes this
