### ISSUE TITLE
Validator fails when moving to 2020.1

### ISSUE THREAD

**Issue by gtmills** [DMTF/Redfish-Service-Validator#369]
I am trying to move OpenBMC to 2020.1. Excited to add some new features to our implementation. :) 
[gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32188](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32188)

OpenBMC uses the latest Task Event Message Registry
[redfish.dmtf.org/registries/TaskEvent.1.0.1.json](https://redfish.dmtf.org/registries/TaskEvent.1.0.1.json)

After moving to 2020.1, I see several Redfish-Service-Validator errors in the Task Event Message Registry:
```
ERROR - Messages.TaskAborted.MessageSeverity: Mandatory prop does not exist
ERROR - Messages.TaskCancelled.MessageSeverity: Mandatory prop does not exist
ERROR - Messages.TaskCompletedOK.MessageSeverity: Mandatory prop does not exist
ERROR - Messages.TaskCompletedWarning.MessageSeverity: Mandatory prop does not exist
....
```

Also, see these in the Base Message Registry, even after moving to the latest, [redfish.dmtf.org/registries/Base.1.8.0.json](https://redfish.dmtf.org/registries/Base.1.8.0.json)

This is caused by the new required property, MessageSeverity, in MessageRegistry.v1_4_0.json.

On the Redfish call today, it was confirmed these shouldn't be errors since not using the MessageRegistry.v1_4_0.json.

Also seeing new Warnings around the use of the Severity property in these registries:
```WARNING - Messages.TaskStarted.Severity: The given property is deprecated by revision: This property has been deprecated in favor of MessageSeverity, which ties the values to the enumerations defined for the Health property within Status.```

The Redfish-Service-Validator I am using is e299ff3075f7271253db23909a5e9e6a4fdb294e

From Thread https://redfishforum.com/thread/323/validator-errors-when-moving-release

**Comment by gtmills** [comment]
From the ConformanceLog
```
VERBO - MessageRegistry.v1_0_0.Message:NumberOfArgs
VERBO - 	value: 0 <class 'int'>
VERBO - 	has Type: Edm.Int64 Edm.Int64
VERBO - 	Mandatory Test: OK
VERBO - 	permission OData.Permission/Read
VERBO - 	Success
VERBO - MessageRegistry.v1_0_0.Message:ParamTypes
VERBO - 	value: n/a <class 'str'>
VERBO - 	has Type: Collection(MessageRegistry.v1_0_0.ParamType) enum
VERBO - 	is Optional
VERBO - 	prop Does not exist, skip...
VERBO - MessageRegistry.v1_0_0.Message:Resolution
VERBO - 	value: The modification may have failed due to permission issues or issues with the request body. <class 'str'>
VERBO - 	has Type: Edm.String Edm.String
VERBO - 	Mandatory Test: OK
VERBO - 	permission OData.Permission/Read
VERBO - 	Success
VERBO - MessageRegistry.v1_0_0.Message:Oem
VERBO - 	value: n/a <class 'str'>
VERBO - 	has Type: Resource.Oem complex
VERBO - 	is Optional
VERBO - 	prop Does not exist, skip...
VERBO - 	***out of Complex
VERBO - complex Counter({'skipOptional': 6, 'pass': 5, 'failMandatoryExist': 1, 'warnDeprecated': 1, 'err.Resource.Health': 1})
VERBO - MessageRegistry.v1_0_0.MessageProperty:AccountRemoved
VERBO - 	value: OrderedDict([('Description', 'Indicates that the account was successfully removed.'), ('Message', 'The account was successfully removed.'), ('NumberOfArgs', 0), ('Resolution', 'No resolution is required.'), ('Severity', 'OK')]) <class 'collections.OrderedDict'>
VERBO - 	has Type: MessageRegistry.v1_0_0.Message complex
VERBO - 	is Optional
VERBO - 	***going into Complex
VERBO - MessageRegistry.v1_4_0.Message:MessageSeverity
VERBO - 	value: n/a <class 'str'>
VERBO - 	has Type: Resource.Health enum
VERBO - 	Mandatory Test: FAIL
VERBO - 	permission OData.Permission/Read
ERROR - Messages.AccountRemoved.MessageSeverity: Mandatory prop does not exist
VERBO - 	FAIL
```

**Comment by tomasg2012** [comment]
The code branch `complex-version-limit` should appropriate cast complex and additional objects in them as limited by the versions written in the payload.

**Comment by mraineri** [comment]
@gtmills would you be able to verify the fix in the branch @tomasg2012 mentioned? If it solves your problem, I'll go ahead and merge things and make a new release.

**Comment by gtmills** [comment]
That branch, complex-version-limit, passed. I really appreciate the quick fix here! 

I am still seeing warnings for Severity deprecated, even though it is a required property. 
https://github.com/DMTF/Redfish/issues/4007

```
WARNING - Messages.UnrecognizedRequestBody.Severity: The given property is deprecated by revision: This property has been deprecated in favor of MessageSeverity, which ties the values to the enumerations defined for the Health property within Status.
```

**Comment by gtmills** [comment]
Didn't mean to close. Sorry for the noise.

**Comment by mraineri** [comment]
Great, thanks; I'll start the release process for the tool

**Comment by mraineri** [comment]
Fix merged to master
