### ISSUE TITLE
LocalAccountAuth design explaination

### ISSUE THREAD

**Issue by archerwen** [DMTF/Redfish-Service-Validator#376]
Hi,

According LocalAccountAuth description in AccountService.v1_6_0 schema:
"LocalAccountAuth": 
**"Fallback"**: "The service authenticates users based on the Account Service-defined accounts collection only if any external account providers are currently unreachable."
**"LocalFirst"**: "The service first authenticates users based on the Account Service-defined accounts collection.  If authentication fails, the Service authenticates by using external account providers."

Question1: 
If i created two account with same username but different password for external & local, like below.
**Account Service-defined account :** 
Username: ADtest1, Password: Auto0001
**External AD Account:**
Username: ADtest1, Password: Auto0000

When i switch to "LocalFirst" and try to login ADtest1 with password like Auto0002, Auto0003...etc to locked the account.
When account locked, is External AD Account can access redfish?

Question2:
If Question1 answer is NO,
What is the real behavior for Fallback and LocalFirst?

Thanks,
Archer.

**Comment by mraineri** [comment]
@archerwen I recommend posting this on https://redfishforum.com/ for asking general questions about Redfish. This Github project is to track a tool we develop for verifying a service conforms to the schema definitions.

**Comment by archerwen** [comment]
@mraineri Sorry for inconvenience and thanks for reminder. 
I will post on redfish forum.
