### ISSUE TITLE
RSV tool does not accumulate  type definitions discovered in processed xml files for use in child pages, relies solely on $metatdata supplemented by the page being validated

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#38]
Based on some tests here it appears that the tool assumes that $metadata page list is the only source of Schemas files to process.  However if the basic schemas are reviewed one discovers a number of edmx:Reference at the top of every schema xml files. ComputerSystem_v1.xml for example has  20 Reference definitions each including Uri and Namespace.

My issue = **What should the Service-Validator do with these references inside of fetched xml schema?**
Can these locally override the Uri of a schema also referenced in $metadata?
Can $metadata leave out schemas that are referenced in one of the files that are referenced by $metadata? Should the schema references add to the schema list?

The spec is not totally clear to me - 
_Redfish Services shall expose a metadata document describing the service at the "/redfish/v1/$metadata" resource. This metadata document describes the resources available at the root, and references additional metadata documents describing the full set of resource types exposed by the service._

**Comment by mraineri** [comment]
From OData, the $metadata document is just a schema file. Some OData implementations will put their entire schema within the $metadata file.

From a payload response perspective, any time we use `@odata.type` or `@odata.context`, we need the namespace included in the $metadata file so that a generic client can resolve the reference (since clients will start from /redfish/v1/$metadata). The $metadata resource does not need to include all nested namespaces; it just needs the first level of inclusion for clients to resolve the lookup.

For example, in the EthernetInterface schema, it references the ComplexTypes found in IPAddresses. Ultimately since the type and context properties for the resource point to the namespaces in EthernetInterface, $metadata does not need to include IPAddresses.

**Comment by mraineri** [comment]
Effectively when you build a data model for a given service, you start with $metadata and then pull in references from other schemas as needed. For example, with EthernetInterface, a client would start by referencing the EthernetInterface XML file, and afterwards it will use the references in that file to pull other external dependencies.

**Comment by tomasg2012** [comment]
The Service Validator does use the references held in each file, it's just that when it grabs a new resource, it will almost always use the given context in the resource.  In the given situation that there isn't a context (which should always exist in anything but ReferenceableMembers/Autoexpanded items), it wouldn't attempt to proceed.  If I recall, in those two cases, it will use the context of its parent and traverse the type its parent designates it.

In the situation it does use references is when there are base types and entities that exist deeper in the reference chain, for example, almost every Resource on a service will have Resource_v1.xml as a reference, and thus will follow that when doing type generation.

**Comment by jbobzin-insyde** [comment]
Tomas - Not sure I completely understand your comment.
But I can give a concrete example - 
1) Assume $metadata has edmx:Reference for type A but NOT for type B. Type A is used in ServiceRoot but Type B is not.
2) A.xml has edmx:Reference with Uri and Namespace=B, and, uses B in a Type= clause
3) In my test, current version of the tool will throw an error because it cannot find schema for B.  This is a false error. 

For implementation strategy, I suggest tool should process the edmx:Reference list in newly loaded schema.xml page, and, if unique schema not seen previously is found, it should be downloaded using Uri and added to the schema store.

This logic addition opens the possibility of inconsistent definitions. For example two edmx:reference with same Namespace and different Uri.  This could be flagged as error during the lookup search for already seen definitions mentioned above.

**Comment by jbobzin-insyde** [comment]
But I am not 100% confident about my conclusions about current behavior.  If you believe that my example will not generate an error in tools's current logic I will prepare a better test tomorrow.

**Comment by tomasg2012** [comment]
I'm trying to picture the situation you gave me and I'm having a bit of trouble.  The program works by forking off a resource like a tree: grabs the first resource, ServiceRoot and validates (in function validateSingle), which then returns its links.  In the validation of a single URI, it should grab the $metadata just once and follow its fragment, and that xml and refs is used for the entire validateSingle function.  

Perhaps a diagram might be in order, because based on your example, as long as a BaseType= of B exists in the ServiceRoot xml or its references, it should function, and I see no reason for Type A to be acknowledged.

**Comment by jbobzin-insyde** [comment]
Open Chassis_v1.xml or ComputerSystem_v1.xml in a editor.  Examine the top 25% of the file and note the edmx:Reference items. They look like items from $metadata and indeed they are intended to supplement $metadata Reference list.  Is this supplementation working in the current version of the program?  In my test it is not. These Reference items in xxxx_v1.xml appear to be ignored.  I would like you to confirm the expected behavior. If we disagree I can do more testing and send clear example of output.

**Comment by tomasg2012** [comment]
I've completely emptied the Metadata except for say, ComputerSystem, and the program responds normally and without errors.  Where it doesn't find references in Metadata when grabbing a Resource, it reports an ERROR to the log and jumps to local schema.

When validating a ComputerSystem, however, it seems perfectly capable of following BaseTypes and verifying entities.  So this error in particular might need a log to demonstrate.

**Comment by jbobzin-insyde** [comment]
Embarrassed to say I cannot duplicate this issue in a new careful test.  I will start over and try to figure out what send me down this wrong path.

**Comment by jbobzin-insyde** [comment]
OK, I figured it out.  I just needed to look deeper.

Here is the test situation -
1. $metadata has no edmx:Reference for StorageCollection 
2. StorageCollection is however edmx:Reference defined in ComputerSystem_v1.xml
3. The page /redfish/v1/Systems/<name>/ has property "Storage": which has type StorageCollection with ContainsTarget=True.
4. RSV is fine with the checking of the ComputerSystem page and has no error on Storage property. The txt log shows the file StorageCollection_v1.xml being downloaded.
5. But RSV throws an error (below) when later processing the actual page of type StorageCollection  referenced by the Storage: property in the System page. This page has @odata.context of "/redfish/v1/$metadata#StorageCollection.StorageCollection"

Conclusion - Locally defined schema references are used inside the file in which they are defined but not in child files.  I propose this is not correct interpretation of the spec language. Instead a Type definition must be found in $metadata or the xml files referenced by $metadata, or the files these files reference and so on to encompass the entire tree of type definitions.



*ERROR on /redfish/v1/Systems/<name>/Storage*

`ERROR - SchemaURI missing reference link: /redfish/v1/$metadata StorageCollection.StorageCollection
ERROR - SchemaURI unsuccessful: /redfish/v1/$metadata
ERROR - Something went wrong
Traceback (most recent call last):
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 174, in getSchemaDetailsLocal
    filehandle = open(SchemaLocation + '/' + Alias + suffix, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/StorageCollection_v1.xml'
ERROR - validateURI: No schema XML for #StorageCollection.StorageCollection StorageCollection`

**Comment by jbobzin-insyde** [comment]
In the message above the formatting characters I used in the Uri did not work as expected. Be assured there is a system name 

/redfish/v1/Systems/nameofsystem _Storage Property has_ link to_
/redfish/v1/Systems/nameofsystem/Storage

**Comment by jbobzin-insyde** [comment]
Misunderstanding. RSV is correct. Closed.
