### ISSUE TITLE
Too many arguments for format string

### ISSUE THREAD

**Issue by PuwenHsiao** [DMTF/Redfish-Service-Validator#382]
Reported by VSCode (pylint), error message: Too many arguments for format string
traverseService.py
Line 437:
`traverseLogger.warn("Incorrect content type 'text/xml' for file within service".format(URILink))`

Line 601:
`traverseLogger.warn('@odata.id should not have a fragment'.format(odata_id))`

LIne 611:
`traverseLogger.warn('@odata.id should have a fragment'.format(odata_id))`

**Comment by mraineri** [comment]
Fixed in latest PR
