### ISSUE TITLE
Redfish Service Validator Issue related to Task Instance

### ISSUE THREAD

**Issue by GINUGEORGE** [DMTF/Redfish-Service-Validator#384]
**I am using** github.com/DMTF/Redfish-Service-Validator **to validate redfish service if it is in adherence with the schema.** 

**But I am facing an error as mentioned below:**

For the Task Collection URI /redfish/v1/TaskService/Tasks , there are four instances or members under it and for one particular instance, when a GET request is issued by the validator, the validator throws the below error -

**ERROR - Members[2]: GET of resource at URI /redfish/v1/TaskService/Tasks/2 returned HTTP 202. Check URI.**

**But as per the DMTF Specification in the link below :**

https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.8.0.pdf 

• The Task Monitor is used by the Client to get the Response Body of the actual operation. 
• If the operation has been accepted for processing, a 202 can be returned. This mean a Task has been started to complete the request.
• The “Location” header is set to the URI of a Task Monitor. 
• There may also be a “Retry-After” header to specify the amount of time the client should wait before querying the Task Monitor 
• When the operation is finished, the Response Body will be returned with the content the same as if the Request had been synchronous. 

**So , is this a Redfish Service Validator issue ? Please clarify.**

**Comment by mraineri** [comment]
There is a distinction to be made between the "Task resource" and the "Task Monitor".

The members of the TaskCollection found in the TaskService will all reference Task resources. In this case, when you perform a GET on the Task resource, you should get back a 200 OK along with the Task representation.

The Task Monitor is a special URI for the requestor of the original operation. You can find the Task Monitor URI within the Task resource itself, but the semantics about responding with a 202 Accepted until the operation is complete is purely unique to the Task Monitor URI.

In addition to the HTTP status differences, there is another key difference in behavior between the Task resource and Task Monitor.
- Performing GET operations on a Task resource that represents a completed task will still return the Task resource itself.
- Performing GET operations on a Task Monitor for a completed task will return the response for the original operation that generated the task.

**Comment by GINUGEORGE** [comment]
Currently, when the Task Resource is queried, we are returning 

**202 Accepted** as the **Http Status Code** as long as the **corresponding Task is executing** 

and

 **200 OK** as the **Http Status Code** once the Task is **finished execution**.

Do we need to return **200 OK** even when the **Task** is in **running state** ? Please clarify.

**Comment by mraineri** [comment]
That's correct; there are really only two cases where 202 Accepted is valid for the response:
- A client invokes an operation that will take a long time (such as an action or a POST to a collection) and a task is needed to monitor the operation.
- A client invokes a GET on the Task Monitor URI (NOT the Task resource) it received from the original operation that produced the task, and that task is still running.
