### ISSUE TITLE
odata.Type value showing in response

### ISSUE THREAD

**Issue by SelviRaju** [DMTF/Redfish-Service-Validator#392]
Hi All,

Normally in response showing response as e.g #Service.v1_2_1.Service.
while displaying in odayatype under action in below 2 cases which one we can use.
case 1:
        #Service.v1_2_1.Service.TimeSupport
case 2 : 
     #Service.v1_2_1.TimeSupport

Please mention which one to support in response.

Thanks & Regards,
R.Selvi

**Comment by mraineri** [comment]
None of those are valid; there shouldn't be an @odata.type property within Actions.

With actions, the namespace info is encoded in the action name itself. For example:

```
{
    "Actions": {
        "#ComputerSystem.Reset": { ... }
    }
}
```

The pattern OData lays out with actions is they're in the form of "#Namespace.ActionName". So, the above example would direct a client to look in the "ComputerSystem" namespace for the action called "Reset".

**Comment by SelviRaju** [comment]
But Redfish schema mentioned as #Service.v1_2_1.TimeSupport,Please confirm schema having typo problem.

shall i add as #Service.TimeSupport

**Comment by mraineri** [comment]
Sorry, I'm a bit confused by what you're saying.

`@Redfish.OperationApplyTimeSupport` is the name of a property. In OData, you can add annotations into payloads that are in the form of `PropName@Namespace.Term` where...
- `PropName` is the name of the property being annotated; if not present, then the annotations is for the entire object
- `Namespace` is the namespace containing the annotation definition; for Redfish-defined annotations, we put them all in the `Redfish` namespace, which is defined in RedfishExtensions_v1.xml
- `Term` is the name of the annotations term

For `@Redfish.OperationApplyTimeSupport`, this is an annotation for the object that it's in, and you can find the term definition in the `Redfish` namespace, and the term is called `OperationApplyTimeSupport`. Inside of that annotation is `@odata.type`, which further describes the format of that annotation, which follows the `OperationApplyTimeSupport` object definition defined in the `Settings.v1_2_0` namespace.

**Comment by mraineri** [comment]
As a complete example:
```
{
    "Actions": {
        "#ComputerSystem.Reset": {
            "target": "/redfish/v1/Systems/1/Actions/ComputerSystem.Reset",
            "@Redfish.OperationApplyTimeSupport": {
                "@odata.type": "#Settings.v1_2_0.OperationApplyTimeSupport",
                <properties defined in OperationApplyTimeSupport within the Settings.v1_2_0 namespace>
            }
        }
    }
}
```

**Comment by SelviRaju** [comment]
Thank you for the confirmation.i updated as per above example

**Comment by jautor** [comment]
@SelviRaju does that resolve your question?  Can we close this issue?

**Comment by SelviRaju** [comment]
Yes,Please close this issue.thank you for the support.
