### ISSUE TITLE
MaintenanceWindowStartTime during reset Action

### ISSUE THREAD

**Issue by SelviRaju** [DMTF/Redfish-Service-Validator#393]
Hi All,

We are doing Action based on maintenancewindowstart time,which means when time reached it will do the action.
so based on this we can creat multiple action with multiple time,so during the get call we have to show the maintenancewindowstart time.

Here our doubt is which value time value we have to show in maintenancewindowstart  in GET call.whether completed time,or last created time.

![image](https://user-images.githubusercontent.com/60085258/91423930-ca894480-e876-11ea-817f-3bacdef2c127.png)

Thanks & regards,
R.Selvi

**Comment by SelviRaju** [comment]
Hi,

Can you please check this issue and confirm .

Thanks & Regards,
R.Selvi

**Comment by mraineri** [comment]
It really depends on what it is you support. If you only support specifying an action can be performed at the start of the maintenance window, then you should only show "AtMaintenanceWindowStartTime".

Think of it this way: a client is going to provide the "@Redfish.OpperationApplyTime" term in the action request; the values you list in "SupportedValues" will be the enums your action supports. If you don't support "Immediate" in the client request, then don't list "Immediate".

**Comment by SelviRaju** [comment]
Hi,

I got the your point,my clarification is in maintenancewindowstart time which value we have to show if we are created 2 tasks based on time.

whether we have to show first task time or second task time.

Thanks & Regards,
R.Selvi

**Comment by mraineri** [comment]
I'm not sure what you mean; only one task will be created, and that Task will be for the client request on the action itself. What's the second task you're thinking of?

**Comment by ShirleyHebyH** [comment]
Jeff,
What our clarification is if the User wants to Schedule more than one task for the same resource at different times for example Give a System Reset sometime 4P.M and say at 8P.M. Now we don't have a provision in the Schema as MaintenanceWindow is not an array but on object with only 1 value for MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds.

So if User issues the second task, we should discard it if the first task still hasn't completed or can accept both and perform one by one but there is no provision to display these times in the GET call.

Do you think in future, you can add this provision ? 

Thanks

**Comment by mraineri** [comment]
Currently that's not really in scope for how the maintenance window is defined. Usually maintenance windows are per-determined periods of time where a system is allowed to be taken down for a maintenance operation.

What you're looking at is more akin to a user defined Job, where a client requests a Job to perform an operation at a specific time (as in not related to the maintenance window). So, two different clients can create their own Jobs to perform a reset at the exact time they want.

**Comment by SelviRaju** [comment]
while two clients creating their job with their time,but in maintenance window we have to show particular client time,so in that case which time we can show.

Please confirm me this changes,also thi psoperty is string as per schem,so possible to show only one value.
