### ISSUE TITLE
Review the current options in the tool to see what we can remove

### ISSUE THREAD

**Issue by mraineri** [DMTF/Redfish-Service-Validator#395]
There are currently lots of options that have grown over time with this tool. Many are probably not useful anymore, and others can be consolidated with other options. Would like to see what we can remove, or perhaps add intelligence to the tool so some options don't need to be specified.

**Comment by tomasg2012** [comment]
Along with the options list, will have what functions in the tool can be parsed out into its own separate code files

# config
'-c':  Necessary for independent config files.  Handling of this can be moved to a py file.

# Validator based options
'--payload': Useful for prototyping
'--logdir': 
'--nooemcheck':  
'--csv_report':  Potentially redundant with tohtml.py function in README (X)

# Verbosity settings
# With these, maybe only -v should be necessary, but debug_logging especially helps for users to report issues.
# Can potentially combine all three (-v, -vv, -vvv)
'-v': (X)
'--debug_logging' (X)
'--verbose_checks': (X)

# Host Info
# Any/All of this could be relegated to the redfish library, which am unsure if it has any capacity for taking its own host info via a file
# Can we have a quick/easy way to pass a basic configuration to a redfish service via this library?
# If not, moving this to a mandatory host config file would make most of this per service moot, simplifying the tool's interface
'--ip'
'--timeout'
'--nochkcert':  This can maybe be normalized in some way, needs research.  
'--nossl':  Could combine this into ip, if that's how we want to go about it.  It shouldn't be neceesary to use on any officially supported Redfish service, so i'd rather keep it
'--ca_bundle':  
'--http_proxy'
'--https_proxy'
'--desc': Mostly for labeling the host, so would go here likely as well.

# Auth (also for redfish library)
# Might be able to combine this all
'--forceauth':  This is a dangerous option in and of itself and probably shouldn't exist, but allows any Authentication on HTTP (which is unsupported.  Combine below maybe) (X)
'--authtype':  This could combine User/Password and Token in the same way Payload does, i.e. (--authtype Basic User:Password, --authtype Token TokenValue) 
'--user', '--password':  As long as we have BASIC authtype, this would be needed, but can be combined (X)
'--token': Can be combined above (X)

# More options
'--cache':  Largely available as a useful tool for quickly prototyping fixing payloads.  maybe just needs to be explained better.  Redundant for individual payloads with --payload

# Options specific to how to handle the service's payloads and schemas
'--uri_check':  Deprecated with seperate tool (X)
'--version_check':  This could be deprecated with some sort of message filtering (X)
'--localonly': Each of the following 3 options is potentially combineable, as they are not mutually exclusive (X)
'--preferonline' (X)
'--service' (X)
'--linklimit':  Consider the difference between linklimit and sample (X)
'--sample':

# Options for schemas on the client
# Noted that this could be parsed away from the validator client itself     
'--schemadir'
'--schema_pack'
'--suffix':  This is extremely vestigial from very old Redfish services.  If we stop supported the initial "1.0" schema or automatically detect their necessity, this can be removed

**Comment by tomasg2012** [comment]
```
    argget = argparse.ArgumentParser(description='DMTF tool to test a service against a collection of Schema, version {}'.format(tool_version))

    # base tool
    argget.add_argument('-v', '--verbose', action='count', default=0, help='Verbosity of tool in stdout')
    argget.add_argument('--logdir', type=str, default='./logs', help='directory for log files')
    argget.add_argument('--debugging', action="store_true", help='Output debug statements to text log, otherwise it only uses INFO')

    # host info
    argget.add_argument('-i', '--ip', type=str, help='Address of host to test against, using http or https (example: https://123.45.6.7:8000)')
    argget.add_argument('-u', '--user', type=str, help='Username for Authentication')
    argget.add_argument('-p', '--password', type=str, help='Password for Authentication')
    argget.add_argument('--description', type=str, help='sysdescription for identifying logs, if none is given, draw from serviceroot')
    argget.add_argument('--nochkcert', action='store_true', help='Ignore check for HTTPS certificate')
    argget.add_argument('--forceauth', action='store_true', help='Force authentication on unsecure connections')
    argget.add_argument('--authtype', type=str, default='Basic', help='authorization type (None|Basic|Session|Token)')
    argget.add_argument('--token', type=str, help='bearer token for authtype Token')

    # validator options
    argget.add_argument('--payload', type=str, help='mode to validate payloads [Tree, Single, SingleFile, TreeFile] followed by resource/filepath', nargs=2)
    argget.add_argument('--nooemcheck', action='store_const', const=True, default=None, help='Don\'t check OEM items')
    argget.add_argument('--schema_directory', type=str, default='./SchemaFiles/metadata', help='directory for local schema files')
    argget.add_argument('--schema_origin', type=str, default='local', help='Preferred location of schemafiles.  Can be local, for a local directory, online or only from the host service itself [local, online, service]')
    argget.add_argument('--schema_pack', type=str, help='Deploy DMTF schema from zip distribution, for use with --localonly (Specify url or type "latest", overwrites current schema)')

    args = argget.parse_args(argslist)
```

Here is an updated version of the arguments allowed by the tool.  Currently doesn't have any `--config` option as it is refactored.  Things to note:

- Proxy settings, timeout and certificate bundle options removed, still doing research if this can be done externally.
- linklimit and sample currently being reworked
- Unsure how to handle deprecating options, are people expected to learn new names??

**Comment by mraineri** [comment]
This is looking good so far. I think as far as deprecating options go, we could bump the major version to indicate significant change and compatibility issues and folks will simply need to adjust to the new arguments. Certainly can discuss this more with others.

Some other thoughts:
* I think we can remove `nochkcert`; since this is really a test tool, I expect most users will be testing on systems with self-signed certs or other implementation-specific certs, so we might be able to always treat this as `true`.
* Would it be possible to remove `schema_origin` and `schema_pack` and have the tool try to figure out the best path for getting schema files on its own? It could follow logic like: First try getting schema files based on the contents of $metadata, then try local cached copies, then try downloading from the DMTF site.

**Comment by mraineri** [comment]
Closing; resolved in latest merge
