### ISSUE TITLE
Fails with "SyntaxWarning:" error

### ISSUE THREAD

**Issue by Arul-Jothi** [DMTF/Redfish-Service-Validator#397]
Test run of "Redfish-Service-Validator" leads error as listed below at end of the completion for this validator run, but able to get the logs under /tmp/logs/. 

**Error Message Print** 

Validation has failed: 255 problems found
/Redfish-Service-Validator/traverseService.py:350: SyntaxWarning: "is" with a literal. Did you mean "=="?
  inService = scheme is '' and netloc is ''
/Redfish-Service-Validator/traverseService.py:350: SyntaxWarning: "is" with a literal. Did you mean "=="?
  inService = scheme is '' and netloc is ''
/Redfish-Service-Validator/traverseService.py:351: SyntaxWarning: "is" with a literal. Did you mean "=="?
  scheme = ('https' if UseSSL else 'http') if scheme is '' else scheme
/Redfish-Service-Validator/traverseService.py:352: SyntaxWarning: "is" with a literal. Did you mean "=="?
  netloc = ConfigIP if netloc is '' else netloc
/Redfish-Service-Validator/traverseService.py:582: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if fragment is '':
/Redfish-Service-Validator/traverseService.py:598: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if fragment_odata is '':
/Redfish-Service-Validator/traverseService.py:604: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if fragment is not '':
/Redfish-Service-Validator/traverseService.py:608: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if fragment_odata is not '':

**Comment by jautor** [comment]
Agree that these should be changed to use "==" instead of "is".  I assume these are all working as-is because the comparisons are to empty strings or common/short string values, such that Python is caching those such that "is" and "==" both pass.

**Comment by gkeishin** [comment]
Would be great to have fixes for this failure. I'm also seeing this in my run recently.

**Comment by mraineri** [comment]
@gkeishin @Arul-Jothi can either of you please test the "Python38-Fixes" branch I created to verify it resolves the issue for you?

**Comment by gkeishin** [comment]
@mraineri Looks good to me.. Here is a snippet of the run`
```
$ git clone https://github.com/DMTF/Redfish-Service-Validator/ -b Python38-Fixes
Cloning into 'Redfish-Service-Validator'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 1709 (delta 33), reused 36 (delta 18), pack-reused 1645
Receiving objects: 100% (1709/1709), 882.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1110/1110), done.
```


```
$ cd Redfish-Service-Validator

$ python3 RedfishServiceValidator.py --ip xx.xx.xx.xx:443 --nochkcert --authtype=Session -u root -p xxxxxxxx --logdir logs/ --debug_logging
```

```
*** /redfish/v1/JsonSchemas/redfish-payload-annotations
         Type (#JsonSchemaFile.v1_0_2.JsonSchemaFile), GET SUCCESS (time: 0.107172)
         PASS

*** /redfish/v1/JsonSchemas/redfish-schema
         Type (#JsonSchemaFile.v1_0_2.JsonSchemaFile), GET SUCCESS (time: 0.101202)
         PASS
Elapsed time: 0:04:37
Counter({'skipOptional': 4323, 'pass': 4013, 'metadataNamespaces': 1975, 'passGet': 224, 'warnDeprecated': 208, 'serviceNamespaces': 62, 'invalidPropertyValue': 38, 'warningPresent': 29, 'passAction': 11, 'optionalAction': 8, 'repeat': 1, 'unverifiedComplexAdditional': 1})
Validation has succeeded.
```

**Comment by Arul-Jothi** [comment]
@mraineri 
Issue is not exist in "Python38-Fixes". Snippet of run below, 

Counter({'skipOptional': 13803, 'pass': 8740, 'passGet': 516, 'failComplex': 255, 'warnDeprecated': 157, 'metadataNamespaces': 138, 'serviceNamespaces': 63, 'repeat': 58, 'invalidPropertyValue': 38, 'warningPresent': 25, 'passAction': 17, 'optionalAction': 11, 'reflink': 1, 'err.StorageCollection.StorageCollection': 1, 'failProp': 1, 'unvalidated': 1, 'problemResource': 1})
getSchemaDetails() -> CacheInfo(hits=79, misses=559, maxsize=64, currsize=64)
callResourceURI() -> CacheInfo(hits=887, misses=607, maxsize=128, currsize=128)
Validation has failed: 257 problems found
[root@xxxx openapi]#
