### ISSUE TITLE
Failed to verify the Redfish.ExcerptCopy

### ISSUE THREAD

**Issue by lindappwu** [DMTF/Redfish-Service-Validator#399]
It seems the tool need to do special checking for sensor excerpt?

![image](https://user-images.githubusercontent.com/11567488/114786537-21268e80-9d33-11eb-9712-2442ebfb2359.png)

**Comment by mraineri** [comment]
@lindappwu to verify the issue is resolved with the latest changes

**Comment by lindappwu** [comment]
Issue closed with the latest changes. Thanks!
