### ISSUE TITLE
Program Fails with latest version of beautifulsoup4

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#41]
Setting up a new computer for a new person.
1. Downloaded and installed Python 3.6.1 (been using Python 3.5)
2. did pip3 install -r requirements.txt with no errors
The system under test does not have valid trusted certificate
$metadata page looks good using Chrome

Can you tell - Is this Some problem with Python?

---Jeff

`G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator>python RedfishServiceValidator.py
System Info: S2600WFO
RedfishServiceValidator Config details: ('https://192.168.100.209', 'user:root', 'metadata', 'no CheckCert', 'Attempt for Online Schema')
Start time: 06/12/17 - 15:22:01

*** ServiceRoot, /redfish/v1
C:\Python36\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python36\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
SchemaURI missing reference link: /redfish/v1/$metadata ServiceRoot.ServiceRoot
SchemaURI unsuccessful: /redfish/v1/$metadata
File not found metadata/ServiceRoot_v1.xml:
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 740, in <module>
    sys.exit(main(sys.argv))
  File "RedfishServiceValidator.py", line 632, in main
    success, counts, results, xlinks = validateURITree('/redfish/v1', 'ServiceRoot')
  File "RedfishServiceValidator.py", line 568, in validateURITree
    validateSingleURI(URI, uriName, expectedType, expectedSchema, expectedJson, parent)
  File "RedfishServiceValidator.py", line 483, in validateSingleURI
    propResourceObj = rst.ResourceObj(uriName, URI, expectedType, expectedSchema, expectedJson, parent)
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 297, in __init__
    SchemaFullType, SchemaType)
NameError: name 'SchemaFullType' is not defined`

**Comment by jbobzin-insyde** [comment]
Further notes - 
This host system is Windows 10
Test of redfishtool had no problems

My guess is Beatifulsoup issue?

**Comment by jbobzin-insyde** [comment]
Installed 3.5.2 instead. Did not fix. here is the txt file. 
[ComplianceLog_06_12_2017_155314.txt](https://github.com/DMTF/Redfish-Service-Validator/files/1069353/ComplianceLog_06_12_2017_155314.txt)

**Comment by tomasg2012** [comment]
Correct, this is pretty much that issue, though the exception it generates should not exist and halt the program.  I've also noticed that Python spits out a lot of untrusted certificate issues on my Windows python environment vs Ubuntu but I'm sure its a python version difference I should account for.

**Comment by tomasg2012** [comment]
You may run a command like this (or one appropriate for your system) to restore functionality until we change the docs or fix the code in response.

% pip3 uninstall beautifulsoup
% pip3 install -Iv beautifulsoup==4.5.3

**Comment by tomasg2012** [comment]
Could you run "pip3 list" on your system?

**Comment by jbobzin-insyde** [comment]
after running the pip3 commands above the problem is gone.
suggest improving readme instructions regarding requirements.txt 
because readme suggests
    pip3 install -r requirements.txt
which is not currently working

**Comment by tomasg2012** [comment]
Thank you, I will.

**Comment by jbobzin-insyde** [comment]
duplicate
