### ISSUE TITLE
Validatory --ip option question

### ISSUE THREAD

**Issue by gkeishin** [DMTF/Redfish-Service-Validator#413]
```
  -i IP, --ip IP        Address of host to test against, using http or https
                        (example: https://123.45.6.7:8000)
```

Earlier release it use to work without explicitly adding https or https in the IP , now looks like its actually asking user to append it as  like a URL. Is this going to be like this ahead  ?

**Comment by tomasg2012** [comment]
I believe from this point forward the tool specifically complains about a lack of http or https, and will error out.  Though maybe it might be beneficial to default it to https, as of now it's a hard change, and that might immediately break some users scripts.  I am unsure if that's the better option, but the tool may act differently if it automatically assumed something like that.  This is an issue with deprecating a ton of options and maybe it ought to be explicit or hide them for the sake of warning about deprecation...

**Comment by mraineri** [comment]
> 
> 
> ```
>   -i IP, --ip IP        Address of host to test against, using http or https
>                         (example: https://123.45.6.7:8000)
> ```
> 
> Earlier release it use to work without explicitly adding https or https in the IP , now looks like its actually asking user to append it as like a URL. Is this going to be like this ahead ?

Yes, part of the reason we bumped the major version was to refactor many arguments in the tool based on usage over time to help simplify the interface and minimize the amount of arguments needed. It will be like this going forward.

**Comment by gkeishin** [comment]
sure thing.. Thanks @mraineri @tomasg2012
