### ISSUE TITLE
Unique Resource Path should match case defined in schema URI

### ISSUE THREAD

**Issue by J2Hilland** [DMTF/Redfish-Service-Validator#420]
The "Unique Resource Path" part of @odata.id in the payload should match
1) the URI required in the schema, including upper/lower case
2) the URI that was just used, including upper/lower case
and it should probably throw a warning for now if they do not match 

Technically, according to RFC 3986, only the scheme and authority portions of the URI are case insensitive.  The resource path should technically be case sensitive.  But it’s bad practice to have two URIs that only differ by case and I would hope Redfish never does this (though there is currently no restriction technically).  And I sure wouldn’t want the service to do a redirection to the “proper” URI if a client used the wrong case.  Nor would I want a 404 just because the client used the wrong case. Would these behaviors be flagged as warnings too?

**Comment by mraineri** [comment]
There's a separate tool for URI validation; we do this in the Redfish URI Validator here: https://github.com/DMTF/Redfish-URI-Validator

**Comment by mraineri** [comment]
Latest PR adds this support
