### ISSUE TITLE
Resource Type issue

### ISSUE THREAD

**Issue by Kavo21** [DMTF/Redfish-Service-Validator#427]
Hi 

I used the tool (Version: 2.0.4) for checking Schema compliance and in the report, there is a failAdditional.complex errors in /redfish/v1/Managers/Self/NetworkProtocol.

![image](https://user-images.githubusercontent.com/34242547/136971549-6daf20cf-a70e-430f-bc7f-8028844312dd.png)

The resource is following the https://redfish.dmtf.org/schemas/v1/ManagerNetworkProtocol.v1_6_0.json
and the resource type is Manager Network Protocol.v1_6_0.Manager Network Protocol. My question is that why used the ManagerNetworkProtocol.v1_5_0.ManagerNetworkProtocol to validate the property. Is it correct?

![image](https://user-images.githubusercontent.com/34242547/136971906-a0fa0213-1407-4e8e-bcab-7e1c37d946da.png)

**Comment by mraineri** [comment]
What is in the payload of the resource in question? From a CSDL perspective, some definitions only exist in one namespace and are inherited in newer versions. That particular definition highlighted in the error message is defined in the ManagerNetworkProtocol.v1_5_0 namespace.

Remember, this tool operates on CSDL and follows strict CSDL grammar; JSON Schema is a different schema language published by the DMTF and has its own versioning rules and format.
