### ISSUE TITLE
Shall @odata.id is necessary property in Oem resource?

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Service-Validator#441]
Hi,

As stated in the title, due to use the 2.0.1 version tool not observer the error about the @odata.id.
However, a lot of errors about that Oem does't contain the @odata.id be presented on report with 2.0.6 version of tool.

Example:
1. /redfish/v1/
ERROR - Ami: EntityType resource does not contain required @odata.id property, attempting default /Ami
"Oem": {
    "Ami": {
        "@odata.type": "#AMIServiceRoot.v1_0_0.AMIServiceRoot",
        "Configurations": {
            "@odata.id": "/redfish/v1/Oem/Ami/Configurations"
        },
        "InventoryDataStatus": {
            "@odata.id": "/redfish/v1/Oem/Ami/InventoryData/Status"
        },
        "RtpVersion": "13.03"
    }
},

2. /redfish/v1/UpdateService
ERROR - AMIUpdateService: EntityType resource does not contain required @odata.id property, attempting default /AMIUpdateService
ERROR - BMC: EntityType resource does not contain required @odata.id property, attempting default /BMC
    "Oem": {
        "AMIUpdateService": {
            "@odata.type": "#AMIUpdateService.v1_0_0.AMIUpdateService",
            "FlashPercentage": null,
            "PreserveConfiguration": {
                "AUTOMATION_ENGINE": false,
                "Authentication": false,
                "EXTLOG": false,
                "FRU": false,
                "IPMI": false,
                "KVM": false,
                "NTP": false,
                "Network": false,
                "REDFISH": false,
                "SDR": false,
                "SEL": false,
                "SNMP": false,
                "SSH": false,
                "Syslog": false,
                "WEB": false
            },
            "UpdateStatus": null,
            "UpdateTarget": null
        },
        "BMC": {
            "@odata.type": "#AMIUpdateService.v1_0_0.BMC"
        }
    },

Attach report for your reference.
[ConformanceHtmlLog_11_25_2021_173415.zip](https://github.com/DMTF/Redfish-Service-Validator/files/7608032/ConformanceHtmlLog_11_25_2021_173415.zip)

Thanks.

**Comment by mraineri** [comment]
In a resource (defined by EntityType in CSDL), yes, `@odata.id` is mandatory.

However, from the examples you provided, you may be defining your OEM extension incorrectly. When you're defining the OEM object, it needs to be a "ComplexType" definition since it's an embedded object in a resource and not a standalone resource. So, make sure your type definitions for "AMIServiceRoot.v1_0_0.AMIServiceRoot" and "AMIUpdateService.v1_0_0.AMIUpdateService" are "ComplexType" definitions and not "EntityType" definitions.

**Comment by FelixD999** [comment]
Got it!
Thanks for your reply.
