### ISSUE TITLE
report failure for resources with different type than specified in the schema

### ISSUE THREAD

**Issue by arahimanshaik** [DMTF/Redfish-Service-Validator#458]
property in response:

`"SubTasks": "/redfish/v1/TaskService/Tasks/task97bdb532-fa10-43da-b998-d1fad927ad0d/SubTasks"`

Std err:

*** /redfish/v1/TaskService/Tasks/task967aabd1-753b-4048-8bcb-cbbf6c18c61c
         Type (Task.v1_5_1.Task), GET SUCCESS (time: 0:00:00.391549)
This complex object Object should be a dictionary or None, but it's of type <class 'str'>...
SubTasks: EntityType val is null/absent, not testing...
          FAIL...
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 227, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "RedfishServiceValidator.py", line 166, in main
    success, counts, results, xlinks, topobj = validateURITree(currentService, '/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "/home/odimra/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/odimra/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/odimra/Redfish-Service-Validator/validateResource.py", line 334, in validateURITree
    returnVal = validateURITree(service, link_destination, uriName + ' -> ' + link.Name, parent=parent, allLinks=allLinks, inAnnotation=link.InAnnotation)
  File "/home/odimra/Redfish-Service-Validator/validateResource.py", line 304, in validateURITree
    link_destination = link.Value.get('@odata.id', link.Value.get('Uri'))
AttributeError: 'str' object has no attribute 'get'

report failure for resources with different type than specified in the schema file, and resume validating next resource instead of failing the run.

**Comment by mraineri** [comment]
Could you please provide the contents of "/redfish/v1/TaskService/Tasks/task967aabd1-753b-4048-8bcb-cbbf6c18c61c" (or one of the other tasks)? From the exception, it's not clear to me if there's an issue with `@odata.type`, or an object in the resource, or if the resource isn't valid JSON.

**Comment by tomasg2012** [comment]
From a glance, the NavigationProperty provided may have used a string instead of an object i.e. 

`"Systems": "/redfish/v1/Systems"`
vs
```"Systems": {
"@odata.id": "/redfish/v1/Systems"
}```

From this point forward the program should probably have fail-safes between validating links, and wrap it in a try-catch

**Comment by arahimanshaik** [comment]
Sorry for the delay.
correct @tomasg2012. That's what exactly we has in payload.
@mraineri  here is the sample payload.

```
{
    "@odata.type": "#Task.v1_5_1.Task",
    "@odata.id": "/redfish/v1/TaskService/Tasks/task01d3e46d-941f-40b4-adda-fa8241adfb25",
    "@odata.context": "/redfish/v1/$metadata#Task.Task",
    "Id": "task01d3e46d-941f-40b4-adda-fa8241adfb25",
    "Name": "Task task01d3e46d-941f-40b4-adda-fa8241adfb25",
    "Message": "The task with id task01d3e46d-941f-40b4-adda-fa8241adfb25 has started.",
    "MessageId": "TaskEvent.1.0.3.TaskStarted",
    "MessageArgs": [
        "task01d3e46d-941f-40b4-adda-fa8241adfb25"
    ],
    "NumberOfArgs": 1,
    "Severity": "OK",
    "TaskState": "Running",
    "StartTime": "2022-02-11T11:02:06.248955391Z",
    "EndTime": "0001-01-01T00:00:00Z",
    "TaskStatus": "OK",
    "SubTasks": "/redfish/v1/TaskService/Tasks/task01d3e46d-941f-40b4-adda-fa8241adfb25/SubTasks"
    "TaskMonitor": "/taskmon/task01d3e46d-941f-40b4-adda-fa8241adfb25",
    "Payload": {
        "HttpHeaders": [
        ],
        "HttpOperation": "",
        "JsonBody": "",
        "TargetUri": ""
    },
    "Oem": {
    }
}

```

We were not redfish-compliant with respect to this payload. So the whole point we use service validator is to make a report of how compliant is our system wrt to the schema provided.
anyhow, we have fixed 'SubTasks' to object type now.
It would be better if he have right exception handlings inscribed.
