### ISSUE TITLE
Allow header should not contain POST in /redfish/v1/AccountService/Roles

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Service-Validator#461]
Hi,
I have questions about the POST /redfish/v1/AccountService/Roles.
Refer the 66.1.Privilege model of Specification DSP0266_1.11.2 :
"A service may define additional custom roles. A service may allow users to create custom roles through a POST to the Roles resource collection."
But I was fail in validator report and the Error Message show "Allow header should NOT contain POST for RoleCollection.RoleCollection".
Could you explain inconsistent of them? I didn't understand why the report would have this error.
![Ask issue](https://user-images.githubusercontent.com/85208691/157163828-9dbd87ed-33c1-4abf-bd88-7896afe830fa.JPG)

Thanks,
Felix

**Comment by mraineri** [comment]
This looks like a bug in the RoleCollection schema. It's currently marked as "Insertable=false", meaning the service validator will fail any service that allows for roles to be added. The tool looks like it's behaving correctly, so we'll need a correction in the DSP8010 bundle to address this.

**Comment by mraineri** [comment]
DSP8010 2022.1 has been published with a fix for this; can you please retest with the updated schema bundle?

**Comment by FelixD999** [comment]
Yes, I updated schema bundle then test reports no longer seeing this issue.
Thanks for your help!

**Comment by mraineri** [comment]
Closing; new schema resolves the issue
