### ISSUE TITLE
Possible BeatifulSoup compatibility issue

### ISSUE THREAD

**Issue by edtanous** [DMTF/Redfish-Service-Validator#465]
On current master, on a debian-based on linux system, running the service validator results in an exception being thrown

```
Setting up service...
Service could not be started: AttributeError("'NoneType' object has no attribute 'find_all'")
```

Digging into this a bit shows that on the version of packages I'm running, BeautifulSoup seems to not want to deal with tag namespaces;  Clearly this worked at some point, but seems to be broken now.  A quick search for relevant sources didn't turn up much on the topic.

I'm running the latest versions of both lxml and beatifulsoup4
```
pip show beautifulsoup4 lxml                                                                 ✔ 
Name: beautifulsoup4
Version: 4.10.0
Summary: Screen-scraping library
Home-page: http://www.crummy.com/software/BeautifulSoup/bs4/
Author: Leonard Richardson
Author-email: leonardr@segfault.org
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: soupsieve
Required-by: 
---
Name: lxml
Version: 4.8.0
Summary: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Home-page: https://lxml.de/
Author: lxml dev team
Author-email: lxml-dev@lxml.de
License: BSD
Location: /usr/local/google/home/edtanous/.local/lib/python3.9/site-packages
Requires: 
Required-by: 
```

The patch attached below makes this work on my system, essentially by removing the "edmx:" tag from all find and find_all lookups.  In theory this shouldn't have any consequences to users of old beautifulsoup versions, but I'm not quite sure.  If this works, I can get it submitted as a PR, but I'm looking for some input if there's a better way to handle this, or if anyone knows any more background here.

```
From 03eeb1136ec600b21dacd257a0012bde107f2df5 Mon Sep 17 00:00:00 2001
From: Ed Tanous <edtanous@google.com>
Date: Thu, 17 Mar 2022 11:05:41 -0700
Subject: [PATCH] Remove beautifulsoup namespace lookups

Signed-off-by: Ed Tanous <edtanous@google.com>
---
 common/catalog.py |  8 ++++----
 common/schema.py  | 10 +++++-----
 2 files changed, 9 insertions(+), 9 deletions(-)

diff --git a/common/catalog.py b/common/catalog.py
index de5ac29..d1442e2 100644
--- a/common/catalog.py
+++ b/common/catalog.py
@@ -177,11 +177,11 @@ class SchemaDoc:
         self.classes = {}
         self.alias = {}
 
-        edmxTag = self.soup.find("edmx:Edmx", recursive=False)
-        reftags = edmxTag.find_all("edmx:Reference", recursive=False)
+        edmxTag = self.soup.find("Edmx", recursive=False)
+        reftags = edmxTag.find_all("Reference", recursive=False)
         self.refs = {}
         for ref in reftags:
-            includes = ref.find_all("edmx:Include", recursive=False)
+            includes = ref.find_all("Include", recursive=False)
             for item in includes:
                 uri = ref.get("Uri")
                 ns, alias = (item.get(x) for x in ["Namespace", "Alias"])
@@ -200,7 +200,7 @@ class SchemaDoc:
 
         cntref = len(self.refs)
 
-        parentTag = edmxTag.find("edmx:DataServices", recursive=False)
+        parentTag = edmxTag.find("DataServices", recursive=False)
         children = parentTag.find_all("Schema", recursive=False)
         self.classes = {}
         for child in children:
diff --git a/common/schema.py b/common/schema.py
index d2bf442..943f50e 100644
--- a/common/schema.py
+++ b/common/schema.py
@@ -134,8 +134,8 @@ def getSchemaDetailsLocal(SchemaType, SchemaURI, config):
 
         # get tags
         soup = BeautifulSoup(data, "xml")
-        edmxTag = soup.find('edmx:Edmx', recursive=False)
-        parentTag = edmxTag.find('edmx:DataServices', recursive=False)
+        edmxTag = soup.find('Edmx', recursive=False)
+        parentTag = edmxTag.find('DataServices', recursive=False)
         child = parentTag.find('Schema', recursive=False)
         SchemaNamespace = child['Namespace']
         FoundAlias = SchemaNamespace.split(".")[0]
@@ -186,10 +186,10 @@ def getReferenceDetails(soup, metadata_dict=None, name='xml'):
     includeTuple = namedtuple('include', ['Namespace', 'Uri'])
     refDict = {}
 
-    maintag = soup.find("edmx:Edmx", recursive=False)
-    reftags = maintag.find_all('edmx:Reference', recursive=False)
+    maintag = soup.find("Edmx", recursive=False)
+    reftags = maintag.find_all('Reference', recursive=False)
     for ref in reftags:
-        includes = ref.find_all('edmx:Include', recursive=False)
+        includes = ref.find_all('Include', recursive=False)
         for item in includes:
             uri = ref.get('Uri')
             ns, alias = (item.get(x) for x in ['Namespace', 'Alias'])
-- 
2.35.1.894.gb6a874cedc-goog
```

**Comment by mraineri** [comment]
If you make a PR I can at least do testing in my environment. I'm running the same version of beautifulsoup4, but an older lxml (4.6.3).

**Comment by mraineri** [comment]
Just tried updating lxml to the same version you have; no problems seen. I am using Python3.8 (will try 3.9).

**Comment by edtanous** [comment]
Done #468

**Comment by edtanous** [comment]
I'm on python 3.9.9, Debian 12, but we've gone through the package differences that could matter.  I did try backing up to BS 4.6 and as far back in lxml as I could go that still compiled, and that still shows the issue.  I have no idea what else could be different.  Another thing I did try is that the soup docs suggest that you should explicitly select a backend (ie lxml-xml instead of just xml) in the constructor, to ensure you get the same results in all environments,  but that didn't seem to have an effect.

**Comment by edtanous** [comment]
I'm starting to have a suspicion that my dev system flew too close to the bleeding edge of master, and inadvertently saw a lxml bug, because after an apt upgrade for minor revisions last night.... the problem has completely gone away as quickly as it appeared.

I somewhat wonder if my system got caught up in the fix for this:
https://bugs.launchpad.net/lxml/+bug/1915613

and some regression it caused.  Not sure I'll ever know.  In terms of the patchset, looking up the un-namespaced version of the tag seems simpler, and relies on less internal mechanics of beautifulsoup to work properly, but the potential for breaking things probably isn't worth the cost of the change.

**Comment by tomasg2012** [comment]
A simple solution is to simply check if the tag acquired with `edmx:Edmx` is None.  `If parentTag is None` then attempt to grab the tag without the namespace `Edmx`

**Comment by mraineri** [comment]
At least for how Redfish uses schema files, I'd be okay with the proposed change. I don't see a strong need to call out the namespace explicitly as long as getting `Edmx` is always going to be equivalent to getting `edmx:Edmx`.

**Comment by edtanous** [comment]
I'll get the commit message on the patchset cleaned up and it should be good to merge.

**Comment by mraineri** [comment]
Closing; merged fix for this
