### ISSUE TITLE
Does the latest validator not support check the "AttributeRegistry"?

### ISSUE THREAD

**Issue by haitaoso** [DMTF/Redfish-Service-Validator#487]
In the old version(example version 2.0.1) validator, I can find the function "validateAttributeRegistry" in the file "validateSpecial.py".
This function checks some properties values matching to the registry attributes or not. Such as the "Attributes" property of the "Bios" schema.
When I use the 2.0.1 version validator to test my redfish service, it reports errors:
```log
ERROR - Attributes.ADDDCEn has a value of Disabled. This is not an expected value from the Enumeration: ['0x1', '0x0']
```
But, when I use the latest version validator to test my redfish service, it reports all passed, no errors.
If the latest validator no longer supports checking the "AttributeRegistry", can you tell me why it was removed?

Thanks

**Comment by mraineri** [comment]
It was taken out when we did the major rework for 2.0.0, but added back in version 2.0.7. As long as you have the registry referenced from the MessageRegistryFile resource, it will step into each of the locally referenced registries (from the "Uri" property) to verify their contents.

**Comment by mraineri** [comment]
At least using the latest version of the tool (2.1.5), I was able to verify on one of the systems I have that it does follow the Uri property in MessageRegistryFile resources to validate the registry's contents (one of which being an AttributeRegistry on the system I tested).
