### ISSUE TITLE
Failed to lauch the validator that version is 2.1.5

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#494]
I cannot launch validator (version is 2.1.5) in linux environment, but it works normally when I switch to 2.1.4. 
Here is the error message:
```
Setting up service...
Service could not be started: TypeError("redfish_client() got an unexpected keyword argument 'proxies'",)
Try running the Redfish Protocol Validator to ensure the service meets basic protocol conformance
```

**Comment by mraineri** [comment]
Please check the version of the Redfish Python library you have installed. We added a feature to have manual proxy overrides, and that's dependent on a newer version of the library. We updated requirements.txt with the new dependency (`redfish>=3.1.5`).

You can check the version with `pip show redfish`. If you have something older than 3.1.5, you can update it with `pip install redfish -U`.

**Comment by JojoWu19** [comment]
@mraineri , I can launch validator after `pip3 install redfish -U`, so I close this.
Thank you.
