### ISSUE TITLE
Access fail for resource RedfishExtensions_v1.xml

### ISSUE THREAD

**Issue by vincent-tang1** [DMTF/Redfish-Service-Validator#498]
from tag 2.1.6 or others version, after running execution file, seems like, sometimes can not get resource RedfishExtensions_v1.xml from official DMTF server and keep retry it, detail as below, although it can finish whole test procedure, not sure if it has other impact? thanks your attention.

Setting up service...
Attempt 1 of /redfish/v1/
Response Time for GET to /redfish/v1/: 0.8934055699937744 seconds.
Attempt 1 of /redfish/v1/SessionService/Sessions
Response Time for GET to /redfish/v1/SessionService/Sessions: 0.28226744099811185 seconds.
Attempt 1 of /redfish/v1/$metadata
Response Time for GET to /redfish/v1/$metadata: 0.88536910500261 seconds.
Constructing metadata...
Attempt 1 of https://redfish.dmtf.org/schemas/RedfishExtensions_v1.xml
Retrying https://redfish.dmtf.org/schemas/RedfishExtensions_v1.xml [HTTPSConnectionPool(host='172.17.10.242https', port=443): Max retries exceeded with url: /redfish.dmtf.org/schemas/RedfishExtensions_v1.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22f6d7b7f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))]
Attempt 2 of https://redfish.dmtf.org/schemas/RedfishExtensions_v1.xml
Retrying https://redfish.dmtf.org/schemas/RedfishExtensions_v1.xml [HTTPSConnectionPool(host='172.17.10.242https', port=443): Max retries exceeded with url: /redfish.dmtf.org/schemas/RedfishExtensions_v1.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22f6d74048>: Failed to establish a new connection: [Errno -2] Name or service not known',))]
Attempt 3 of https://redfish.dmtf.org/schemas/RedfishExtensions_v1.xml
....

**Comment by mraineri** [comment]
Are there other schema files being downloaded from the DMTF site when you run the tool? Do those also have issues?

Are you able to reach the DMTF site from your test environment?

**Comment by tomasg2012** [comment]
The `xml-gets` branch may fix this by proxy, but it isn't pulled into the codebase.  Mike, do you think it's plausible?  The fix uses requests instead of the redfish library to get those xmls.

**Comment by vincent0526** [comment]
> Are there other schema files being downloaded from the DMTF site when you run the tool? Do those also have issues?
Yes, all other schema files can successfully download to SchemaFiles folder, and  no this kind issue.

> Are you able to reach the DMTF site from your test environment?
Yes, my environment can reach it

**Comment by mraineri** [comment]
@vincent0526 were you able to try out the branch Tomas suggested? It's been incorporated into the main branch, so if not, you can try again with the latest version of the tool.

**Comment by mraineri** [comment]
Closing; no updates about the issue...
