### ISSUE TITLE
Edm.Duration regex does not include all formats

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/Redfish-Service-Validator#499]
The current regex pattern for Edm.Duration does not include weeks or years for duration, double check the ISO spec used by Redfish Spec to see if this is okay.  

Refer to ISO 8601.

**Comment by mraineri** [comment]
We did deviate a bit from ISO8601 intentionally; there is ambiguity in ISO8601 regarding the duration of a month (is it strictly calendar based or could it be exactly 30 days) and a year (do you always consider the leap year length). The Redfish spec calls out the exact format, and it doesn't allow for weeks, months, or years.

**Comment by mraineri** [comment]
7/8: From today's discussion, this is as expected based on how the Redfish Specification is. We want to cap the units at "days" for Redfish's usage.
