### ISSUE TITLE
Seeing Error in validateDatetime

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#50]
Latest Version shows "Malformed DateTimeOffset" error based on this property in LogEntry received from service under test:
"Created": "2017-06-14T11:49",

Checked the source but do not understand what is wrong. Is tool expecting more data? Perhaps Z plus offset?

The Logentry example in Public Mockup http://redfish.dmtf.org/redfish/v1/mockup/841 
has this example string
"Created":  "2012-03-07T14:44",
Also http://redfish.dmtf.org/redfish/v1/mockup/842 and others

**Comment by jbobzin-insyde** [comment]
ECMA spec at https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1
states in 15.9.1.15 that reduced strings are acceptable, namely YYYY-MM-DDTHH:mm
and full string YYYY-MM-DDTHH:mm:ss.sssZ is not required.

**Comment by tomasg2012** [comment]
I've noticed this error come and go from time to time, but the regex pattern I use hasn't changed, and is based on what the spec provides, if I recall.  There is currently an issue on DMTF/spmf on the mockups and their validation issues, which includes some of these errors.

**Comment by tomasg2012** [comment]
Should this require a more relaxed regex?

**Comment by jbobzin-insyde** [comment]
Yes, I am pretty sure this is a mockup error.  I did not see this specifically mentioned in the issue you created.

If nobody contradicts I will close.

**Comment by jbobzin-insyde** [comment]
The tool is following the English text of the spec, the mockups are not.

**Comment by jbobzin-insyde** [comment]
But the spec text seems to create a redundant situation because LogService has DateTimeLocalOffset.

But this other field is R/W and could change I guess.

**Comment by mraineri** [comment]
At least the way I'm interpreting the spec, I also think our mockups are wrong. I think we should discuss this in the next meeting.

**Comment by jbobzin-insyde** [comment]
moved issue to spmf
