### ISSUE TITLE
Windows GUI won't load config file

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#502]
The "Load Config" option doesn't appear to work - and need to check if the command line args are being passed through as well.

**Comment by mraineri** [comment]
@jautor I may need to work with you directly on this; this works normally on my system (both under Windows with the built EXE file and Linux).

**Comment by jautor** [comment]
Closing - the .EXE was out of date / sync with my clone, properly updating resolved the issue.
