### ISSUE TITLE
`Links` object implemented as an array isn't marked as an error

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#516]
Implementation wrongly placed an array of links as the value of `Links`, but this was not flagged as an error:

~~~json
{
   "Links": [ 
      {
          "@odata.id": "/redfish/v1/URI..."
      },
     {
         "@odata.id": "/redfish/v1/URI2"
     }]
}
~~~

I would have expected at least a type-mismatch error for `Links` (array vs object).

**Comment by mraineri** [comment]
This is the same issue as #497; can we close this as a duplicate?

**Comment by jautor** [comment]
Yes, close as duplicate.
