### ISSUE TITLE
No-Internet Mode - SPMF confirms ServiceMode not behaving as expected

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#52]
Hi Tomas,

Long discussion of Redfish use in no-Internet shop during Tuesday meeting. Some notes here - https://github.com/DMTF/spmf/issues/2118 . This issue is not closed but I am establishing this issue  under validator as a discussion spot for no-Internet Validator test.

My take-away - SPMF consensus is Validator's ServiceMode implementation is not currently enforced correctly.    When ServiceMode is True, and the Validator encounters a Uri that is off-system, this Uri should be ignored. Not an error but not used. They want the intelligent client to depend upon $metadata Uri only. 

Current Insyde test system has modified $metadata with no off-system references.  All of the schema in the $metadata are available local. But the Validator goes crazy in no-Internet test with multiple exceptions because there are multiple Uri="http://redfish.dmtf.org/schemas/v1/..." references inside the local schemas.

SPMF does not want to require implementers to edit every schema file. If it is possible, they want the client to be smart. And when client is configured for ServiceMode it should find everything local.

At this time I am not sure how they will recommend client get the 3 odata schema locally.
http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.*****
But it seems most likely that $metadata will have include entry to deliver local Uri to client.

If you have comments and concerns Mike and I can take these back to larger group.

**Comment by tomasg2012** [comment]
This sounds perfectly reasonable, I actually just encountered this just before this issue was posted, as my setup used ServiceMode but had no hard drive schema to fall back to in the scenario you just described.

In terms of the current implementation, it should be an easy fix.

**Comment by jbobzin-insyde** [comment]
No in previous discussions it was confirmed that $metadata has to supply Uri for schema defining every type actually used or Validator should throw an error. Reference to a type in included Schema, without definition in any Schema file in $metadata, but never used in JSON should be a warning event as this is not actually fatal to client.

Myself I think the Uri inside the Schema files are a feature of Odata that Redfish does not really embrace fully.  And these internal-to-schema reference Uri cause more trouble than benefit.

What should Validator do if the Uri inside a schema points to a file with xml content different from the Uri to the same name at $metadata ? This is currently allowed and can lead to very odd inconsistent behavior and tough bugs.

But that is just my opinion.

**Comment by tomasg2012** [comment]
That is true, I've noticed differences between two different XML files that could cause issues.  I will address this for Thursday.

**Comment by mraineri** [comment]
PR merged
