### ISSUE TITLE
ERROR RetriesExhaustedError cause tool stop

### ISSUE THREAD

**Issue by RogerWei0220** [DMTF/Redfish-Service-Validator#520]
Version: 2.2.1

We found that tool will stop if URI have some issue, and no html report created on this situation. 
Is it possible to catch this exception and let html report created anyway?
![20221020_1](https://user-images.githubusercontent.com/116244021/196852054-b1f2e934-1d7e-41b3-8f20-47c1bd218fa7.PNG)

**Comment by mraineri** [comment]
It's likely something in the payload of the response is causing the exception. Can you please provide what the service is returning for "/redfish/v1/Fabrics/NVLinkFabric"?

**Comment by tomasg2012** [comment]
From a glance at that code, it's attempting to get a status code from a unsuccessful callResourceURI.  It's old code that uses "success" instead of Exception wrapping, so line 113 would need to check if success is true.

**Comment by mraineri** [comment]
@RogerWei0220 were you able to collect the info requested? There is an open PR that has a change Tomas is referring to, but it would be good to get confirmation about things before assuming his fix will address your issue.
