### ISSUE TITLE
When Constructing metadata, Got [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by HanCJiang** [DMTF/Redfish-Service-Validator#521]
![image](https://user-images.githubusercontent.com/93564769/197423378-13b8ea98-7c3e-40f2-bd1b-a00d10a898ee.png)
Is it possible to apply this patch to solve this problem?
<pre>
diff --git a/redfish_service_validator/traverse.py b/redfish_service_validator/traverse.py
index 22dad7e..31c198f 100644
--- a/redfish_service_validator/traverse.py
+++ b/redfish_service_validator/traverse.py
@@ -165,7 +165,7 @@ class rfService():
             startTick = datetime.now()
             mockup_file_path = os.path.join(config['mockup'], URLDest.replace('/redfish/v1/', '', 1).strip('/'), 'index.json')
             if not inService:
-                req = requests.get(URLDest, proxies=self.ext_proxies)
+                req = requests.get(URLDest, proxies=self.ext_proxies, verify=False)
                 content = req.json if not isXML else req.text
                 response = rf.rest.v1.StaticRestResponse(Status=req.status_code, Headers={x:req.headers[x] for x in req.headers}, Content=req.text)
             elif config['mockup'] != '' and os.path.isfile(mockup_file_path): 
</pre>

**Comment by mraineri** [comment]
Yes, feel free to make a pull request with the change.

**Comment by mraineri** [comment]
Closing; PR merged
