### ISSUE TITLE
Mandatory Property Error

### ISSUE THREAD

**Issue by SelviRaju** [DMTF/Redfish-Service-Validator#526]
Hi All,

For Power Subsystem showing mandatory property as below

![image](https://user-images.githubusercontent.com/60085258/209794554-91082714-afc3-404f-8e55-c8498585fe3c.png)

But in validator thorwing error for redundancy group

![image](https://user-images.githubusercontent.com/60085258/209794647-8def6927-0794-4cef-948d-5fb872b1fc24.png)

![image](https://user-images.githubusercontent.com/60085258/209794766-1b47fed1-a26a-49ab-a67a-fb7ad34fe0b2.png)

Please confirm whether Redundancy group as mandatory if yes where we can confirm.

Thanks & Regards,
R.Selvi

**Comment by jautor** [comment]
You'll see the mandatory ("required" term in JSON schema) properties for the `RedundancyGroup` in the Redundancy schema referenced by PowerSubsystem.

If your PowerSubsystem resource contains a `PowerSupplyRedundancy` property, then yes, the `RedundancyType`, `MinNeededInGroup`, `Status`, and `RedundancyGroup` are all required properties.  

If your resource does NOT contain the `PowerSupplyRedundancy` property, then that would be a tool issue.  But that pattern of referenced definitions containing required properties appears in other places throughout the model, so I'd expect the tool is handling that correctly.

**Comment by mraineri** [comment]
@jautor is correct; it looks like your service is returning the "PowerSupplyRedundancy" property but is not providing "RedundancyGroup".

Can you please provide the payload for your resource to confirm? This looks like a conformance issue with the service.

**Comment by mraineri** [comment]
@SelviRaju were you able to follow up with your implementation to see what's in the payload?

**Comment by mraineri** [comment]
Closing; based on the existing details, this appears to be a service-side error.

If there are additional details that show otherwise, please reopen.
