### ISSUE TITLE
Error: URI does not match object IDs of resource chain with Oem

### ISSUE THREAD

**Issue by zkurzyns** [DMTF/Redfish-Service-Validator#537]
Hi. using the latest version of validator I am getting the error bellow.

 `ERROR - URI /redfish/v1/Managers/bmc/Oem/CompanyX/ServiceY does not match object IDs of resource chain`.

Redfish.Uris is constructed like this:

    <Annotation Term="Redfish.Uris">
      <Collection>
        <String>/redfish/v1/Managers/{ManagerId}/Oem/CompanyX/ServiceY</String>
      </Collection>
    </Annotation>

and the response to mentioned URL has properties defined like below:

    {
    "Id": "ServiceY",
    "Name": "Service Y",
    ...
    }

With other URIs where there is no Oem/<Company> subtree I do not see this error.

This error was not see with previous validator version.
is it regression or some of my schemas/implementation needs upgrade?

**Comment by mraineri** [comment]
@zkurzyns could you please try out the change from the referenced PR? It's available in the main branch (and version 2.2.5)

**Comment by mraineri** [comment]
Thanks; there's still additional cleanup we're doing now that addresses other false positives.

Are you able to try the branch `uri-remove-toggle`? This seems to address the other false positives I've been finding.

**Comment by zkurzyns** [comment]
Hi Mike, this branch `uri-remove-toggle` looks promising.
I do not get any false positive errors:)

**Comment by mraineri** [comment]
Thanks for checking! When you're comfortable with the changes, please close the issue.

**Comment by zkurzyns** [comment]
Thank you for quick and effective support :)
Closing this issue.
