### ISSUE TITLE
False positives for URI checking on public-rackmount1 mockup

### ISSUE THREAD

**Issue by mraineri** [DMTF/Redfish-Service-Validator#538]
From PR #536 

@tomasg2012 I'm seeing mixed results when I test against the public-rackmount1 mockup found in this bundle: https://www.dmtf.org/sites/default/files/standards/documents/DSP2043_2022.3.zip

Some of the failures are real and need to be fixed in the mockup, but these resources look correct to me (but the test report shows a "failRedfishUriStrict" error). Please take a look at the report for these URIs:

* /redfish/v1/Managers/BMC
* /redfish/v1/Managers/BMC/EthernetInterfaces/eth0/SD
* /redfish/v1/Chassis/1U/TrustedComponents/AC-RoT0/Certificates/DeviceCert
* /redfish/v1/Chassis/1U/TrustedComponents/TPM/Certificates/EKCert
* /redfish/v1/Systems/437XR1138R2/Bios/Settings
* /redfish/v1/Systems/437XR1138R2/Processors/FPGA1/AccelerationFunctions/Compression

[ConformanceLog_02_10_2023_203011.txt](https://github.com/DMTF/Redfish-Service-Validator/files/10712290/ConformanceLog_02_10_2023_203011.txt)

[ConformanceHtmlLog_02_10_2023_203011.html.txt](https://github.com/DMTF/Redfish-Service-Validator/files/10712292/ConformanceHtmlLog_02_10_2023_203011.html.txt)

**Comment by tomasg2012** [comment]
In reference to this, both ``/redfish/v1/Chassis/1U/Sensors/CPU1Temp`` and ``/redfish/v1/Systems/437XR1138R2/Certificates/contoso-subca`` are positives.  The rest however, I can attribute to a particular piece of code that toggles uri checking if the program detects an annotation:  however, I don't have any precedent for why this is the case, and removing it doesn't seem to cause issue.  It may need to be reworked.  For now, removing these lines fixes the issue.
