### ISSUE TITLE
First Test Of Changes - Not Working at All

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#54]
[no_service__mode_logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/1146957/no_service__mode_logs.zip)
[service_mode_logs.zip](https://github.com/DMTF/Redfish-Service-Validator/files/1146958/service_mode_logs.zip)

Internet Connection was normal

The Test of Service_mode=True is probably not valid because the service does not have local copy of the 3 odata xml files.  I will try to correct this tomorrow.  

But this omission should not have affected ServiceMode=False unless the reference inside the xml file are now ignored in that case as well.

**Comment by tomasg2012** [comment]
```
ERROR - Reference in a Schema not in metadata, this may not be compatible with ServiceMode
ERROR - References missing in metadata: ['StorageSystemCollection', 'StorageServiceCollection', 'EventService', 'OData', 'MessageRegistryFileCollection', 'JsonSchemaFileCollection', 'Capabilities', 'Message', 'Validation', 'TaskService', 'FabricCollection', 'Resource.v1_0_0']
```
The way the references are compounded now are that URIs given in the $metadata overwrite those in the Schema files.  This is the output that would show if you're missing references in your $metadata and don't overwrite these, as it stands, it can be ignored if this is fixed or if say, those particular schema are unneeded (such as StorageSystemCollection), but will likely still be reported...  However, I noticed the below message:


```
DEBUG - callingResourceURI: /redfish/v1/schema/ChassisCollection_v1.xml
DEBUG - 404, [200], {'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json', 'X-UA-Compatible': 'IE=11', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Date': 'Sat, 02 Jan 2016 03:25:28 GMT', 'Server': 'lighttpd/1.4.39', 'Status': '404', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked'},
TIME ELAPSED: 2.36688
DEBUG - SchemaURI unsuccessful: /redfish/v1/schema/ChassisCollection_v1.xml
DEBUG - ('ChassisCollection', '/redfish/v1/schema/ChassisCollection_v1.xml', 'metadata/ChassisCollection_v1.xml') /// This is where it attempts to find it locally after unable to grab it through the URI ///
ERROR - File not found in metadata for ChassisCollection: /// The file doesn't exist in folder 'metadata', therefore ///
ERROR - getPropertyDetails: InnerType could not be acquired,  ChassisCollection /// The type cannot be constructed ///
```

I noticed that there is a 404 for the URI specified "/redfish/v1/schema/ChassisCollection_v1.xml".  Am I mistaken?  This is consistent throughout the log in Service Mode for each NavigationProperty validated, the same is involved for Non-ServiceMode.

**Comment by jbobzin-insyde** [comment]
Some of the Problems here arising from recent patches in the Insyde source code which introduced bug. I will isolate and refile.
