### ISSUE TITLE
ComputerSystem MemorySummary/MemoryMetrics does not match object ID of resource

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Validator#541]
This appears to be a valid MemoryMetrics URI per the Redfish Data Model Specification: /redfish/v1/Systems/Partition0/MemorySummary/MemoryMetrics

But as of last night, top-of-tree of this tool flags this with `ERROR - URI /redfish/v1/Systems/Partition0/MemorySummary/MemoryMetrics does not match object ID of resource`

**Comment by mraineri** [comment]
@blakehilliard please try the branch in PR #539

**Comment by blakehilliard** [comment]
I've confirmed this is fixed today, presumably from that PR which was merged.

**Comment by mraineri** [comment]
Perfect, thanks for checking. Is it okay to close this issue now?

**Comment by blakehilliard** [comment]
Yes
