### ISSUE TITLE
About checking Settings resource URI

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Service-Validator#542]
We get below errors at last version:
```
...
1 failRedfishUriStrict errors in /redfish/v1/Systems/1/Bios/Pending
1 failRedfishUriStrict errors in /redfish/v1/Systems/1/Pending
...
```
Should tool skip these Settings resources? or standard schema files will be added the Settings resource URI into URIs?

**Comment by mraineri** [comment]
Yes, the tool is expected to skip testing URIs for resources found in `@Redfish.Settings`, `@Redfish.ActionInfo`, and `@Redfish.CollectionCapabilities`. In the spec, we list the exemption in the "Redfish-defined URIs and relative reference rules" clause:

> All other Redfish service-supported URIs shall match the resource URI patterns definitions, **except the supplemental resources that the @Redfish.Settings, @Redfish.ActionInfo, and @Redfish.CollectionCapabilities** payload annotations reference.

**Comment by JojoWu19** [comment]
@mraineri , get it and thank for your response.
