### ISSUE TITLE
URI checks flag false errors with @Redfish.Settings resources

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Validator#544]
As of today, I'm now getting this error `ERROR - URI /redfish/v1/Systems/Partition0/Bios/Settings does not match the following required URIs in Schema of Bios.v1_2_0.Bios`.

This is correct, and linked off /redfish/v1/Systems/Partition0/Bios with `@Redfish.Settings`

**Comment by mraineri** [comment]
@blakehilliard we just made a fix in 2.2.7; can you please try that? Issue #542 was opened the other day about this.
