### ISSUE TITLE
Tool should use later errata version of schema if found, replacing earlier version 

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#55]
$metadata should not have to carry every errata version of the schema, just the latest errata supported. 
Here is section of $metadata
<edmx:Reference Uri="/redfish/v1/schema/Resource_v1.xml">
        <edmx:Include  Namespace="Resource"/ 
        <edmx:Include Namespace="Resource.v1_0_3"/>
        <edmx:Include Namespace="Resource.v1_1_2"/>
        <edmx:Include Namespace="Resource.v1_2_1"/>
        <edmx:Include Namespace="Resource.v1_3_0"/>
    </edmx:Reference>

Here is error from tool

ERROR - Reference in a Schema not in metadata, this may not be compatible with ServiceMode
ERROR - References missing in metadata: ['Resource.v1_1_0']

My proposal - references to v1_1_x should use v1_1_y so long as y > x

**Comment by tomasg2012** [comment]
Noted.  This happens because a type within the Schema is specifically noted to be of BaseType Resource.v1_1_0.  Not sure how this affects odata and such in the grand scheme.

**Comment by jbobzin-insyde** [comment]
I cannot make statements about the Odata rules. But I believe it is the intent of Redfish designers, that errata updates supersede earlier versions of the same major/minor version.

So I say, even if the schema reference 1_2_0, if there is a 1_2_3 in the metadata, that should be used instead.

Lets wait and see if any disagrees with me next week.

**Comment by jbobzin-insyde** [comment]
This exact same issue was discussed and closed in July. I thought my position was supported in the discussion.

**Comment by tomasg2012** [comment]
It was, but the issue was resubmitted as #68, as an enhancement.  I can put it through as a more important request, or simply just start on doing enhancements as they've been on the back burner for longer than has been necessary.
