### ISSUE TITLE
Default Oem property not shown in the Redfish Validator tool 

### ISSUE THREAD

**Issue by Saravanans2001** [DMTF/Redfish-Service-Validator#555]
Hi,

I am using Redfish Validator tool(https://github.com/DMTF/Redfish-Service-Validator) for checking Schema compliance,

For Managers/Bmc URI, I could see the Response as below, which  does not contain **Oem.OpenBmc.Fan**      

![Screenshot from 2023-07-11 16-31-09](https://github.com/DMTF/Redfish-Service-Validator/assets/139228548/bf5bbd8c-2482-4cc4-b98e-909b72f07acd)

But in validator tool the table response is as shown below which contains  **Oem.OpenBmc.Fan**    

![Screenshot from 2023-07-11 16-31-30](https://github.com/DMTF/Redfish-Service-Validator/assets/139228548/219a754d-4ea1-4c19-a71b-53a101810bd0)

Both the response are for same payload and the report generated by the Validator tool, 
1. Whether it is normal behavior to show a property without the property actually present  in Redfish Response  ??
2. Here Fan is not available in Oem property, how it is taken in Validator tool ??

![Screenshot from 2023-07-11 18-45-28](https://github.com/DMTF/Redfish-Service-Validator/assets/139228548/50edfdfa-eccb-4756-a240-074a9afb34c7)

![Screenshot from 2023-07-11 18-45-12](https://github.com/DMTF/Redfish-Service-Validator/assets/139228548/b089fe56-ae22-4dde-ba17-bd7b2e568564)

**Comment by mraineri** [comment]
The report will show all properties defined in the schema file, and mark the "Exists" column with "No" if it's not in the payload. If there is a "Fan" property defined in the schema, then this looks correct to me.
