### ISSUE TITLE
Binary exits with exit code 1 when validation succeeds

### ISSUE THREAD

**Issue by mmasque** [DMTF/Redfish-Service-Validator#556]
Running `rf_service_validator` will return an exit code of 1 even when validation succeeds and the main function (`redfish_service_validator.RedfishServiceValidator:main`) returns an exit code of 0. 

As far as I can tell this is caused by the return type of the main function being a 3-tuple. The [specification](https://packaging.python.org/en/latest/specifications/entry-points/) for entry point setup says the linked function should return an integer (corresponding to the exit code) or None (then 0 is assumed). 

As the returned 3-tuple is used in the GUI the return type cannot simply be changed. I'm happy to open a PR after discussion on a fix!

**Comment by mraineri** [comment]
Yes, please feel free to make a fix!
