### ISSUE TITLE
Tool Terminates unexpectedly after getting error message back from Service under test

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#56]
This happens with ServiceMode True or False.
This implantation does not locally cache Base Message File.
Here is the end of the log. There is no exception or other indication why tool exited.
HTML file is not created. 

INFO - #StorageCollection.StorageCollection, Counter({'passGet': 1, 'skipOptional': 1, 'failProp': 1, 'err.Collection(Storage.Storage)': 1, 'skipOem': 1, 'pass': 1})
DEBUG - OrderedDict([('Members.Storage#0', ('/redfish/v1/Systems/BQWT64900010/Storage/1', False, 'Storage.Storage', '/redfish/v1/schema/Storage_v1.xml', OrderedDict([('@odata.id', '/redfish/v1/Systems/BQWT64900010/Storage/1')])))])
INFO - 
*** ServiceRoot -> Systems.Systems -> Members.ComputerSystem#0 -> Storage.Storage -> Members.Storage#0, /redfish/v1/Systems/BQWT64900010/Storage/1
DEBUG - 
*** None, False, False
DEBUG - True, OrderedDict([('@odata.type', '/redfish/v1/$metadata#Message.1.0.0.Message'), ('MessageId', 'Base.1.0.ResourceInStandby'), ('Message', 'The request could not be performed because the resource is in standby.'), ('Severity', 'Critical'), ('Resolution', 'Ensure that the resource is in the correct power state and resubmit the request.')]), 200

**Comment by tomasg2012** [comment]
Unfortunately, I've noticed something about the python logging into ComplianceLog, that if the program exits via an Exception that isn't caught, it ends abruptly without printing that exception.  What I can imagine is ValidateSingleURI encountered an error that wasn't wrapped in a try block, usually in the vein of trying to force a string out of a non-string type (this is a bad habit of mine, usually obj tend to have a __string__ attribute, but None does not), thus terminating.

If you could capture the stdout/stderr or view the console output personally at the end of the script run, it might reveal something...

**Comment by jbobzin-insyde** [comment]
Console Output below. I guess there is an exception shown.

Traceback (most recent call last):
  File ".\RedfishServiceValidator.py", line 793, in <module>
    sys.exit(main(sys.argv))
  File ".\RedfishServiceValidator.py", line 681, in main
    success, counts, results, xlinks = validateURITree('/redfish/v1', 'ServiceRoot')
  File ".\RedfishServiceValidator.py", line 610, in validateURITree
    success, linkCounts, linkResults, xlinks = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 589, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 610, in validateURITree
    success, linkCounts, linkResults, xlinks = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 589, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 610, in validateURITree
    success, linkCounts, linkResults, xlinks = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 589, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 610, in validateURITree
    success, linkCounts, linkResults, xlinks = executeLink(links[linkName], thisobj)
  File ".\RedfishServiceValidator.py", line 589, in executeLink
    linkURI, uriName + ' -> ' + linkName, parent=parent, allLinks=allLinks)
  File ".\RedfishServiceValidator.py", line 600, in validateURITree
    URI, uriName, expectedType, expectedSchema, expectedJson, parent)
  File ".\RedfishServiceValidator.py", line 504, in validateSingleURI
    propResourceObj = rst.ResourceObj(uriName, URI, expectedType, expectedSchema, expectedJson, parent)
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 395, in __init__
    fullType, SchemaURI=self.context)
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 223, in getSchemaDetails
    return getSchemaDetailsLocal(SchemaAlias, SchemaURI)
  File "G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator\traverseService.py", line 228, in getSchemaDetailsLocal
    uriparse = SchemaURI.split('/')[-1].split('#')
AttributeError: 'NoneType' object has no attribute 'split'
PS G:\_Redfish_git\Redfish-Service-Validator-public\Redfish-Service-Validator>

**Comment by jbobzin-insyde** [comment]
In discussion earlier this week, it was confirmed that Service root did not need to point to BaseMessage file and client should not expect.

But we plan to add this reference.

**Comment by tomasg2012** [comment]
Yeah, the lack of @odata.context returns None, which is not compensated for in the program.  I don't have any sort of handling for Messages and other such special cases in the program, so I don't think it'll handle them right.  I'll have to read the spec about these extra bits when they're traversed to in the program.

**Comment by jbobzin-insyde** [comment]
Yes, I agree that message needs @odata.context.  I will get this fixed and retest.

I am not sure if @odata.id is also needed and if so,  how to construct this property.
So I will leave that out for now.

**Comment by tomasg2012** [comment]
Here's a question, does a message like this come with a status code 200?  Should it be 400 or 404, 4xx?

**Comment by tomasg2012** [comment]
Additionally, should services have a way to test errors?  Maybe I'm missing the scope of how error messages should work...

**Comment by tomasg2012** [comment]
Not sure where this stands.  I believe it's been resolved in that the nature of missing context (I'm not sure if it needs context as a BaseMessage...), but additionally, a 200 should not return with a BaseMessage Error.
