### ISSUE TITLE
The test was not completed but got stuck.

### ISSUE THREAD

**Issue by xuwh6** [DMTF/Redfish-Service-Validator#560]
I can run the test with Tag 2.3.3 successfully.
[ConformanceLog_09_04_2023_102211.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12518506/ConformanceLog_09_04_2023_102211.txt)

But when I run the test with Tag 2.3.4 or master, the test will stop after output these info:
*** /redfish/v1/
Attempt 1 of /redfish/v1/
Response Time for GET to /redfish/v1/: 0.11497827991843224 seconds.
Schema not found for JobService.JobService
Schema not found for StorageSystemCollection.StorageSystemCollection
Schema not found for StorageServiceCollection.StorageServiceCollection
Schema not found for ActionStatus.v1_0_0.ActionStatus
[ConformanceLog_09_05_2023_110731.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12518514/ConformanceLog_09_05_2023_110731.txt)

The test was not completed but got stuck here.

Info after KeyboardInterrupt:
^CTraceback (most recent call last):
  File "RedfishServiceValidator.py", line 11, in <module>
    sys.exit(main())
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/RedfishServiceValidator.py", line 249, in main
    status_code, _, _ = validate()
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/RedfishServiceValidator.py", line 189, in validate
    success, counts, results, xlinks, topobj = validateURITree(currentService, '/redfish/v1/', 'ServiceRoot', expectedJson=jsonData)
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/validateResource.py", line 306, in validateURITree
    validateSuccess, counts, results, links, thisobj = validateSingleURI(service, URI, uriName, expectedType, expectedJson, parent)
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/validateResource.py", line 107, in validateSingleURI
    redfish_obj = catalog.RedfishObject(redfish_type, 'Object', parent=parent).populate(me['payload']) if redfish_type else None
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 1019, in populate
    populated_object.properties = {x: y.populate(sub_payload.get(x, REDFISH_ABSENT)) for x, y in populated_object.properties.items()}
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 1019, in <dictcomp>
    populated_object.properties = {x: y.populate(sub_payload.get(x, REDFISH_ABSENT)) for x, y in populated_object.properties.items()}
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 1047, in populate
    populated_object.properties[add_name] = object.populate(sub_payload.get(add_name, REDFISH_ABSENT))
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 921, in populate
    populated_object = RedfishObject(type_obj, populated_object.Name, populated_object.parent).populate(sub_payload, check=check, casted=True)
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 846, in __init__
    self.properties[prop] = RedfishObject(typ, prop, self)
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 842, in __init__
    for prop, typ in redfish_type.getProperties().items():
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 596, in getProperties
    for type_obj in self.getTypeTree():
  File "/home/xwh/Desktop/Redfish-Service-Validator/redfish_service_validator/catalog.py", line 541, in getTypeTree
    type_obj = self.owner.parent_doc.catalog.getSchemaDocByClass(my_type).getTypeInSchemaDoc(my_type)
KeyboardInterrupt
^C

**Comment by mraineri** [comment]
Can you provide the output of /redfish/v1/? Can you also try with `--debugging` added to the test and provide the log file?

**Comment by xuwh6** [comment]
output of /redfish/v1:
[output of redfish_v1.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12711658/output.of.redfish_v1.txt)

the log file with "--debugging":
[ConformanceLog_09_25_2023_140150.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12711661/ConformanceLog_09_25_2023_140150.txt)

Thanks!

**Comment by mraineri** [comment]
Unfortunately that's not giving me much more detail... Based on your earlier trace, I'm wondering if it's getting stuck in a loop trying to parse the OEM schemas...

I'll see if I can make a branch to get more debug information to see what's going on here...

**Comment by xuwh6** [comment]
the log file with "--debugging" and "--nooemcheck":
[ConformanceLog_09_27_2023_100630.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12733623/ConformanceLog_09_27_2023_100630.txt)

It doesn't seem to have changed much.

**Comment by xuwh6** [comment]
Any update?

**Comment by xuwh6** [comment]
the log file use the branch "Fix560-Tool-Stuck" with "--debugging" and "--nooemcheck":
[ConformanceLog_11_01_2023_144234.txt](https://github.com/DMTF/Redfish-Service-Validator/files/13224178/ConformanceLog_11_01_2023_144234.txt)

**Comment by mraineri** [comment]
@xuwh6 would you be able to provide the schema files "AMIServiceRoot" and "AMIConfigurations"? It's possible "AMIConfigurations" is also part of the same file as AMIServiceRoot. There should be a "SchemaFiles" where the tool places all local copies of the schema files. From the output, it looks like the AMIConfigurations definition is creating a loop; ultimately this would indicate the schema is not defined properly and breaks CSDL schema rules, but if I can get a copy of the file, I can harden the tool to escape from this.

**Comment by xuwh6** [comment]
These file is *.xml file which are not supported to upload, I change them to *.txt. For your reference.
AMIServiceRoot：
[AMIServiceRoot_v1.txt](https://github.com/DMTF/Redfish-Service-Validator/files/13246123/AMIServiceRoot_v1.txt)

AMIConfigurations:
[AMIConfigurations_v1.txt](https://github.com/DMTF/Redfish-Service-Validator/files/13246135/AMIConfigurations_v1.txt)
