### ISSUE TITLE
Could not finish check because Policy

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Service-Validator#564]
After used version 2.3.6, tool cannot finish check and aborted validation with KeyError 'Policy'.
![policy](https://github.com/DMTF/Redfish-Service-Validator/assets/85208691/8db93369-9fd7-4fb4-84e2-56b8aad8cd53)
We tried a lower version (2.3.1) and it ran to completion, although there were errors at the same URL.
The log is as follows:
[ConformanceLog_09_27_2023_170928.txt](https://github.com/DMTF/Redfish-Service-Validator/files/12780559/ConformanceLog_09_27_2023_170928.txt)

May I know the meaning of KeyError "Policy" and how to successfully run the tool?

Thanks,
Felix

**Comment by mraineri** [comment]
It's likely more stringent about schema format with some of the updates we've done recently, most notably with enforcing the usage of arrays. I'm guessing there's a scheme reference to "Policy" somewhere that doesn't resolve. Are you able to provide copies of these schema file? They appear to be OEM not something I would find in DMTF publications.

**Comment by FelixD999** [comment]
Thanks for your answer.
Attached is the OEM schema file related to NmDomain.
[DMTF_554.zip](https://github.com/DMTF/Redfish-Service-Validator/files/12792198/DMTF_554.zip)

**Comment by mraineri** [comment]
There are quite a few CSDL issues I see in the schemas that need to be corrected. It would be good if the tool wouldn't crash in the first place, but as things stand with those schemas, they cannot be parsed properly.

At least specifically with some of the "Policy" types of properties, a few things stick out to me...

* In NmDomain_v1.xml, line 165 makes a type reference that doesn't resolve. The namespace `NmPolicy` doesn't contain a `Policy` EntityType. I suspect this is supposed to be `Collection(NmPolicy.NmPolicy)`.
* In NmThrottlingStatus_v1.xml, line 60, the type here is `Edm.String`. NavigationProperty terms cannot reference primitive types like this; they need to reference some sort of EntityType definition.
