### ISSUE TITLE
Redfish Service Validator is not checking or navigating the properties of a OEM schema when basetype is Resource.OemObject

### ISSUE THREAD

**Issue by manipk01** [DMTF/Redfish-Service-Validator#569]
Hi All,
 
For the oem schema mentioned below the Redfish Service Validator is not checking or not navigating the property of the oem schema.

<img width="806" alt="image" src="https://github.com/DMTF/Redfish-Service-Validator/assets/124661726/f8d444bd-082a-4cf0-a382-ae00368108db">

 
Above example schema is using basetype as Resource.OemObject. when i gave basetype as contoso.contoso Redfish Service validator is working fine and it is navigating to the property. 
 
Whether it is a tool issue or schema issue?
 
What is the usage of BaseType=Resource.OemObject?

File: 
[OemSample_v1.txt](https://github.com/DMTF/Redfish-Service-Validator/files/13504098/OemSample_v1.txt)

 
Thanks,
Mani P K

**Comment by mraineri** [comment]
Can you please provide the debug output of the tool and sample resource responses? The OEM schema you've provided does not look valid to me, and it looks like the service validator would not be able to perform inspections of the OEM extension.

"Resource.OemObject" is specifically used for the "Oem" object itself; not the contents of the OEM extension. The OEM extension ComplexType itself is not expected to have a base type pointing back to Resource.OemObject. It may be worth reviewing some simple OEM extension examples in the public-oem-examples mockup in DSP2043.

**Comment by mraineri** [comment]
"Resource.OemObject" is used to enforce expected typing for the OEM extensions. The "Oem" object definition has a bit of hardening to ensure the only contents of `"Oem": { }` are properly-defined OEM extension objects. This is enforced by this definition...

```
      <ComplexType Name="Oem">
        <Annotation Term="OData.AdditionalProperties" Bool="true"/>
        <Annotation Term="Redfish.DynamicPropertyPatterns">
          <Collection>
            <Record>
              <PropertyValue Property="Pattern" String="^[A-Za-z0-9_]+$"/>
              <PropertyValue Property="Type" String="Resource.OemObject"/>
            </Record>
          </Collection>
        </Annotation>
        <Annotation Term="OData.Description" String="The OEM extension."/>
        <Annotation Term="OData.LongDescription" String="This object represents the OEM properties.  The resource values shall comply with the Redfish Specification-described requirements."/>
      </ComplexType>
```

The above definition essentially states that "Oem can contain properties whose name matches `"^[A-Za-z0-9_]+$"` and stem from the OemObject definition". This is to ensure we don't have things like string properties inside of "Oem".

**Comment by mraineri** [comment]
Closing; no updates to debug the issue further.
