### ISSUE TITLE
Service Validator throws "Connection aborted" Error 

### ISSUE THREAD

**Issue by GinuGeorgeAMI** [DMTF/Redfish-Service-Validator#572]
**Redfish Service Validator Version Used : 2.3.7 and 2.3.8**

When I am trying to run the DMTF Redfish Service Validator against an application providing Redfish Service, I am getting the below mentioned error when it tries to query the initial Service Root Request(/redfish/v1/) :

**('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))**

![Screenshot 2024-01-22 232930](https://github.com/DMTF/Redfish-Service-Validator/assets/143481975/d1af4962-e43a-487b-ad98-38718885e976)

However, at that very time, when I try to query the Service Root Request(/redfish/v1/) or in that case any URI by either **using Postman or Curl** , I am able to get the proper response :

![Screenshot 2024-01-22 232504](https://github.com/DMTF/Redfish-Service-Validator/assets/143481975/a215d131-e069-46cf-90a0-fc0bb55f8fe2)

![Screenshot 2024-01-22 233222](https://github.com/DMTF/Redfish-Service-Validator/assets/143481975/1c53968a-cfe7-43c7-87ec-e72df795fca9)

Did anyone face this issue ? Please provide your inputs, if so, to fix it.

**Comment by mraineri** [comment]
Can you please provide the full exception trace? Can you also add `--debugging` and send the log file?

**Comment by GinuGeorgeAMI** [comment]
@mraineri As requested, I am attaching the log file

[ConformanceLog_01_23_2024_043553.txt](https://github.com/DMTF/Redfish-Service-Validator/files/14016354/ConformanceLog_01_23_2024_043553.txt)

Please take a look and do let us know.

**Comment by mraineri** [comment]
What happens when you try using curl on /redfish/v1/ without the `-u` argument?

The Service Validator won't pass credentials when doing initial inspection of /redfish/v1/ since that's expected to always be available for discovery purposes.

**Comment by mraineri** [comment]
Closing; no additional info provided. It would be good to test with the Protocol Validator to see if there are protocol-related issues with the service (like if it's requiring credentials on service root).
