### ISSUE TITLE
The default schema pack is lost

### ISSUE THREAD

**Issue by henbin** [DMTF/Redfish-Service-Validator#587]
Hi,
Does anyone encounter the default schema pack  in DMTF website is lost?

<img width="635" alt="image" src="https://github.com/DMTF/Redfish-Service-Validator/assets/21031064/552e8b37-a4fe-4f65-90af-49bdb8e47f90">

![image](https://github.com/DMTF/Redfish-Service-Validator/assets/21031064/7406b3ae-669b-428e-b37d-bfba5b64bce2)

Thanks.
Henbin.

**Comment by mraineri** [comment]
@robertkeyes the hardened "latest" link appears broken now

**Comment by mraineri** [comment]
@henbin the DMTF site was fixed; can you try again?

**Comment by henbin** [comment]
> @henbin the DMTF site was fixed; can you try again?

It's OK now. Thanks for your prompt response.
