### ISSUE TITLE
Tool must support both forms for odata.context 

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#63]
Redfish supports the use of both OData-defined formats for the @odata.context values, the tool currently supports the "Resource Type" format, but does not support the "Resource Path" format.  Both are valid Redfish and are in use.  While we recommend the Resource Type format (because it's simpler), implementations are free to use either.

**Comment by tomasg2012** [comment]
I've been having trouble and haven't returned to this issue, but I do have questions about these forms of context:

What exactly is SelectList?  I haven't seen it employed in the context of Redfish, is it picking particular properties that exists within that Schema file?  

The path to resource, I've seen it before but the current spec lacks an example, is it written as if it were a uri, or is written as a series of types?  If someone has implemented it, perhaps it could be explained as to how an odata program handles a context like that.

**Comment by tomasg2012** [comment]
Added with 8-10 PR
