### ISSUE TITLE
Schema file and version should be determined by @odata.type, not @odata.context

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#64]
Related to issue #63 

The schema file related to a payload should be determined using the @odata.type , not the @odata.context value.  The Context does not contain schema version information, which will be important for proper validation.  And determining the proper schema file is considerably more difficult if the implementation uses the ResourcePath style for @odata.context.

**Comment by tomasg2012** [comment]
@odata.context determines what XML schema file to find in a service's $metadata, while @odata.type picks the namespace inside the XML grabbed.  This does bring up the issue, yes, if the other style of context is implemented, so I'll be asking for what the other style implies and how it's supposed to be implemented.

**Comment by mraineri** [comment]
`@odata.type` needs to be used over `@odata.context`. `@odata.context` is really only every used by generic OData clients, so the service validator needs to just validate the `@odata.context` format and not use it for decoding.

**Comment by tomasg2012** [comment]
Added with 8-10 PR
