### ISSUE TITLE
Regex validation fails on valid 'RedfishVersion' in ServiceRoot

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#65]
Note that the tool is using pre-loaded regex values for UUID and date/time values.

The regex validation pattern pulled from CSDL for "RedfishVersion" in ServiceRoot appears to be correct, and validates using online regex checkers to a value of "1.0.0". But the tool marks this value as a malformed string failure (regex mismatch).  Tested on HPE ProLiant Gen9, multiple Dell implementations return identical or similar correct string values ("1.0.0", "1.0.2").

This may be caused by regex string conversion upon reading the CSDL - similar to an issued opened in SPMF regarding the conversion of CSDL strings to JSON schema.

**Comment by tomasg2012** [comment]
I've noticed a difference between some service schema and the publicly available schema located on redfish.dmtf.org via URL... I've seen Redfish version succeed in some occasions but fail on others based on this distinction, and I am unsure if it's a version release that gives a different Regex or some other issue?  I can bring up an example of this case.

**Comment by tomasg2012** [comment]
```<Annotation Term="Validation.Pattern" String="^\d+\.\d+\.\d+$"/>```
```<Annotation Term="Validation.Pattern" String="^\\d+\\.\\d+\\.\\d+$"/>```

These are two patterns that I've come across, where the former works but the latter draws an error, from ServiceRoot file v1.2.0 and v1.0.2 respectively

**Comment by jautor** [comment]
Ok, this makes more sense - the former is what I believe to be the correct form (and hopefully what is on dmtf.org as the latest version).

**Comment by jautor** [comment]
Further investigation leads this is likely a combination of old schema issues (fixed with later errata) and the implementation under test referencing the dot-form (1.0.0) of the original schema releases.

**Comment by tomasg2012** [comment]
I believe this has been resolved internally.
