### ISSUE TITLE
results logging - error on split when url is null or invalid

### ISSUE THREAD

**Issue by hohene** [DMTF/Redfish-Service-Validator#67]
RedfishServiceValidator.py, If the url is null (or invalid), we get an error trying to split the results for reporting the final counts in main().
Code pulled 8/2/2017.

Error:
```
1 exceptionPropCompliance errors in /redfish/v1/TaskService
Traceback (most recent call last):
  File "RedfishServiceValidator.py", line 815, in <module>
    sys.exit(main(sys.argv))
  File "RedfishServiceValidator.py", line 758, in main
    rsvLogger.error('{} {} errors in {}'.format(innerCounts[countType], countType, results[item][0].split(' ')[0]))
AttributeError: 'NoneType' object has no attribute 'split'
```
Workaround:
```
@@ -751,7 +755,11 @@ def main(argv):
         finalCounts.update(innerCounts)
         for countType in sorted(innerCounts.keys()):
             if 'problem' in countType or 'fail' in countType or 'exception' in countType:
-                rsvLogger.error('{} {} errors in {}'.format(innerCounts[countType], countType, results[item][0].split(' ')[0]))
+                try:
+                    rsvLogger.error('{} {} errors in {}'.format(innerCounts[countType], countType, results[item][0].split(' ')[0]))
+                except:
+                    rsvLogger.error('{} {} errors at {}'.format(innerCounts[countType], countType, item))
+                    rsvLogger.debug(" results {} ".format(results[item][0]))
             innerCounts[countType] += 0
             htmlStr += '<div {style}>{p}: {q}</div>'.format(
                     p=countType,
```

**Comment by tomasg2012** [comment]
Not sure if it's bad form, but this can also be solved by wrapping all variablesin `str()` when attempting to print a string, and handling None properly in all other cases.  I just keep missing all the print statements that this would happen on...

Is there a particular Resource this happened on?  Did it find a service problem that would've caused this?

**Comment by hohene** [comment]
Yes, we have an error within our /redfish/v1/TaskService schemas, so, when fixing the logger statements, we can drill down into the error easier.  So, it did identify the problem.  This is the output now, showing the error.
```
1 exceptionPropCompliance errors in /redfish/v1/TaskService
1 problemResource errors at ServiceRoot -> Tasks.Tasks -> Tasks.Tasks
 EH: results None 
```

**Comment by tomasg2012** [comment]
Seems I lost the exception printout somewhere, I noticed that just
yesterday.  If you could add the following statement to inside the
'exceptionResource' exception catch block in RedfishServiceValidator.py,
should reveal more:

rsvLogger.exception("")

I noticed this line disappeared along with some handler stuff based on
other issues...

**Comment by tomasg2012** [comment]
Should be fixed with latest 8-10 PR
