### ISSUE TITLE
Validator returns "KeyError: 'Options' " for all the inputs 

### ISSUE THREAD

**Issue by Seretsi** [DMTF/Redfish-Service-Validator#70]
Hello all,

When I make use of the validator, it returns a KeyError reponse right before throwing another exception while handling that first that is described as, "configparser.NoSectionError: No section: 'Options'".  

the first exceptions was:

Traceback (most recent call last):_
   File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values 
    sectiondic = self./__sections[section]
KeyError: 'Options'

**Comment by tomasg2012** [comment]
What is your command line execution?  did you specify a valid config file?

**Comment by tomasg2012** [comment]
We will be working on making these errors more user friendly in the near future, sorry for the trouble.  This error is a result of specifying a config that doesn't exist or is incorrectly written; it is not necessary to specify a config if you plan to use the command line arguments.

**Comment by Seretsi** [comment]
Any of the command line arguments I try return the same response. A simple "-h" command list gets rejected. I don't intend to make use of the config file so I never specify "-c" in my args list.

**Comment by tomasg2012** [comment]
Is there more to this output?  I feel that something is missing...

**Comment by Seretsi** [comment]
I used args list: "-h"

the output was:

Redfish Service Validator args: -h                                                        
Traceback (most recent call last):                                                        
  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values                  
    sectiondict = self._sections[section]                                                 
KeyError: 'Options'                                                                       
                                                                                          
During handling of the above exception, another exception occurred:                       
                                                                                          
Traceback (most recent call last):                                                        
  File "RedfishServiceValidator.py", line 25, in <module>                                 
    useSSL = config.getboolean('Options', 'UseSSL')                                       
  File "/usr/lib/python3.4/configparser.py", line 802, in getboolean                      
    raw=raw, vars=vars)                                                                   
  File "/usr/lib/python3.4/configparser.py", line 776, in _get                            
    return conv(self.get(section, option, **kwargs))                                      
  File "/usr/lib/python3.4/configparser.py", line 754, in get                             
    d = self._unify_values(section, vars)                                                 
  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values                  
    raise NoSectionError(section)                                                         
configparser.NoSectionError: No section: 'Options'

**Comment by tomasg2012** [comment]
Is this using the version available on github, or the one that is published?

**Comment by Seretsi** [comment]
It is the version available on github

**Comment by tomasg2012** [comment]
```
File "RedfishServiceValidator.py", line 25, in 
useSSL = config.getboolean('Options', 'UseSSL')
```
This does not coincide with the latest version on github on line 25

https://github.com/DMTF/Redfish-Service-Validator/blob/master/RedfishServiceValidator.py#L25

To acquire this version, you must download from https://github.com/DMTF/Redfish-Service-Validator or use git as follows:

`git clone https://github.com/DMTF/Redfish-Service-Validator.git`

**Comment by tomasg2012** [comment]
Not sure where this stands.  If the above hasn't resolved, please return to comment on the issue.
