### ISSUE TITLE
Seeing Exception in killSession() at end of program

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#73]
In the case that Authentication is Basic, there is no session, and when RedfishServiceValidator line 709 calls killSession() which calls isSessionOld() there is comparison to initialized variable.

maybe this patch?

    if rst.currentSession.started: 
        rst.currentSession.killSession()

Or maybe patch the entry of killSession()? Or both?

    def killSession(self):
        if self.started:
            if not self.isSessionOld():
                headers = {"X-Auth-Token": self.getSessionKey()}
                headers.update(commonHeader)
                response = requests.delete(str(self.server) + str(self.loc), verify=self.chkCert, headers=headers)
                self.started = False
        return True

**Comment by tomasg2012** [comment]
This was patched in as part of an addendum on Friday, I believe it's been
merged as of then.  It was a bit sudden, so a quick pull should allow you
to run Basic.

**Comment by jbobzin-insyde** [comment]
Did not know you were able to patch outside of the meeting.
Sorry, I was on the Thursday version.
