### ISSUE TITLE
BIOS Attributes are not getting validated.

### ISSUE THREAD

**Issue by skhannade** [DMTF/Redfish-Service-Validator#77]
BIOS Attributes are not getting validated using Redfish Service Validator tool.

The Bios Schema details are as below.

        <Property Name="**Attributes**" Type="**Bios.v1_0_0.Attributes**" Nullable="false">
          <Annotation Term="OData.Description" String="This is the manufacturer/provider specific list of BIOS attributes."/>
          <Annotation Term="OData.LongDescription" String="BIOS Attribute settings appear as additional properties in this object, and can be looked up in the Attribute Registry by their AttributeName."/>
        </Property>
      </EntityType>

      <ComplexType Name="**Attributes**">
        <Annotation Term="OData.AdditionalProperties" Bool="false"/>
        <Annotation Term="Redfish.DynamicPropertyPatterns">
          <Collection>
            <Record>
              <PropertyValue Property="Pattern" String="[A-Za-z0-9]+"/>
              <PropertyValue Property="Type" String="Edm.Primitive"/>
            </Record>
          </Collection>
        </Annotation>
      </ComplexType>

**Comment by mraineri** [comment]
Need to make two types of changes:
- Need to handle a collection of records in the schema and match the Pattern and Type properties with what's reported by the service
- Make a secondary check to lookup the attribute in the BIOS attribute registry to ensure it matches

**Comment by tomasg2012** [comment]
This should be available in the latest PR but doesn't do a complete checkup on the attribute registry or regex available in the schema, simple treats such Attributes as valid additional properties.

**Comment by samerhaj** [comment]
Another change suggested:

- The validator should validate that enum type BIOS Attributes have valid value in the Attribute Registry 
- The validator should vlidate that all AttributeName and ValueName properties in the BIOS Attributes Registry follow valid OData naming rules (this is a common problem that exists/existed in multiple implementations)

**Comment by tomasg2012** [comment]
I'm not totally familiar on how the Attribute Registry is supposed to work for BIOS, but I will be looking into getting some examples soon.

**Comment by mraineri** [comment]
May be this is out of scope of the tool; may consider developing a new tool for registry validation, or part of the BIOS Use Case checker
