### ISSUE TITLE
Validator should be less dependent on $metadata

### ISSUE THREAD

**Issue by mraineri** [DMTF/Redfish-Service-Validator#79]
There are cases where an implementation may have a bad $metadata resource. This has caused some exceptions to occur early in validation. We need to have less dependencies on the $metadata resource and be more intelligent to fallback on local cached schemas or what's published on the DMTF website.

One example of an issue found here: https://redfishforum.com/thread/57/redfish-service-validator-issues

**Comment by billdodd** [comment]
I asked the original poster in the redfishforum what versions of beautifulsoup4 and python 3 they are running. I'm starting to suspect the possibility of a parser problem of some sort.

The traceback shown in the redfishforum post is the same one @jautor got a couple of days ago. But neither Tomas nor I have been able to reproduce it (yet).

**Comment by tomasg2012** [comment]
Maybe we got lost in the reply thread but I think we solved the issue that happened in particular, which was that ultimately there was a 200 response to bogus HTML payload that didn't belong to Redfish.

**Comment by billdodd** [comment]
The issue @mraineri mentioned above from the redfishforum is being worked via issue #80.

**Comment by mraineri** [comment]
Closing; original submitter from the forum filed an issue now
