### ISSUE TITLE
Update validator to use XML parser with beautifulsoup4

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Service-Validator#81]
While investigating how we are using bs4 to parse XML, I learned more about how bs4 does parsing. BS4 doesn't do parsing itself; it delegates parsing to one of several parsers (the built-in python html.parser, lxml or html5lib). We are using the built-in python html.parser. But that parser is for HTML and we are parsing XML. We should be using the XML parser (lxml in XML mode). We've gotten by with using an HTML parser so far. But if we continue to do so, we will almost certainly have odd problems come up as more folks start using the tool.

And in fact the problem where we cannot use bs4 version 4.6.0 with our tool is very likely due to our use of the html.parser along with a code change that went into bs4 4.6.0. I found the following post on the bs4 forum:

https://groups.google.com/forum/?fromgroups#!topic/beautifulsoup/1U9sHiZcaaA

It describes a behavior change in bs4 when comparing tags that have namespace prefixes. Our XML files, of course, have namespace prefixes. But an HTML parser will not understand them. I'm fairly certain that this code change is what is causing our validator to fail when using bs4 4.6.0.

For reference, here is the bs4 code revision referenced:

http://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/revision/442

Switching to an XML parser (lxml) should prevent unexpected/unexplained parser errors in future, will solve the issue with bs4 4.6.0 and later, and should also booth parsing performance.

**Comment by tomasg2012** [comment]
Closed with latest PR.
