### ISSUE TITLE
text/xml header not accepted as http header

### ISSUE THREAD

**Issue by ajaskins** [DMTF/Redfish-Service-Validator#82]
This elseif statement was added 6 days ago, and now it will no longer accept http headers that are "text/xml". 

Code that was changed in traversal.py: 
elif contenttype is not None and **'application**/xml' in contenttype:
    decoded = response.text

If you try to run the Validator without changing this if statement you receive an error beginning with - 

This URI did NOT return XML or Json, this is not a Redfish resource (is this redirected?): /redfish/v1/$metadata

**Comment by mraineri** [comment]
"text/xml" is not a valid value for either the Content-Type or Accept headers per the Redfish specification. Only "application/xml" and "application/json" are valid (depending on the type of resource being accessed).

**Comment by ajaskins** [comment]
Thanks for getting back to me.

I was wondering if this was specified I. The spec, I'll go dig through and
find it, thanks for clarifying!

**Comment by mraineri** [comment]
Closing; text/xml is not acceptable, and other issues are filed for making robustness changes into the tool to work with bad Content-Type headers
