### ISSUE TITLE
Exception thrown: traverseService.py, line 848, getAllLinks insideItem = jsonData.get(item)

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Validator#84]
Attempting to run the tool against an implementation, and getting an exception. Snippet from the log:

> DEBUG - ___
> DEBUG - Resource.v1_0_0, Resource.v1_0_0.Resource:Name
> DEBUG - {'isTerm': False, 'attrs': {'type': 'Resource.Name', 'nullable': 'false', 'name': 'Name'}, 'isNav': False, 'Redfish.Required': {'term': 'Redfish.Required'}}
> DEBUG - HASTYPE
> DEBUG - Resource, Resource.Name
> DEBUG - Reference Org.OData.Core.V1 as OData, http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml
> DEBUG - Reference RedfishExtensions.v1_0_0 as Redfish, /redfish/v1/metadata/RedfishExtensions_v1.xml
> DEBUG - HASTYPE
> DEBUG - Edm, Edm.String
> DEBUG - Schema is Resource.Resource, Resource, Resource
> DEBUG - ___
> DEBUG - Resource
> DEBUG - {'basetype': 'Resource.Item', 'abstract': 'true', 'name': 'Resource'}
> DEBUG - Resource.Item
> DEBUG - Schema is Resource.Item, Item, Resource
> DEBUG - ___
> DEBUG - Item
> DEBUG - {'abstract': 'true', 'name': 'Item'}
> DEBUG - None
> DEBUG - Oem
> DEBUG - Resource.Oem
> DEBUG - {'type': 'Resource.Oem', 'nullable': 'false', 'name': 'Oem'}
> DEBUG - ADDING :::: Oem
> DEBUG - ___
> DEBUG - Resource, Resource.Item:Oem
> DEBUG - {'OData.Description': {'string': 'This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.', 'term': 'OData.Description'}, 'isTerm': False, 'attrs': {'type': 'Resource.Oem', 'nullable': 'false', 'name': 'Oem'}, 'isNav': False, 'OData.LongDescription': {'string': 'The value of this string shall be of the format for the reserved word *Oem*.', 'term': 'OData.LongDescription'}}
> DEBUG - HASTYPE
> DEBUG - Resource, Resource.Oem
> DEBUG - Reference Org.OData.Core.V1 as OData, http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml
> DEBUG - Reference RedfishExtensions.v1_0_0 as Redfish, /redfish/v1/metadata/RedfishExtensions_v1.xml
> DEBUG - go deeper in type
> DEBUG - Schema is Resource.Oem, Oem, Resource
> DEBUG - ___
> DEBUG - Oem
> DEBUG - {'name': 'Oem'}
> DEBUG - None
> DEBUG - OrderedDict()
> DEBUG - OrderedDict()
> ERROR - 
> Traceback (most recent call last):
>   File "RedfishServiceValidator.py", line 547, in validateSingleURI
>     uriName, URI, expectedType, expectedSchema, expectedJson, parent)
>   File "C:\DevTools\Redfish-Service-Validator\traverseService.py", line 546, in __init__
>     self.jsondata, node.propList, node.refs, context=expectedSchema))
>   File "C:\DevTools\Redfish-Service-Validator\traverseService.py", line 879, in getAllLinks
>     jsonData[item], propDict['typeprops'].propList, refDict, prefix + item + '.', context))
>   File "C:\DevTools\Redfish-Service-Validator\traverseService.py", line 848, in getAllLinks
>     insideItem = jsonData.get(item)
> AttributeError: 'list' object has no attribute 'get'
> INFO - Elapsed time: 0:00:07
> INFO - 1
> ERROR - 1 exceptionResource errors in /redfish/v1
> INFO - Counter({'exceptionResource': 1})
> INFO - Validation has failed: 1 problems found
> 
>

**Comment by tomasg2012** [comment]
Would you be able to post the contents of this resource in particular?  Seems that it's expecting a dictionary where there should be a list.

**Comment by samerhaj** [comment]
This is against the service root... I think I found the problem. The Links property is implemented as an array, when it should be an object:


{
...
    "Links": [],
    "Id": "RootService",
    "@odata.id": "/redfish/v1/",
    "@odata.type": "#ServiceRoot.v1_1_0.ServiceRoot",
    "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
...
}

Should be:

{
...
    "Links": {
        "Sessions": {
            "@odata.id": "/redfish/v1/SessionService/Sessions"
        }
    },
    "Id": "RootService",
    "@odata.id": "/redfish/v1/",
    "@odata.type": "#ServiceRoot.v1_1_0.ServiceRoot",
    "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
....
}


But still, it would be helpful for the validator not to crash on this error, but show the failure and continue ...

**Comment by tomasg2012** [comment]
I definitely agree, thanks for catching that.  The tool is making its way toward meaningful errors, and this is a good example.

**Comment by samerhaj** [comment]
I have a fix, and trying to submit a pull request , but do not seem to have permissions for my account (I do have permissions to spmf private repo, just not the tools public repos). 

Can someone please help?

**Comment by tomasg2012** [comment]
I wasn't aware that you needed permissions to submit a PR.  Are you trying to push to this repo as a branch or in your own fork?

**Comment by samerhaj** [comment]
I am trying to create a branch off master and submit the PR off that branch (standard procedure in SPMF... Should i be dong a fork here?)

**Comment by tomasg2012** [comment]
You might want to check in with someone who can monitor and change permissions, I've had issues before with directly submitting branches and PRs and had it rectified before.  perhaps @mraineri

**Comment by mraineri** [comment]
@samerhaj all set; I added you to the Open Source Maintainer team

**Comment by mraineri** [comment]
Normally what outside people can do is fork the repo, make their changes on their fork, and then do a PR to bring their fork back into the main repo

**Comment by samerhaj** [comment]
Thank you @mraineri .. Pull request created for this issue

**Comment by tomasg2012** [comment]
As a question, is there a simple way to pull a commit into a local git repo via the command line?

Is it something like
```git pull <uri> branch/commit```

I have pending changes that I would also like to pull request and I don't want any conflicts...
