### ISSUE TITLE
Failure with ComputerSystem.BootSourceOverrideMode

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#89]
This false-error was fixed some time ago but came back in latest

ERROR - Boot.BootSourceOverrideMode: Appears to be an extra property (check inheritance or casing?)

From this page fragment - 
  "Boot": {
        "BootSourceOverrideEnabled": "Once",
        "BootSourceOverrideTarget": "None",
        "BootSourceOverrideMode": "Legacy",
        "BootSourceOverrideTarget@Redfish.AllowableValues": [
            "None",  "Pxe",  "Cd",  "Usb",  "Hdd",  "BiosSetup",  "Diags",  "UefiTarget" ]
        },

I will leave system on if you want to check

**Comment by tomasg2012** [comment]
In the block labeled by line 832 in _traverseService.py_ for ComplexType, every instance of 'schema' should be 'Schema'.  I could've sworn I did a replace on all these instances of lowercase but maybe didn't do it for 'schema', just 'term', 'navigationproperty' and 'property'.  Thank you for letting me check the system!  It's much easier with the "--payload Single /redfish/v1/Systems/<name>" option

**Comment by jbobzin-insyde** [comment]
This run has Similar error in Chassis.Links.Storage

**Comment by mraineri** [comment]
Closing; fixed with latest PR
