### ISSUE TITLE
Error check for version information of server

### ISSUE THREAD

**Issue by veedu** [DMTF/Redfish-Service-Validator#95]
Hi,

Is there any check for version of properties and their attributes with the tool. We require to do error check on our server's properties' version like chassis_1_0_4 etc.,

Is there any direct or indirect way to do that with the tool?

Thanks,
Vidhya

**Comment by mraineri** [comment]
To clarify, are you asking to check the version of schema a given resource follows, or are you asking for some other version information?

**Comment by mraineri** [comment]
Do you have a concrete example for what you're trying to check? It also sounds like you're asking that the tool ensures the properties conform to the schema version. For example, if the `@odata.type` property says "#Chassis.v1_0_4.Chassis", but the payload contains a property introduced in "#Chassis.v1_2_0.Chassis", the tool will report an error in this case.

**Comment by mraineri** [comment]
Based on what we think the ask is (to ensure the payload conforms to a given version of the schema), this is already covered; for example, if Chassis.v1_2_0 adds new properties, and a payload is using those properties but with the type set to Chassis.v1_0_4.Chassis, the validation will fail.

If this is not the case, please reopen and clarify the request.
