### ISSUE TITLE
Apparent Regression on ServiceMode=True Processing

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Validator#96]
Our implementation has $metadata with local URI for schema download from the schema store on the  server. $metadata does not reference any xml files beyond what is stored on the server.
The individual schema xml files are not edited to remove lines that reference dmtf.org or that reference unused types not found in the local schema store. Because Xml files for Unused schema types are not carried on the service.

Some weeks ago, testing the then-current version,  ServiceMode produced 3 or 4 warnings but no errors.
With the current version pulled today there are 274 errors.
Many errors are because parser is unable to find Resource_v1.xml and flags "Id" and "Name" in every page.

It is also possible that group understanding changed and we now need to redact all local xml to remove dmtf and/or unused references. If so, I missed that change.

With ServiceMode=False there are zero errors.
system is on. ip is not changed. private message if question.

**Comment by tomasg2012** [comment]
I'm curious, is this particular Resource reference in the Metadata?  It's pretty precise about the namespace that is imported.  If say, your Metadata imports "Resource" but an internal XML imports "Resource.v1_0_0" and uses it in its type checking, it will not use Metadata's less specific "Resource" import URL.  This has no effect on what type/version it's actually looking for inside the file.  

It could be changed to simply consider keeping track of the most generic import.  Could a log be produced for this problem?

**Comment by tomasg2012** [comment]
log
```
ERROR - Reference in a Schema /redfish/v1/schema/ServiceRoot_v1.xml not in metadata, this may not be compatible with ServiceMode
ERROR - References missing in metadata: ['Capabilities', 'FabricCollection', 'JsonSchemaFileCollection', 'StorageSystemCollection', 'StorageServiceCollection', 'Resource.v1_0_0', 'OData', 'TaskService', 'Validation']
DEBUG - References generated from /redfish/v1/schema/ServiceRoot_v1.xml: 21 out of 134
...
DEBUG - getting Schema of Resource.v1_0_0 http://redfish.dmtf.org/schemas/v1/Resource_v1.xml
DEBUG - Disallowed out of service URI
INFO - Nonservice URI skipped: http://redfish.dmtf.org/schemas/v1/Resource_v1.xml
DEBUG - This program is currently SERVICE ONLY
DEBUG - ('Resource.v1_0_0', 'http://redfish.dmtf.org/schemas/v1/Resource_v1.xml', 'metadata/Resource_v1.xml')
ERROR - File not found in metadata for Resource_v1.xml: 
```
metadata.xml
```
    <edmx:Reference Uri="/redfish/v1/schema/Resource_v1.xml">
        <edmx:Include Namespace="Resource"/>
        <edmx:Include Namespace="Resource.v1_0_3"/>
        <edmx:Include Namespace="Resource.v1_1_2"/>
        <edmx:Include Namespace="Resource.v1_2_1"/>
        <edmx:Include Namespace="Resource.v1_3_0"/>
    </edmx:Reference>
```

Seems to be the case.  Maybe I should add in some sort of feature to the Reference Checker to create a metadata containing every possible reference on the service?  That would simplify any manual editing of the metadata file.  It can also create a cache of XMLs for the user that could be used.

**Comment by jbobzin-insyde** [comment]
I don't believe the $metadata should need to list every possible errata release- just the highest supported.
v1_0_3 namespace should be accepted as equivalent to v1_0_0, v1_0_1, v1_0_2 and used in its place.
The intention of the errata releases is to fix things.
So 1_0_3 fixes something that was in 1_0_0.
The client should use the highest errata release in the metadata.
And the errata fixes should not be ignored just because an older schema still uses literal v1_0_0.

That is the only client strategy that makes sense to me.

**Comment by tomasg2012** [comment]
Correct, this is a problem with the #68 enhancement not being in place.

**Comment by jbobzin-insyde** [comment]
I know Odata defines this feature of including lines with reference to other 'used' schemas inside the individual schema xml file, but for Redfish I think this causes more trouble then benefit.  $metadata should rule.

**Comment by jbobzin-insyde** [comment]
Mike explained why this is a error
