### ISSUE TITLE
Tool pulls $metadata from schema directory in LocalOnly mode

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Validator#99]
LocalOnly should pull 'local' copies of schema to avoid Internet connectivity requirements, but should not retrieve $metadata from the local repo (must pull it from the Service).

The 'cached' option allows for local override of resources - $metadata should be treated like all other resources (it's just the only XML resource in the model).

**Comment by billdodd** [comment]
Thanks for raising this Jeff. Agreed. Will get the $metadata from the service, even in LocalOnly mode.

**Comment by billdodd** [comment]
Tomas has a Pull Request in progress that should fix this issue.
